//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/jcajce/provider/sphincs/Sphincs256KeyFactorySpi.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"
#include "java/lang/Exception.h"
#include "java/security/InvalidKeyException.h"
#include "java/security/Key.h"
#include "java/security/KeyFactorySpi.h"
#include "java/security/PrivateKey.h"
#include "java/security/PublicKey.h"
#include "java/security/spec/InvalidKeySpecException.h"
#include "java/security/spec/KeySpec.h"
#include "java/security/spec/PKCS8EncodedKeySpec.h"
#include "java/security/spec/X509EncodedKeySpec.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/pkcs/PrivateKeyInfo.h"
#include "org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.h"
#include "org/bouncycastle/pqc/jcajce/provider/sphincs/BCSphincs256PrivateKey.h"
#include "org/bouncycastle/pqc/jcajce/provider/sphincs/BCSphincs256PublicKey.h"
#include "org/bouncycastle/pqc/jcajce/provider/sphincs/Sphincs256KeyFactorySpi.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/jcajce/provider/sphincs/Sphincs256KeyFactorySpi must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaSecurityPrivateKey>)engineGeneratePrivateWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec {
  if ([keySpec isKindOfClass:[JavaSecuritySpecPKCS8EncodedKeySpec class]]) {
    IOSByteArray *encKey = [((JavaSecuritySpecPKCS8EncodedKeySpec *) nil_chk(((JavaSecuritySpecPKCS8EncodedKeySpec *) keySpec))) getEncoded];
    @try {
      return [self generatePrivateWithOrgBouncycastleAsn1PkcsPrivateKeyInfo:OrgBouncycastleAsn1PkcsPrivateKeyInfo_getInstanceWithId_(OrgBouncycastleAsn1ASN1Primitive_fromByteArrayWithByteArray_(encKey))];
    }
    @catch (JavaLangException *e) {
      @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_([e description]);
    }
  }
  @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_(JreStrcat("$@C", @"Unsupported key specification: ", [((id<JavaSecuritySpecKeySpec>) nil_chk(keySpec)) java_getClass], '.'));
}

- (id<JavaSecurityPublicKey>)engineGeneratePublicWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec {
  if ([keySpec isKindOfClass:[JavaSecuritySpecX509EncodedKeySpec class]]) {
    IOSByteArray *encKey = [((JavaSecuritySpecX509EncodedKeySpec *) nil_chk(((JavaSecuritySpecX509EncodedKeySpec *) keySpec))) getEncoded];
    @try {
      return [self generatePublicWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:OrgBouncycastleAsn1X509SubjectPublicKeyInfo_getInstanceWithId_(encKey)];
    }
    @catch (JavaLangException *e) {
      @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_([e description]);
    }
  }
  @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_(JreStrcat("$@C", @"Unknown key specification: ", keySpec, '.'));
}

- (id<JavaSecuritySpecKeySpec>)engineGetKeySpecWithJavaSecurityKey:(id<JavaSecurityKey>)key
                                                      withIOSClass:(IOSClass *)keySpec {
  if ([key isKindOfClass:[OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PrivateKey class]]) {
    if ([JavaSecuritySpecPKCS8EncodedKeySpec_class_() isAssignableFrom:keySpec]) {
      return create_JavaSecuritySpecPKCS8EncodedKeySpec_initWithByteArray_([((id<JavaSecurityKey>) nil_chk(key)) getEncoded]);
    }
  }
  else if ([key isKindOfClass:[OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PublicKey class]]) {
    if ([JavaSecuritySpecX509EncodedKeySpec_class_() isAssignableFrom:keySpec]) {
      return create_JavaSecuritySpecX509EncodedKeySpec_initWithByteArray_([((id<JavaSecurityKey>) nil_chk(key)) getEncoded]);
    }
  }
  else {
    @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_(JreStrcat("$@C", @"Unsupported key type: ", [((id<JavaSecurityKey>) nil_chk(key)) java_getClass], '.'));
  }
  @throw create_JavaSecuritySpecInvalidKeySpecException_initWithNSString_(JreStrcat("$@C", @"Unknown key specification: ", keySpec, '.'));
}

- (id<JavaSecurityKey>)engineTranslateKeyWithJavaSecurityKey:(id<JavaSecurityKey>)key {
  if ([key isKindOfClass:[OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PrivateKey class]] || [key isKindOfClass:[OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PublicKey class]]) {
    return key;
  }
  @throw create_JavaSecurityInvalidKeyException_initWithNSString_(@"Unsupported key type");
}

- (id<JavaSecurityPrivateKey>)generatePrivateWithOrgBouncycastleAsn1PkcsPrivateKeyInfo:(OrgBouncycastleAsn1PkcsPrivateKeyInfo *)keyInfo {
  return create_OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PrivateKey_initWithOrgBouncycastleAsn1PkcsPrivateKeyInfo_(keyInfo);
}

- (id<JavaSecurityPublicKey>)generatePublicWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)keyInfo {
  return create_OrgBouncycastlePqcJcajceProviderSphincsBCSphincs256PublicKey_initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(keyInfo);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaSecurityPrivateKey;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LJavaSecurityPublicKey;", 0x1, 3, 1, 2, -1, -1, -1 },
    { NULL, "LJavaSecuritySpecKeySpec;", 0x11, 4, 5, 2, -1, -1, -1 },
    { NULL, "LJavaSecurityKey;", 0x11, 6, 7, 8, -1, -1, -1 },
    { NULL, "LJavaSecurityPrivateKey;", 0x1, 9, 10, 11, -1, -1, -1 },
    { NULL, "LJavaSecurityPublicKey;", 0x1, 12, 13, 11, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(engineGeneratePrivateWithJavaSecuritySpecKeySpec:);
  methods[2].selector = @selector(engineGeneratePublicWithJavaSecuritySpecKeySpec:);
  methods[3].selector = @selector(engineGetKeySpecWithJavaSecurityKey:withIOSClass:);
  methods[4].selector = @selector(engineTranslateKeyWithJavaSecurityKey:);
  methods[5].selector = @selector(generatePrivateWithOrgBouncycastleAsn1PkcsPrivateKeyInfo:);
  methods[6].selector = @selector(generatePublicWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "engineGeneratePrivate", "LJavaSecuritySpecKeySpec;", "LJavaSecuritySpecInvalidKeySpecException;", "engineGeneratePublic", "engineGetKeySpec", "LJavaSecurityKey;LIOSClass;", "engineTranslateKey", "LJavaSecurityKey;", "LJavaSecurityInvalidKeyException;", "generatePrivate", "LOrgBouncycastleAsn1PkcsPrivateKeyInfo;", "LJavaIoIOException;", "generatePublic", "LOrgBouncycastleAsn1X509SubjectPublicKeyInfo;" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi = { "Sphincs256KeyFactorySpi", "org.bouncycastle.pqc.jcajce.provider.sphincs", ptrTable, methods, NULL, 7, 0x1, 7, 0, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi;
}

@end

void OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi_init(OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi *self) {
  JavaSecurityKeyFactorySpi_init(self);
}

OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi *new_OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi, init)
}

OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi *create_OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcJcajceProviderSphincsSphincs256KeyFactorySpi)
