//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/util/encoders/DecoderException.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Throwable.h"
#include "org/bouncycastle/util/encoders/DecoderException.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/util/encoders/DecoderException must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastleUtilEncodersDecoderException () {
 @public
  JavaLangThrowable *cause_DecoderException_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastleUtilEncodersDecoderException, cause_DecoderException_, JavaLangThrowable *)

@implementation OrgBouncycastleUtilEncodersDecoderException

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause {
  OrgBouncycastleUtilEncodersDecoderException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
  return self;
}

- (JavaLangThrowable *)getCause {
  return cause_DecoderException_;
}

- (void)dealloc {
  RELEASE_(cause_DecoderException_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "LJavaLangThrowable;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:withJavaLangThrowable:);
  methods[1].selector = @selector(getCause);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "cause_DecoderException_", "LJavaLangThrowable;", .constantValue.asLong = 0, 0x2, 1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LJavaLangThrowable;", "cause" };
  static const J2ObjcClassInfo _OrgBouncycastleUtilEncodersDecoderException = { "DecoderException", "org.bouncycastle.util.encoders", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleUtilEncodersDecoderException;
}

@end

void OrgBouncycastleUtilEncodersDecoderException_initWithNSString_withJavaLangThrowable_(OrgBouncycastleUtilEncodersDecoderException *self, NSString *msg, JavaLangThrowable *cause) {
  JavaLangIllegalStateException_initWithNSString_(self, msg);
  JreStrongAssign(&self->cause_DecoderException_, cause);
}

OrgBouncycastleUtilEncodersDecoderException *new_OrgBouncycastleUtilEncodersDecoderException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) {
  J2OBJC_NEW_IMPL(OrgBouncycastleUtilEncodersDecoderException, initWithNSString_withJavaLangThrowable_, msg, cause)
}

OrgBouncycastleUtilEncodersDecoderException *create_OrgBouncycastleUtilEncodersDecoderException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleUtilEncodersDecoderException, initWithNSString_withJavaLangThrowable_, msg, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleUtilEncodersDecoderException)
