//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/es/gob/jmulticard/apdu/dnie/VerifyApduCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobJmulticardApduDnieVerifyApduCommand")
#ifdef RESTRICT_EsGobJmulticardApduDnieVerifyApduCommand
#define INCLUDE_ALL_EsGobJmulticardApduDnieVerifyApduCommand 0
#else
#define INCLUDE_ALL_EsGobJmulticardApduDnieVerifyApduCommand 1
#endif
#undef RESTRICT_EsGobJmulticardApduDnieVerifyApduCommand

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EsGobJmulticardApduDnieVerifyApduCommand_) && (INCLUDE_ALL_EsGobJmulticardApduDnieVerifyApduCommand || defined(INCLUDE_EsGobJmulticardApduDnieVerifyApduCommand))
#define EsGobJmulticardApduDnieVerifyApduCommand_

#define RESTRICT_EsGobJmulticardApduCommandApdu 1
#define INCLUDE_EsGobJmulticardApduCommandApdu 1
#include "es/gob/jmulticard/apdu/CommandApdu.h"

@class IOSByteArray;
@class JavaLangByte;
@class JavaLangInteger;
@class JavaxSecurityAuthCallbackPasswordCallback;

@interface EsGobJmulticardApduDnieVerifyApduCommand : EsGobJmulticardApduCommandApdu
@property (readonly, class) jbyte INS_VERIFY NS_SWIFT_NAME(INS_VERIFY);

#pragma mark Public

- (instancetype _Nonnull)initWithByte:(jbyte)cla
withJavaxSecurityAuthCallbackPasswordCallback:(JavaxSecurityAuthCallbackPasswordCallback *)pinPc;

- (IOSByteArray *)getData;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithByte:(jbyte)arg0
                             withByte:(jbyte)arg1
                             withByte:(jbyte)arg2
                             withByte:(jbyte)arg3
                        withByteArray:(IOSByteArray *)arg4
                  withJavaLangInteger:(JavaLangInteger *)arg5 NS_UNAVAILABLE;

- (instancetype _Nonnull)initWithByteArray:(IOSByteArray *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobJmulticardApduDnieVerifyApduCommand)

inline jbyte EsGobJmulticardApduDnieVerifyApduCommand_get_INS_VERIFY(void);
#define EsGobJmulticardApduDnieVerifyApduCommand_INS_VERIFY 32
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardApduDnieVerifyApduCommand, INS_VERIFY, jbyte)

FOUNDATION_EXPORT void EsGobJmulticardApduDnieVerifyApduCommand_initWithByte_withJavaxSecurityAuthCallbackPasswordCallback_(EsGobJmulticardApduDnieVerifyApduCommand *self, jbyte cla, JavaxSecurityAuthCallbackPasswordCallback *pinPc);

FOUNDATION_EXPORT EsGobJmulticardApduDnieVerifyApduCommand *new_EsGobJmulticardApduDnieVerifyApduCommand_initWithByte_withJavaxSecurityAuthCallbackPasswordCallback_(jbyte cla, JavaxSecurityAuthCallbackPasswordCallback *pinPc) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobJmulticardApduDnieVerifyApduCommand *create_EsGobJmulticardApduDnieVerifyApduCommand_initWithByte_withJavaxSecurityAuthCallbackPasswordCallback_(jbyte cla, JavaxSecurityAuthCallbackPasswordCallback *pinPc);

J2OBJC_TYPE_LITERAL_HEADER(EsGobJmulticardApduDnieVerifyApduCommand)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EsGobJmulticardApduDnieVerifyApduCommand")
