name: felectronic_certificates_platform_interface
description: >-
  A common platform interface for the felectronic_certificates plugin.
  Defines the shared API for Android and iOS certificate management.
version: 1.0.0
repository: https://github.com/nicoacevedor/felectronic_dnie
issue_tracker: https://github.com/nicoacevedor/felectronic_dnie/issues
topics:
  - certificate
  - platform-interface

environment:
  sdk: ^3.11.0

dependencies:
  meta: ^1.7.0
  felectronic_x509: ^1.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.3.3
  very_good_analysis: ^10.2.0
