//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/xmss/XMSSPublicKeyParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters")
#ifdef RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters 1
#endif
#undef RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters || defined(INCLUDE_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters))
#define OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_

#define RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSKeyParameters 1
#define INCLUDE_OrgBouncycastlePqcCryptoXmssXMSSKeyParameters 1
#include "org/bouncycastle/pqc/crypto/xmss/XMSSKeyParameters.h"

#define RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSStoreableObjectInterface 1
#define INCLUDE_OrgBouncycastlePqcCryptoXmssXMSSStoreableObjectInterface 1
#include "org/bouncycastle/pqc/crypto/xmss/XMSSStoreableObjectInterface.h"

#define RESTRICT_OrgBouncycastleUtilEncodable 1
#define INCLUDE_OrgBouncycastleUtilEncodable 1
#include "org/bouncycastle/util/Encodable.h"

@class IOSByteArray;
@class JavaLangBoolean;
@class OrgBouncycastlePqcCryptoXmssXMSSParameters;

@interface OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters : OrgBouncycastlePqcCryptoXmssXMSSKeyParameters < OrgBouncycastlePqcCryptoXmssXMSSStoreableObjectInterface, OrgBouncycastleUtilEncodable >

#pragma mark Public

- (IOSByteArray *)getEncoded;

- (OrgBouncycastlePqcCryptoXmssXMSSParameters *)getParameters;

- (IOSByteArray *)getPublicSeed;

- (IOSByteArray *)getRoot;

- (IOSByteArray *)toByteArray;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithBoolean:(jboolean)arg0
                            withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters)


#endif

#if !defined (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters || defined(INCLUDE_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder))
#define OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder_

@class IOSByteArray;
@class OrgBouncycastlePqcCryptoXmssXMSSParameters;
@class OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters;

@interface OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder : NSObject

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastlePqcCryptoXmssXMSSParameters:(OrgBouncycastlePqcCryptoXmssXMSSParameters *)params;

- (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters *)build;

- (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *)withPublicKeyWithByteArray:(IOSByteArray *)val;

- (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *)withPublicSeedWithByteArray:(IOSByteArray *)val;

- (OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *)withRootWithByteArray:(IOSByteArray *)val;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder)

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *self, OrgBouncycastlePqcCryptoXmssXMSSParameters *params);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *new_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSParameters *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder *create_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSParameters *params);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters_Builder)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSPublicKeyParameters")
