//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/xmss/XMSSKeyGenerationParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters")
#ifdef RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters 1
#endif
#undef RESTRICT_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters || defined(INCLUDE_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters))
#define OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters_

#define RESTRICT_OrgBouncycastleCryptoKeyGenerationParameters 1
#define INCLUDE_OrgBouncycastleCryptoKeyGenerationParameters 1
#include "org/bouncycastle/crypto/KeyGenerationParameters.h"

@class JavaLangInteger;
@class JavaSecuritySecureRandom;
@class OrgBouncycastlePqcCryptoXmssXMSSParameters;

@interface OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters : OrgBouncycastleCryptoKeyGenerationParameters

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastlePqcCryptoXmssXMSSParameters:(OrgBouncycastlePqcCryptoXmssXMSSParameters *)xmssParameters
                                               withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)prng;

- (OrgBouncycastlePqcCryptoXmssXMSSParameters *)getParameters;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)arg0
                                                  withInt:(jint)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters)

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_withJavaSecuritySecureRandom_(OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters *self, OrgBouncycastlePqcCryptoXmssXMSSParameters *xmssParameters, JavaSecuritySecureRandom *prng);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters *new_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_withJavaSecuritySecureRandom_(OrgBouncycastlePqcCryptoXmssXMSSParameters *xmssParameters, JavaSecuritySecureRandom *prng) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters *create_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_withJavaSecuritySecureRandom_(OrgBouncycastlePqcCryptoXmssXMSSParameters *xmssParameters, JavaSecuritySecureRandom *prng);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoXmssXMSSKeyGenerationParameters")
