name: felectronic_dnie_example
description: Demonstrates how to use the felectronic_dnie plugin suite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  felectronic_certificates:
    path: ../../felectronic_certificates
  felectronic_clave:
    path: ../../felectronic_clave
  felectronic_dnie:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
