//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/asn1/kisa/KISAObjectIdentifiers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleAsn1KisaKISAObjectIdentifiers")
#ifdef RESTRICT_OrgBouncycastleAsn1KisaKISAObjectIdentifiers
#define INCLUDE_ALL_OrgBouncycastleAsn1KisaKISAObjectIdentifiers 0
#else
#define INCLUDE_ALL_OrgBouncycastleAsn1KisaKISAObjectIdentifiers 1
#endif
#undef RESTRICT_OrgBouncycastleAsn1KisaKISAObjectIdentifiers

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleAsn1KisaKISAObjectIdentifiers_) && (INCLUDE_ALL_OrgBouncycastleAsn1KisaKISAObjectIdentifiers || defined(INCLUDE_OrgBouncycastleAsn1KisaKISAObjectIdentifiers))
#define OrgBouncycastleAsn1KisaKISAObjectIdentifiers_

@class OrgBouncycastleAsn1ASN1ObjectIdentifier;

@protocol OrgBouncycastleAsn1KisaKISAObjectIdentifiers < JavaObject >

@end

@interface OrgBouncycastleAsn1KisaKISAObjectIdentifiers : NSObject
@property (readonly, class, strong) OrgBouncycastleAsn1ASN1ObjectIdentifier *id_seedCBC NS_SWIFT_NAME(id_seedCBC);
@property (readonly, class, strong) OrgBouncycastleAsn1ASN1ObjectIdentifier *id_seedMAC NS_SWIFT_NAME(id_seedMAC);
@property (readonly, class, strong) OrgBouncycastleAsn1ASN1ObjectIdentifier *pbeWithSHA1AndSEED_CBC NS_SWIFT_NAME(pbeWithSHA1AndSEED_CBC);
@property (readonly, class, strong) OrgBouncycastleAsn1ASN1ObjectIdentifier *id_npki_app_cmsSeed_wrap NS_SWIFT_NAME(id_npki_app_cmsSeed_wrap);
@property (readonly, class, strong) OrgBouncycastleAsn1ASN1ObjectIdentifier *id_mod_cms_seed NS_SWIFT_NAME(id_mod_cms_seed);

@end

J2OBJC_STATIC_INIT(OrgBouncycastleAsn1KisaKISAObjectIdentifiers)

inline OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_get_id_seedCBC(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_id_seedCBC;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleAsn1KisaKISAObjectIdentifiers, id_seedCBC, OrgBouncycastleAsn1ASN1ObjectIdentifier *)

inline OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_get_id_seedMAC(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_id_seedMAC;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleAsn1KisaKISAObjectIdentifiers, id_seedMAC, OrgBouncycastleAsn1ASN1ObjectIdentifier *)

inline OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_get_pbeWithSHA1AndSEED_CBC(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_pbeWithSHA1AndSEED_CBC;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleAsn1KisaKISAObjectIdentifiers, pbeWithSHA1AndSEED_CBC, OrgBouncycastleAsn1ASN1ObjectIdentifier *)

inline OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_get_id_npki_app_cmsSeed_wrap(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_id_npki_app_cmsSeed_wrap;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleAsn1KisaKISAObjectIdentifiers, id_npki_app_cmsSeed_wrap, OrgBouncycastleAsn1ASN1ObjectIdentifier *)

inline OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_get_id_mod_cms_seed(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgBouncycastleAsn1ASN1ObjectIdentifier *OrgBouncycastleAsn1KisaKISAObjectIdentifiers_id_mod_cms_seed;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleAsn1KisaKISAObjectIdentifiers, id_mod_cms_seed, OrgBouncycastleAsn1ASN1ObjectIdentifier *)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1KisaKISAObjectIdentifiers)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleAsn1KisaKISAObjectIdentifiers")
