//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/es/gob/afirma/core/misc/protocol/ParameterNeedsUpdatedVersionException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException")
#ifdef RESTRICT_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException
#define INCLUDE_ALL_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException 0
#else
#define INCLUDE_ALL_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException 1
#endif
#undef RESTRICT_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException_) && (INCLUDE_ALL_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException || defined(INCLUDE_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException))
#define EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException_

#define RESTRICT_EsGobAfirmaCoreMiscProtocolParameterException 1
#define INCLUDE_EsGobAfirmaCoreMiscProtocolParameterException 1
#include "es/gob/afirma/core/misc/protocol/ParameterException.h"

@class JavaLangThrowable;

@interface EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException : EsGobAfirmaCoreMiscProtocolParameterException

#pragma mark Package-Private

- (instancetype __nonnull)init;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException)

FOUNDATION_EXPORT void EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException_init(EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException *self);

FOUNDATION_EXPORT EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException *new_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException *create_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EsGobAfirmaCoreMiscProtocolParameterNeedsUpdatedVersionException")
