//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/jcajce/provider/sphincsplus/BCSPHINCSPlusPublicKey.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/io/ObjectInputStream.h"
#include "java/io/ObjectOutputStream.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.h"
#include "org/bouncycastle/crypto/CipherParameters.h"
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"
#include "org/bouncycastle/pqc/crypto/sphincsplus/SPHINCSPlusParameters.h"
#include "org/bouncycastle/pqc/crypto/sphincsplus/SPHINCSPlusPublicKeyParameters.h"
#include "org/bouncycastle/pqc/crypto/util/PublicKeyFactory.h"
#include "org/bouncycastle/pqc/crypto/util/SubjectPublicKeyInfoFactory.h"
#include "org/bouncycastle/pqc/jcajce/provider/sphincsplus/BCSPHINCSPlusPublicKey.h"
#include "org/bouncycastle/pqc/jcajce/spec/SPHINCSPlusParameterSpec.h"
#include "org/bouncycastle/util/Arrays.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/jcajce/provider/sphincsplus/BCSPHINCSPlusPublicKey must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey () {
 @public
  OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *params_;
}

- (void)init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)keyInfo OBJC_METHOD_FAMILY_NONE;

- (void)readObjectWithJavaIoObjectInputStream:(JavaIoObjectInputStream *)inArg;

- (void)writeObjectWithJavaIoObjectOutputStream:(JavaIoObjectOutputStream *)outArg;

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, params_, OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *)

inline jlong OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_get_serialVersionUID(void);
#define OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, serialVersionUID, jlong)

__attribute__((unused)) static void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, OrgBouncycastleAsn1X509SubjectPublicKeyInfo *keyInfo);

__attribute__((unused)) static void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_readObjectWithJavaIoObjectInputStream_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, JavaIoObjectInputStream *inArg);

__attribute__((unused)) static void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_writeObjectWithJavaIoObjectOutputStream_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, JavaIoObjectOutputStream *outArg);

@implementation OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey

- (instancetype)initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters:(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *)params {
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_(self, params);
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)keyInfo {
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(self, keyInfo);
  return self;
}

- (void)init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)keyInfo {
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(self, keyInfo);
}

- (jboolean)isEqual:(id)o {
  if (JreObjectEqualsEquals(o, self)) {
    return true;
  }
  if ([o isKindOfClass:[OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey class]]) {
    OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *otherKey = (OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *) o;
    return OrgBouncycastleUtilArrays_areEqualWithByteArray_withByteArray_([((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *) nil_chk(params_)) getEncoded], [((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *) nil_chk(((OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *) nil_chk(otherKey))->params_)) getEncoded]);
  }
  return false;
}

- (NSUInteger)hash {
  return OrgBouncycastleUtilArrays_hashCodeWithByteArray_([((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *) nil_chk(params_)) getEncoded]);
}

- (NSString *)getAlgorithm {
  return @"SPHINCS+";
}

- (IOSByteArray *)getEncoded {
  @try {
    OrgBouncycastleAsn1X509SubjectPublicKeyInfo *pki = OrgBouncycastlePqcCryptoUtilSubjectPublicKeyInfoFactory_createSubjectPublicKeyInfoWithOrgBouncycastleCryptoParamsAsymmetricKeyParameter_(params_);
    return [((OrgBouncycastleAsn1X509SubjectPublicKeyInfo *) nil_chk(pki)) getEncoded];
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
}

- (NSString *)getFormat {
  return @"X.509";
}

- (OrgBouncycastlePqcJcajceSpecSPHINCSPlusParameterSpec *)getParameterSpec {
  return OrgBouncycastlePqcJcajceSpecSPHINCSPlusParameterSpec_fromNameWithNSString_([((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusParameters *) nil_chk([((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *) nil_chk(params_)) getParameters])) getName]);
}

- (id<OrgBouncycastleCryptoCipherParameters>)getKeyParams {
  return params_;
}

- (void)readObjectWithJavaIoObjectInputStream:(JavaIoObjectInputStream *)inArg {
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_readObjectWithJavaIoObjectInputStream_(self, inArg);
}

- (void)writeObjectWithJavaIoObjectOutputStream:(JavaIoObjectOutputStream *)outArg {
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_writeObjectWithJavaIoObjectOutputStream_(self, outArg);
}

- (void)dealloc {
  RELEASE_(params_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x2, 3, 1, 2, -1, -1, -1 },
    { NULL, "Z", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 6, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcJcajceSpecSPHINCSPlusParameterSpec;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleCryptoCipherParameters;", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 7, 8, 9, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 11, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters:);
  methods[1].selector = @selector(initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:);
  methods[2].selector = @selector(init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:);
  methods[3].selector = @selector(isEqual:);
  methods[4].selector = @selector(hash);
  methods[5].selector = @selector(getAlgorithm);
  methods[6].selector = @selector(getEncoded);
  methods[7].selector = @selector(getFormat);
  methods[8].selector = @selector(getParameterSpec);
  methods[9].selector = @selector(getKeyParams);
  methods[10].selector = @selector(readObjectWithJavaIoObjectInputStream:);
  methods[11].selector = @selector(writeObjectWithJavaIoObjectOutputStream:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "params_", "LOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters;", .constantValue.asLong = 0, 0x82, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters;", "LOrgBouncycastleAsn1X509SubjectPublicKeyInfo;", "LJavaIoIOException;", "init", "equals", "LNSObject;", "hashCode", "readObject", "LJavaIoObjectInputStream;", "LJavaIoIOException;LJavaLangClassNotFoundException;", "writeObject", "LJavaIoObjectOutputStream;" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey = { "BCSPHINCSPlusPublicKey", "org.bouncycastle.pqc.jcajce.provider.sphincsplus", ptrTable, methods, fields, 7, 0x1, 12, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey;
}

@end

void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *params) {
  NSObject_init(self);
  JreStrongAssign(&self->params_, params);
}

OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *new_OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *params) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_, params)
}

OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *create_OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *params) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, initWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters_, params)
}

void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, OrgBouncycastleAsn1X509SubjectPublicKeyInfo *keyInfo) {
  NSObject_init(self);
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(self, keyInfo);
}

OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *new_OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *keyInfo) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_, keyInfo)
}

OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *create_OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *keyInfo) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey, initWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_, keyInfo)
}

void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, OrgBouncycastleAsn1X509SubjectPublicKeyInfo *keyInfo) {
  JreStrongAssign(&self->params_, (OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters *) cast_chk(OrgBouncycastlePqcCryptoUtilPublicKeyFactory_createKeyWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(keyInfo), [OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusPublicKeyParameters class]));
}

void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_readObjectWithJavaIoObjectInputStream_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, JavaIoObjectInputStream *inArg) {
  [((JavaIoObjectInputStream *) nil_chk(inArg)) defaultReadObject];
  IOSByteArray *enc = (IOSByteArray *) cast_chk([inArg readObject], [IOSByteArray class]);
  OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_init__WithOrgBouncycastleAsn1X509SubjectPublicKeyInfo_(self, OrgBouncycastleAsn1X509SubjectPublicKeyInfo_getInstanceWithId_(enc));
}

void OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey_writeObjectWithJavaIoObjectOutputStream_(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey *self, JavaIoObjectOutputStream *outArg) {
  [((JavaIoObjectOutputStream *) nil_chk(outArg)) defaultWriteObject];
  [outArg writeObjectWithId:[self getEncoded]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcJcajceProviderSphincsplusBCSPHINCSPlusPublicKey)
