//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/crypto/engines/DESedeEngine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleCryptoEnginesDESedeEngine")
#ifdef RESTRICT_OrgBouncycastleCryptoEnginesDESedeEngine
#define INCLUDE_ALL_OrgBouncycastleCryptoEnginesDESedeEngine 0
#else
#define INCLUDE_ALL_OrgBouncycastleCryptoEnginesDESedeEngine 1
#endif
#undef RESTRICT_OrgBouncycastleCryptoEnginesDESedeEngine

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleCryptoEnginesDESedeEngine_) && (INCLUDE_ALL_OrgBouncycastleCryptoEnginesDESedeEngine || defined(INCLUDE_OrgBouncycastleCryptoEnginesDESedeEngine))
#define OrgBouncycastleCryptoEnginesDESedeEngine_

#define RESTRICT_OrgBouncycastleCryptoEnginesDESEngine 1
#define INCLUDE_OrgBouncycastleCryptoEnginesDESEngine 1
#include "org/bouncycastle/crypto/engines/DESEngine.h"

@class IOSByteArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol OrgBouncycastleCryptoCipherParameters;

@interface OrgBouncycastleCryptoEnginesDESedeEngine : OrgBouncycastleCryptoEnginesDESEngine
@property (readonly, class) jint BLOCK_SIZE NS_SWIFT_NAME(BLOCK_SIZE);

#pragma mark Public

- (instancetype _Nonnull)init;

- (NSString *)getAlgorithmName;

- (jint)getBlockSize;

- (void)init__WithBoolean:(jboolean)encrypting
withOrgBouncycastleCryptoCipherParameters:(id<OrgBouncycastleCryptoCipherParameters>)params OBJC_METHOD_FAMILY_NONE;

- (jint)processBlockWithByteArray:(IOSByteArray *)inArg
                          withInt:(jint)inOff
                    withByteArray:(IOSByteArray *)outArg
                          withInt:(jint)outOff;

- (void)reset;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleCryptoEnginesDESedeEngine)

inline jint OrgBouncycastleCryptoEnginesDESedeEngine_get_BLOCK_SIZE(void);
#define OrgBouncycastleCryptoEnginesDESedeEngine_BLOCK_SIZE 8
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastleCryptoEnginesDESedeEngine, BLOCK_SIZE, jint)

FOUNDATION_EXPORT void OrgBouncycastleCryptoEnginesDESedeEngine_init(OrgBouncycastleCryptoEnginesDESedeEngine *self);

FOUNDATION_EXPORT OrgBouncycastleCryptoEnginesDESedeEngine *new_OrgBouncycastleCryptoEnginesDESedeEngine_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleCryptoEnginesDESedeEngine *create_OrgBouncycastleCryptoEnginesDESedeEngine_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleCryptoEnginesDESedeEngine)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleCryptoEnginesDESedeEngine")
