//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/math/linearalgebra/ByteUtils.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/ArrayIndexOutOfBoundsException.h"
#include "java/lang/Boolean.h"
#include "java/lang/Byte.h"
#include "java/lang/Character.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "java/lang/annotation/Annotation.h"
#include "org/bouncycastle/pqc/math/linearalgebra/ByteUtils.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/math/linearalgebra/ByteUtils must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcMathLinearalgebraByteUtils ()

- (instancetype)init;

@end

inline IOSCharArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_get_HEX_CHARS(void);
static IOSCharArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastlePqcMathLinearalgebraByteUtils, HEX_CHARS, IOSCharArray *)

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraByteUtils_init(OrgBouncycastlePqcMathLinearalgebraByteUtils *self);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraByteUtils *new_OrgBouncycastlePqcMathLinearalgebraByteUtils_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraByteUtils *create_OrgBouncycastlePqcMathLinearalgebraByteUtils_init(void);

__attribute__((unused)) static IOSObjectArray *OrgBouncycastlePqcMathLinearalgebraByteUtils__Annotations$0(void);

J2OBJC_INITIALIZED_DEFN(OrgBouncycastlePqcMathLinearalgebraByteUtils)

@implementation OrgBouncycastlePqcMathLinearalgebraByteUtils

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jboolean)equalsWithByteArray:(IOSByteArray *)left
                  withByteArray:(IOSByteArray *)right {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray_withByteArray_(left, right);
}

+ (jboolean)equalsWithByteArray2:(IOSObjectArray *)left
                  withByteArray2:(IOSObjectArray *)right {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray2_withByteArray2_(left, right);
}

+ (jboolean)equalsWithByteArray3:(IOSObjectArray *)left
                  withByteArray3:(IOSObjectArray *)right {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray3_withByteArray3_(left, right);
}

+ (jint)deepHashCodeWithByteArray:(IOSByteArray *)array {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray_(array);
}

+ (jint)deepHashCodeWithByteArray2:(IOSObjectArray *)array {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray2_(array);
}

+ (jint)deepHashCodeWithByteArray3:(IOSObjectArray *)array {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray3_(array);
}

+ (IOSByteArray *)cloneWithByteArray:(IOSByteArray *)array {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_cloneWithByteArray_(array);
}

+ (IOSByteArray *)fromHexStringWithNSString:(NSString *)s {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_fromHexStringWithNSString_(s);
}

+ (NSString *)toHexStringWithByteArray:(IOSByteArray *)input {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_toHexStringWithByteArray_(input);
}

+ (NSString *)toHexStringWithByteArray:(IOSByteArray *)input
                          withNSString:(NSString *)prefix
                          withNSString:(NSString *)seperator {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_toHexStringWithByteArray_withNSString_withNSString_(input, prefix, seperator);
}

+ (NSString *)toBinaryStringWithByteArray:(IOSByteArray *)input {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_toBinaryStringWithByteArray_(input);
}

+ (IOSByteArray *)xor__WithByteArray:(IOSByteArray *)x1
                       withByteArray:(IOSByteArray *)x2 {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_xor__WithByteArray_withByteArray_(x1, x2);
}

+ (IOSByteArray *)concatenateWithByteArray:(IOSByteArray *)x1
                             withByteArray:(IOSByteArray *)x2 {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_concatenateWithByteArray_withByteArray_(x1, x2);
}

+ (IOSByteArray *)concatenateWithByteArray2:(IOSObjectArray *)array {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_concatenateWithByteArray2_(array);
}

+ (IOSObjectArray *)splitWithByteArray:(IOSByteArray *)input
                               withInt:(jint)index {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_splitWithByteArray_withInt_(input, index);
}

+ (IOSByteArray *)subArrayWithByteArray:(IOSByteArray *)input
                                withInt:(jint)start
                                withInt:(jint)end {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_subArrayWithByteArray_withInt_withInt_(input, start, end);
}

+ (IOSByteArray *)subArrayWithByteArray:(IOSByteArray *)input
                                withInt:(jint)start {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_subArrayWithByteArray_withInt_(input, start);
}

+ (IOSCharArray *)toCharArrayWithByteArray:(IOSByteArray *)input {
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_toCharArrayWithByteArray_(input);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 0, 2, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 0, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 4, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 4, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 4, 7, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 8, 5, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 9, 10, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, 11, 5, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, 11, 12, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, 13, 5, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 14, 1, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 15, 1, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 15, 6, -1, -1, -1, -1 },
    { NULL, "[[B", 0x9, 16, 17, 18, -1, -1, -1 },
    { NULL, "[B", 0x9, 19, 20, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 19, 17, -1, -1, -1, -1 },
    { NULL, "[C", 0x9, 21, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(equalsWithByteArray:withByteArray:);
  methods[2].selector = @selector(equalsWithByteArray2:withByteArray2:);
  methods[3].selector = @selector(equalsWithByteArray3:withByteArray3:);
  methods[4].selector = @selector(deepHashCodeWithByteArray:);
  methods[5].selector = @selector(deepHashCodeWithByteArray2:);
  methods[6].selector = @selector(deepHashCodeWithByteArray3:);
  methods[7].selector = @selector(cloneWithByteArray:);
  methods[8].selector = @selector(fromHexStringWithNSString:);
  methods[9].selector = @selector(toHexStringWithByteArray:);
  methods[10].selector = @selector(toHexStringWithByteArray:withNSString:withNSString:);
  methods[11].selector = @selector(toBinaryStringWithByteArray:);
  methods[12].selector = @selector(xor__WithByteArray:withByteArray:);
  methods[13].selector = @selector(concatenateWithByteArray:withByteArray:);
  methods[14].selector = @selector(concatenateWithByteArray2:);
  methods[15].selector = @selector(splitWithByteArray:withInt:);
  methods[16].selector = @selector(subArrayWithByteArray:withInt:withInt:);
  methods[17].selector = @selector(subArrayWithByteArray:withInt:);
  methods[18].selector = @selector(toCharArrayWithByteArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "HEX_CHARS", "[C", .constantValue.asLong = 0, 0x1a, -1, 22, -1, -1 },
  };
  static const void *ptrTable[] = { "equals", "[B[B", "[[B[[B", "[[[B[[[B", "deepHashCode", "[B", "[[B", "[[[B", "clone", "fromHexString", "LNSString;", "toHexString", "[BLNSString;LNSString;", "toBinaryString", "xor", "concatenate", "split", "[BI", "LJavaLangArrayIndexOutOfBoundsException;", "subArray", "[BII", "toCharArray", &OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS, (void *)&OrgBouncycastlePqcMathLinearalgebraByteUtils__Annotations$0 };
  static const J2ObjcClassInfo _OrgBouncycastlePqcMathLinearalgebraByteUtils = { "ByteUtils", "org.bouncycastle.pqc.math.linearalgebra", ptrTable, methods, fields, 7, 0x11, 19, 1, -1, -1, -1, -1, 23 };
  return &_OrgBouncycastlePqcMathLinearalgebraByteUtils;
}

+ (void)initialize {
  if (self == [OrgBouncycastlePqcMathLinearalgebraByteUtils class]) {
    JreStrongAssignAndConsume(&OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS, [IOSCharArray newArrayWithChars:(jchar[]){ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' } count:16]);
    J2OBJC_SET_INITIALIZED(OrgBouncycastlePqcMathLinearalgebraByteUtils)
  }
}

@end

void OrgBouncycastlePqcMathLinearalgebraByteUtils_init(OrgBouncycastlePqcMathLinearalgebraByteUtils *self) {
  NSObject_init(self);
}

OrgBouncycastlePqcMathLinearalgebraByteUtils *new_OrgBouncycastlePqcMathLinearalgebraByteUtils_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraByteUtils, init)
}

OrgBouncycastlePqcMathLinearalgebraByteUtils *create_OrgBouncycastlePqcMathLinearalgebraByteUtils_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraByteUtils, init)
}

jboolean OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray_withByteArray_(IOSByteArray *left, IOSByteArray *right) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  if (left == nil) {
    return right == nil;
  }
  if (right == nil) {
    return false;
  }
  if (left->size_ != right->size_) {
    return false;
  }
  jboolean result = true;
  for (jint i = left->size_ - 1; i >= 0; i--) {
    result &= (IOSByteArray_Get(left, i) == IOSByteArray_Get(right, i));
  }
  return result;
}

jboolean OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray2_withByteArray2_(IOSObjectArray *left, IOSObjectArray *right) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  if (((IOSObjectArray *) nil_chk(left))->size_ != ((IOSObjectArray *) nil_chk(right))->size_) {
    return false;
  }
  jboolean result = true;
  for (jint i = left->size_ - 1; i >= 0; i--) {
    result &= OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray_withByteArray_(IOSObjectArray_Get(left, i), IOSObjectArray_Get(right, i));
  }
  return result;
}

jboolean OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray3_withByteArray3_(IOSObjectArray *left, IOSObjectArray *right) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  if (((IOSObjectArray *) nil_chk(left))->size_ != ((IOSObjectArray *) nil_chk(right))->size_) {
    return false;
  }
  jboolean result = true;
  for (jint i = left->size_ - 1; i >= 0; i--) {
    if (((IOSObjectArray *) nil_chk(IOSObjectArray_Get(left, i)))->size_ != ((IOSObjectArray *) nil_chk(IOSObjectArray_Get(right, i)))->size_) {
      return false;
    }
    for (jint j = ((IOSObjectArray *) nil_chk(IOSObjectArray_Get(left, i)))->size_ - 1; j >= 0; j--) {
      result &= OrgBouncycastlePqcMathLinearalgebraByteUtils_equalsWithByteArray_withByteArray_(IOSObjectArray_Get(nil_chk(IOSObjectArray_Get(left, i)), j), IOSObjectArray_Get(nil_chk(IOSObjectArray_Get(right, i)), j));
    }
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray_(IOSByteArray *array) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  jint result = 1;
  for (jint i = 0; i < ((IOSByteArray *) nil_chk(array))->size_; i++) {
    result = 31 * result + IOSByteArray_Get(array, i);
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray2_(IOSObjectArray *array) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  jint result = 1;
  for (jint i = 0; i < ((IOSObjectArray *) nil_chk(array))->size_; i++) {
    result = 31 * result + OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray_(IOSObjectArray_Get(array, i));
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray3_(IOSObjectArray *array) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  jint result = 1;
  for (jint i = 0; i < ((IOSObjectArray *) nil_chk(array))->size_; i++) {
    result = 31 * result + OrgBouncycastlePqcMathLinearalgebraByteUtils_deepHashCodeWithByteArray2_(IOSObjectArray_Get(array, i));
  }
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_cloneWithByteArray_(IOSByteArray *array) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  if (array == nil) {
    return nil;
  }
  IOSByteArray *result = [IOSByteArray arrayWithLength:array->size_];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(array, 0, result, 0, array->size_);
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_fromHexStringWithNSString_(NSString *s) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  IOSCharArray *rawChars = [((NSString *) nil_chk([((NSString *) nil_chk(s)) uppercaseString])) java_toCharArray];
  jint hexChars = 0;
  for (jint i = 0; i < ((IOSCharArray *) nil_chk(rawChars))->size_; i++) {
    if ((IOSCharArray_Get(rawChars, i) >= '0' && IOSCharArray_Get(rawChars, i) <= '9') || (IOSCharArray_Get(rawChars, i) >= 'A' && IOSCharArray_Get(rawChars, i) <= 'F')) {
      hexChars++;
    }
  }
  IOSByteArray *byteString = [IOSByteArray arrayWithLength:JreRShift32((hexChars + 1), 1)];
  jint pos = hexChars & 1;
  for (jint i = 0; i < rawChars->size_; i++) {
    if (IOSCharArray_Get(rawChars, i) >= '0' && IOSCharArray_Get(rawChars, i) <= '9') {
      JreLShiftAssignByte(IOSByteArray_GetRef(byteString, JreRShift32(pos, 1)), 4);
      *IOSByteArray_GetRef(byteString, JreRShift32(pos, 1)) |= IOSCharArray_Get(rawChars, i) - '0';
    }
    else if (IOSCharArray_Get(rawChars, i) >= 'A' && IOSCharArray_Get(rawChars, i) <= 'F') {
      JreLShiftAssignByte(IOSByteArray_GetRef(byteString, JreRShift32(pos, 1)), 4);
      *IOSByteArray_GetRef(byteString, JreRShift32(pos, 1)) |= IOSCharArray_Get(rawChars, i) - 'A' + 10;
    }
    else {
      continue;
    }
    pos++;
  }
  return byteString;
}

NSString *OrgBouncycastlePqcMathLinearalgebraByteUtils_toHexStringWithByteArray_(IOSByteArray *input) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  NSString *result = @"";
  for (jint i = 0; i < ((IOSByteArray *) nil_chk(input))->size_; i++) {
    JreStrAppend(&result, "C", IOSCharArray_Get(nil_chk(OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS), (JreURShift32(IOSByteArray_Get(input, i), 4)) & (jint) 0x0f));
    JreStrAppend(&result, "C", IOSCharArray_Get(OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS, (IOSByteArray_Get(input, i)) & (jint) 0x0f));
  }
  return result;
}

NSString *OrgBouncycastlePqcMathLinearalgebraByteUtils_toHexStringWithByteArray_withNSString_withNSString_(IOSByteArray *input, NSString *prefix, NSString *seperator) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  NSString *result = [NSString stringWithString:prefix];
  for (jint i = 0; i < ((IOSByteArray *) nil_chk(input))->size_; i++) {
    JreStrAppend(&result, "C", IOSCharArray_Get(nil_chk(OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS), (JreURShift32(IOSByteArray_Get(input, i), 4)) & (jint) 0x0f));
    JreStrAppend(&result, "C", IOSCharArray_Get(OrgBouncycastlePqcMathLinearalgebraByteUtils_HEX_CHARS, (IOSByteArray_Get(input, i)) & (jint) 0x0f));
    if (i < input->size_ - 1) {
      JreStrAppend(&result, "$", seperator);
    }
  }
  return result;
}

NSString *OrgBouncycastlePqcMathLinearalgebraByteUtils_toBinaryStringWithByteArray_(IOSByteArray *input) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  NSString *result = @"";
  jint i;
  for (i = 0; i < ((IOSByteArray *) nil_chk(input))->size_; i++) {
    jint e = IOSByteArray_Get(input, i);
    for (jint ii = 0; ii < 8; ii++) {
      jint b = (JreURShift32(e, ii)) & 1;
      JreStrAppend(&result, "I", b);
    }
    if (i != input->size_ - 1) {
      JreStrAppend(&result, "$", @" ");
    }
  }
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_xor__WithByteArray_withByteArray_(IOSByteArray *x1, IOSByteArray *x2) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  IOSByteArray *out = [IOSByteArray arrayWithLength:((IOSByteArray *) nil_chk(x1))->size_];
  for (jint i = x1->size_ - 1; i >= 0; i--) {
    *IOSByteArray_GetRef(out, i) = (jbyte) (IOSByteArray_Get(x1, i) ^ IOSByteArray_Get(nil_chk(x2), i));
  }
  return out;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_concatenateWithByteArray_withByteArray_(IOSByteArray *x1, IOSByteArray *x2) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  IOSByteArray *result = [IOSByteArray arrayWithLength:((IOSByteArray *) nil_chk(x1))->size_ + ((IOSByteArray *) nil_chk(x2))->size_];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(x1, 0, result, 0, x1->size_);
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(x2, 0, result, x1->size_, x2->size_);
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_concatenateWithByteArray2_(IOSObjectArray *array) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  jint rowLength = ((IOSByteArray *) nil_chk(IOSObjectArray_Get(nil_chk(array), 0)))->size_;
  IOSByteArray *result = [IOSByteArray arrayWithLength:array->size_ * rowLength];
  jint index = 0;
  for (jint i = 0; i < array->size_; i++) {
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(IOSObjectArray_Get(array, i), 0, result, index, rowLength);
    index += rowLength;
  }
  return result;
}

IOSObjectArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_splitWithByteArray_withInt_(IOSByteArray *input, jint index) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  if (index > ((IOSByteArray *) nil_chk(input))->size_) {
    @throw create_JavaLangArrayIndexOutOfBoundsException_init();
  }
  IOSObjectArray *result = [IOSObjectArray arrayWithLength:2 type:IOSClass_byteArray(1)];
  IOSObjectArray_SetAndConsume(result, 0, [IOSByteArray newArrayWithLength:index]);
  IOSObjectArray_SetAndConsume(result, 1, [IOSByteArray newArrayWithLength:input->size_ - index]);
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(input, 0, IOSObjectArray_Get(result, 0), 0, index);
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(input, index, IOSObjectArray_Get(result, 1), 0, input->size_ - index);
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_subArrayWithByteArray_withInt_withInt_(IOSByteArray *input, jint start, jint end) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  IOSByteArray *result = [IOSByteArray arrayWithLength:end - start];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(input, start, result, 0, end - start);
  return result;
}

IOSByteArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_subArrayWithByteArray_withInt_(IOSByteArray *input, jint start) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  return OrgBouncycastlePqcMathLinearalgebraByteUtils_subArrayWithByteArray_withInt_withInt_(input, start, ((IOSByteArray *) nil_chk(input))->size_);
}

IOSCharArray *OrgBouncycastlePqcMathLinearalgebraByteUtils_toCharArrayWithByteArray_(IOSByteArray *input) {
  OrgBouncycastlePqcMathLinearalgebraByteUtils_initialize();
  IOSCharArray *result = [IOSCharArray arrayWithLength:((IOSByteArray *) nil_chk(input))->size_];
  for (jint i = 0; i < input->size_; i++) {
    *IOSCharArray_GetRef(result, i) = (jchar) IOSByteArray_Get(input, i);
  }
  return result;
}

IOSObjectArray *OrgBouncycastlePqcMathLinearalgebraByteUtils__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated(false, @"") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcMathLinearalgebraByteUtils)
