//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/math/linearalgebra/GF2nPolynomial.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2Polynomial.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nElement.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nField.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nONBElement.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nONBField.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nPolynomial.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nPolynomialElement.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2nPolynomialField.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GFElement.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/math/linearalgebra/GF2nPolynomial must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial () {
 @public
  IOSObjectArray *coeff_;
  jint size_;
}

- (instancetype)initWithInt:(jint)deg;

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, coeff_, IOSObjectArray *)

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint deg);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(jint deg) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(jint deg);

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self);

__attribute__((unused)) static jint OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self);

__attribute__((unused)) static jint OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self);

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_enlargeWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint k);

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self);

__attribute__((unused)) static jboolean OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_isZero(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nElement *s);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *g);

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shiftThisLeftWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint amount);

__attribute__((unused)) static IOSObjectArray *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b);

@implementation OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial

- (instancetype)initWithInt:(jint)deg
withOrgBouncycastlePqcMathLinearalgebraGF2nElement:(OrgBouncycastlePqcMathLinearalgebraGF2nElement *)elem {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_(self, deg, elem);
  return self;
}

- (instancetype)initWithInt:(jint)deg {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(self, deg);
  return self;
}

- (instancetype)initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)a {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, a);
  return self;
}

- (instancetype)initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial:(OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *)polynomial
                        withOrgBouncycastlePqcMathLinearalgebraGF2nField:(OrgBouncycastlePqcMathLinearalgebraGF2nField *)B1 {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_(self, polynomial, B1);
  return self;
}

- (void)assignZeroToElements {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(self);
}

- (jint)size {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self);
}

- (jint)getDegree {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(self);
}

- (void)enlargeWithInt:(jint)k {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_enlargeWithInt_(self, k);
}

- (void)shrink {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(self);
}

- (void)setWithInt:(jint)index
withOrgBouncycastlePqcMathLinearalgebraGF2nElement:(OrgBouncycastlePqcMathLinearalgebraGF2nElement *)elem {
  if (!([elem isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement class]]) && !([elem isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nONBElement class]])) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"PolynomialGF2n.set f must be an instance of either GF2nPolynomialElement or GF2nONBElement!");
  }
  IOSObjectArray_Set(nil_chk(coeff_), index, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(elem)) java_clone], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nElement *)atWithInt:(jint)index {
  return IOSObjectArray_Get(nil_chk(coeff_), index);
}

- (jboolean)isZero {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_isZero(self);
}

- (jboolean)isEqual:(id)other {
  if (other == nil || !([other isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial class]])) {
    return false;
  }
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *otherPol = (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *) cast_chk(other, [OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial class]);
  if (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(self) != OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(otherPol)) {
    return false;
  }
  jint i;
  for (i = 0; i < size_; i++) {
    if (![((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(coeff_), i))) isEqual:IOSObjectArray_Get(otherPol->coeff_, i)]) {
      return false;
    }
  }
  return true;
}

- (NSUInteger)hash {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(self) + ((jint) [((IOSObjectArray *) nil_chk(coeff_)) hash]);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement:(OrgBouncycastlePqcMathLinearalgebraGF2nElement *)s {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement_(self, s);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)multiplyAndReduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b
                                                                        withOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)g {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(nil_chk(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b)), g);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)g {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, g);
}

- (void)shiftThisLeftWithInt:(jint)amount {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shiftThisLeftWithInt_(self, amount);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)shiftLeftWithInt:(jint)amount {
  if (amount <= 0) {
    return create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self);
  }
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *result = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_(size_ + amount, IOSObjectArray_Get(nil_chk(coeff_), 0));
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(result);
  for (jint i = 0; i < size_; i++) {
    IOSObjectArray_Set(nil_chk(result->coeff_), i + amount, IOSObjectArray_Get(coeff_, i));
  }
  return result;
}

- (IOSObjectArray *)divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)quotientWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)b {
  IOSObjectArray *result = [IOSObjectArray arrayWithLength:2 type:OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_class_()];
  result = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
  return IOSObjectArray_Get(nil_chk(result), 0);
}

- (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)gcdWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *)g {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *a = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(g);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(a);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(b);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *c;
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *result;
  OrgBouncycastlePqcMathLinearalgebraGF2nElement *alpha;
  while (!OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_isZero(nil_chk(b))) {
    c = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(a, b);
    a = b;
    b = c;
  }
  alpha = IOSObjectArray_Get(nil_chk(a->coeff_), OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(a));
  result = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement_(a, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(alpha)) invert], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
  return result;
}

- (void)dealloc {
  RELEASE_(coeff_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x11, 4, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x11, 5, 0, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nElement;", 0x11, 6, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x11, 7, 8, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 9, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 10, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 11, 12, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 13, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 14, 15, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 16, 2, 17, -1, -1, -1 },
    { NULL, "V", 0x11, 18, 1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 19, 1, -1, -1, -1, -1 },
    { NULL, "[LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 20, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 21, 2, 17, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 22, 2, 17, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", 0x11, 23, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withOrgBouncycastlePqcMathLinearalgebraGF2nElement:);
  methods[1].selector = @selector(initWithInt:);
  methods[2].selector = @selector(initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[3].selector = @selector(initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial:withOrgBouncycastlePqcMathLinearalgebraGF2nField:);
  methods[4].selector = @selector(assignZeroToElements);
  methods[5].selector = @selector(size);
  methods[6].selector = @selector(getDegree);
  methods[7].selector = @selector(enlargeWithInt:);
  methods[8].selector = @selector(shrink);
  methods[9].selector = @selector(setWithInt:withOrgBouncycastlePqcMathLinearalgebraGF2nElement:);
  methods[10].selector = @selector(atWithInt:);
  methods[11].selector = @selector(isZero);
  methods[12].selector = @selector(isEqual:);
  methods[13].selector = @selector(hash);
  methods[14].selector = @selector(addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[15].selector = @selector(scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement:);
  methods[16].selector = @selector(multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[17].selector = @selector(multiplyAndReduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:withOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[18].selector = @selector(reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[19].selector = @selector(shiftThisLeftWithInt:);
  methods[20].selector = @selector(shiftLeftWithInt:);
  methods[21].selector = @selector(divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[22].selector = @selector(remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[23].selector = @selector(quotientWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  methods[24].selector = @selector(gcdWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "coeff_", "[LOrgBouncycastlePqcMathLinearalgebraGF2nElement;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "size_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "ILOrgBouncycastlePqcMathLinearalgebraGF2nElement;", "I", "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", "LOrgBouncycastlePqcMathLinearalgebraGF2Polynomial;LOrgBouncycastlePqcMathLinearalgebraGF2nField;", "enlarge", "set", "at", "equals", "LNSObject;", "hashCode", "add", "scalarMultiply", "LOrgBouncycastlePqcMathLinearalgebraGF2nElement;", "multiply", "multiplyAndReduce", "LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;LOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;", "reduce", "LJavaLangRuntimeException;LJavaLangArithmeticException;", "shiftThisLeft", "shiftLeft", "divide", "remainder", "quotient", "gcd" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial = { "GF2nPolynomial", "org.bouncycastle.pqc.math.linearalgebra", ptrTable, methods, fields, 7, 0x1, 25, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial;
}

@end

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint deg, OrgBouncycastlePqcMathLinearalgebraGF2nElement *elem) {
  NSObject_init(self);
  self->size_ = deg;
  JreStrongAssignAndConsume(&self->coeff_, [IOSObjectArray newArrayWithLength:self->size_ type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()]);
  for (jint i = 0; i < self->size_; i++) {
    IOSObjectArray_Set(nil_chk(self->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(elem)) java_clone], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
  }
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_(jint deg, OrgBouncycastlePqcMathLinearalgebraGF2nElement *elem) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_, deg, elem)
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_(jint deg, OrgBouncycastlePqcMathLinearalgebraGF2nElement *elem) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithInt_withOrgBouncycastlePqcMathLinearalgebraGF2nElement_, deg, elem)
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint deg) {
  NSObject_init(self);
  self->size_ = deg;
  JreStrongAssignAndConsume(&self->coeff_, [IOSObjectArray newArrayWithLength:self->size_ type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()]);
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(jint deg) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithInt_, deg)
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(jint deg) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithInt_, deg)
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *a) {
  NSObject_init(self);
  jint i;
  JreStrongAssignAndConsume(&self->coeff_, [IOSObjectArray newArrayWithLength:((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *) nil_chk(a))->size_ type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()]);
  self->size_ = a->size_;
  for (i = 0; i < self->size_; i++) {
    IOSObjectArray_Set(nil_chk(self->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(a->coeff_, i))) java_clone], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
  }
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *a) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_, a)
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *a) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_, a)
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *polynomial, OrgBouncycastlePqcMathLinearalgebraGF2nField *B1) {
  NSObject_init(self);
  self->size_ = [((OrgBouncycastlePqcMathLinearalgebraGF2nField *) nil_chk(B1)) getDegree] + 1;
  JreStrongAssignAndConsume(&self->coeff_, [IOSObjectArray newArrayWithLength:self->size_ type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()]);
  jint i;
  if ([B1 isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nONBField class]]) {
    for (i = 0; i < self->size_; i++) {
      if ([((OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *) nil_chk(polynomial)) testBitWithInt:i]) {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nONBElement_ONEWithOrgBouncycastlePqcMathLinearalgebraGF2nONBField_((OrgBouncycastlePqcMathLinearalgebraGF2nONBField *) B1));
      }
      else {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nONBElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nONBField_((OrgBouncycastlePqcMathLinearalgebraGF2nONBField *) B1));
      }
    }
  }
  else if ([B1 isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField class]]) {
    for (i = 0; i < self->size_; i++) {
      if ([((OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *) nil_chk(polynomial)) testBitWithInt:i]) {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement_ONEWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField_((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField *) B1));
      }
      else {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField_((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField *) B1));
      }
    }
  }
  else {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"PolynomialGF2n(Bitstring, GF2nField): B1 must be an instance of GF2nONBField or GF2nPolynomialField!");
  }
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_(OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *polynomial, OrgBouncycastlePqcMathLinearalgebraGF2nField *B1) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_, polynomial, B1)
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_(OrgBouncycastlePqcMathLinearalgebraGF2Polynomial *polynomial, OrgBouncycastlePqcMathLinearalgebraGF2nField *B1) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial, initWithOrgBouncycastlePqcMathLinearalgebraGF2Polynomial_withOrgBouncycastlePqcMathLinearalgebraGF2nField_, polynomial, B1)
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self) {
  jint i;
  for (i = 0; i < self->size_; i++) {
    [((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(self->coeff_), i))) assignZero];
  }
}

jint OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self) {
  return self->size_;
}

jint OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self) {
  jint i;
  for (i = self->size_ - 1; i >= 0; i--) {
    if (![((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(self->coeff_), i))) isZero]) {
      return i;
    }
  }
  return -1;
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_enlargeWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint k) {
  if (k <= self->size_) {
    return;
  }
  jint i;
  IOSObjectArray *res = [IOSObjectArray arrayWithLength:k type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->coeff_, 0, res, 0, self->size_);
  OrgBouncycastlePqcMathLinearalgebraGF2nField *f = JreRetainedLocalValue([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(self->coeff_), 0))) getField]);
  if ([IOSObjectArray_Get(nil_chk(self->coeff_), 0) isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement class]]) {
    for (i = self->size_; i < k; i++) {
      IOSObjectArray_Set(res, i, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField_((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField *) cast_chk(f, [OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField class])));
    }
  }
  else if ([IOSObjectArray_Get(self->coeff_, 0) isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nONBElement class]]) {
    for (i = self->size_; i < k; i++) {
      IOSObjectArray_Set(res, i, OrgBouncycastlePqcMathLinearalgebraGF2nONBElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nONBField_((OrgBouncycastlePqcMathLinearalgebraGF2nONBField *) cast_chk(f, [OrgBouncycastlePqcMathLinearalgebraGF2nONBField class])));
    }
  }
  self->size_ = k;
  JreStrongAssign(&self->coeff_, res);
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self) {
  jint i = self->size_ - 1;
  while ([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(self->coeff_), i))) isZero] && (i > 0)) {
    i--;
  }
  i++;
  if (i < self->size_) {
    IOSObjectArray *res = [IOSObjectArray arrayWithLength:i type:OrgBouncycastlePqcMathLinearalgebraGF2nElement_class_()];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->coeff_, 0, res, 0, i);
    JreStrongAssign(&self->coeff_, res);
    self->size_ = i;
  }
}

jboolean OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_isZero(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self) {
  jint i;
  for (i = 0; i < self->size_; i++) {
    if (IOSObjectArray_Get(nil_chk(self->coeff_), i) != nil) {
      if (![((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) isZero]) {
        return false;
      }
    }
  }
  return true;
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b) {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *result;
  if (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self) >= OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(nil_chk(b))) {
    result = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self));
    jint i;
    for (i = 0; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(b); i++) {
      IOSObjectArray_Set(nil_chk(result->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) addWithOrgBouncycastlePqcMathLinearalgebraGFElement:IOSObjectArray_Get(b->coeff_, i)], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
    }
    for (; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self); i++) {
      IOSObjectArray_Set(nil_chk(result->coeff_), i, IOSObjectArray_Get(self->coeff_, i));
    }
  }
  else {
    result = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(b));
    jint i;
    for (i = 0; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self); i++) {
      IOSObjectArray_Set(nil_chk(result->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) addWithOrgBouncycastlePqcMathLinearalgebraGFElement:IOSObjectArray_Get(b->coeff_, i)], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
    }
    for (; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(b); i++) {
      IOSObjectArray_Set(nil_chk(result->coeff_), i, IOSObjectArray_Get(b->coeff_, i));
    }
  }
  return result;
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nElement *s) {
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *result = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self));
  jint i;
  for (i = 0; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self); i++) {
    IOSObjectArray_Set(nil_chk(result->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) multiplyWithOrgBouncycastlePqcMathLinearalgebraGFElement:s], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
  }
  return result;
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_multiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b) {
  jint i;
  jint j;
  jint aDegree = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self);
  jint bDegree = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(nil_chk(b));
  if (aDegree != bDegree) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"PolynomialGF2n.multiply: this and b must have the same size!");
  }
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *result = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithInt_((JreLShift32(aDegree, 1)) - 1);
  for (i = 0; i < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(self); i++) {
    for (j = 0; j < OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_size(b); j++) {
      if (IOSObjectArray_Get(nil_chk(result->coeff_), i + j) == nil) {
        IOSObjectArray_Set(result->coeff_, i + j, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) multiplyWithOrgBouncycastlePqcMathLinearalgebraGFElement:IOSObjectArray_Get(b->coeff_, j)], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
      }
      else {
        IOSObjectArray_Set(result->coeff_, i + j, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(result->coeff_, i + j))) addWithOrgBouncycastlePqcMathLinearalgebraGFElement:[((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(self->coeff_, i))) multiplyWithOrgBouncycastlePqcMathLinearalgebraGFElement:IOSObjectArray_Get(b->coeff_, j)]], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
      }
    }
  }
  return result;
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_reduceWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *g) {
  return OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, g);
}

void OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shiftThisLeftWithInt_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, jint amount) {
  if (amount > 0) {
    jint i;
    jint oldSize = self->size_;
    OrgBouncycastlePqcMathLinearalgebraGF2nField *f = JreRetainedLocalValue([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(self->coeff_), 0))) getField]);
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_enlargeWithInt_(self, self->size_ + amount);
    for (i = oldSize - 1; i >= 0; i--) {
      IOSObjectArray_Set(nil_chk(self->coeff_), i + amount, IOSObjectArray_Get(self->coeff_, i));
    }
    if ([IOSObjectArray_Get(nil_chk(self->coeff_), 0) isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement class]]) {
      for (i = amount - 1; i >= 0; i--) {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField_((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField *) cast_chk(f, [OrgBouncycastlePqcMathLinearalgebraGF2nPolynomialField class])));
      }
    }
    else if ([IOSObjectArray_Get(self->coeff_, 0) isKindOfClass:[OrgBouncycastlePqcMathLinearalgebraGF2nONBElement class]]) {
      for (i = amount - 1; i >= 0; i--) {
        IOSObjectArray_Set(nil_chk(self->coeff_), i, OrgBouncycastlePqcMathLinearalgebraGF2nONBElement_ZEROWithOrgBouncycastlePqcMathLinearalgebraGF2nONBField_((OrgBouncycastlePqcMathLinearalgebraGF2nONBField *) cast_chk(f, [OrgBouncycastlePqcMathLinearalgebraGF2nONBField class])));
      }
    }
  }
}

IOSObjectArray *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b) {
  IOSObjectArray *result = [IOSObjectArray arrayWithLength:2 type:OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_class_()];
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *a = create_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(a);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *shift;
  OrgBouncycastlePqcMathLinearalgebraGF2nElement *factor;
  jint bDegree = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(nil_chk(b));
  OrgBouncycastlePqcMathLinearalgebraGF2nElement *inv = (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(b->coeff_), bDegree))) invert], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]);
  if (OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(a) < bDegree) {
    IOSObjectArray_SetAndConsume(result, 0, new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self));
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(nil_chk(IOSObjectArray_Get(result, 0)));
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(nil_chk(IOSObjectArray_Get(result, 0)));
    IOSObjectArray_SetAndConsume(result, 1, new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self));
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(nil_chk(IOSObjectArray_Get(result, 1)));
    return result;
  }
  IOSObjectArray_SetAndConsume(result, 0, new_OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_initWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self));
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_assignZeroToElements(nil_chk(IOSObjectArray_Get(result, 0)));
  jint i = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(a) - bDegree;
  while (i >= 0) {
    factor = (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(IOSObjectArray_Get(nil_chk(a->coeff_), OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(a)))) multiplyWithOrgBouncycastlePqcMathLinearalgebraGFElement:inv], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]);
    shift = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_scalarMultiplyWithOrgBouncycastlePqcMathLinearalgebraGF2nElement_(b, factor);
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shiftThisLeftWithInt_(nil_chk(shift), i);
    a = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_addWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(a, shift);
    OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(nil_chk(a));
    IOSObjectArray_Set(nil_chk(((OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *) nil_chk(IOSObjectArray_Get(result, 0)))->coeff_), i, (OrgBouncycastlePqcMathLinearalgebraGF2nElement *) cast_chk([((OrgBouncycastlePqcMathLinearalgebraGF2nElement *) nil_chk(factor)) java_clone], [OrgBouncycastlePqcMathLinearalgebraGF2nElement class]));
    i = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_getDegree(a) - bDegree;
  }
  IOSObjectArray_Set(result, 1, a);
  OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_shrink(nil_chk(IOSObjectArray_Get(result, 0)));
  return result;
}

OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_remainderWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *self, OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial *b) {
  IOSObjectArray *result = [IOSObjectArray arrayWithLength:2 type:OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_class_()];
  result = OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_divideWithOrgBouncycastlePqcMathLinearalgebraGF2nPolynomial_(self, b);
  return IOSObjectArray_Get(nil_chk(result), 1);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcMathLinearalgebraGF2nPolynomial)
