//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/math/linearalgebra/PolynomialRingGF2.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "java/io/PrintStream.h"
#include "java/lang/Boolean.h"
#include "java/lang/Byte.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/System.h"
#include "org/bouncycastle/pqc/math/linearalgebra/PolynomialRingGF2.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/math/linearalgebra/PolynomialRingGF2 must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 ()

- (instancetype)init;

@end

__attribute__((unused)) static void OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *self);

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *new_OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *create_OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init(void);

@implementation OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jint)addWithInt:(jint)p
           withInt:(jint)q {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_addWithInt_withInt_(p, q);
}

+ (jlong)multiplyWithInt:(jint)p
                 withInt:(jint)q {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_multiplyWithInt_withInt_(p, q);
}

+ (jint)modMultiplyWithInt:(jint)a
                   withInt:(jint)b
                   withInt:(jint)r {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_modMultiplyWithInt_withInt_withInt_(a, b, r);
}

+ (jint)degreeWithInt:(jint)p {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(p);
}

+ (jint)degreeWithLong:(jlong)p {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithLong_(p);
}

+ (jint)remainderWithInt:(jint)p
                 withInt:(jint)q {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_remainderWithInt_withInt_(p, q);
}

+ (jint)restWithLong:(jlong)p
             withInt:(jint)q {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_restWithLong_withInt_(p, q);
}

+ (jint)gcdWithInt:(jint)p
           withInt:(jint)q {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_gcdWithInt_withInt_(p, q);
}

+ (jboolean)isIrreducibleWithInt:(jint)p {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_isIrreducibleWithInt_(p);
}

+ (jint)getIrreduciblePolynomialWithInt:(jint)deg {
  return OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_getIrreduciblePolynomialWithInt_(deg);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "J", 0x9, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 3, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 5, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 5, 7, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 8, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 9, 10, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 11, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 12, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 13, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(addWithInt:withInt:);
  methods[2].selector = @selector(multiplyWithInt:withInt:);
  methods[3].selector = @selector(modMultiplyWithInt:withInt:withInt:);
  methods[4].selector = @selector(degreeWithInt:);
  methods[5].selector = @selector(degreeWithLong:);
  methods[6].selector = @selector(remainderWithInt:withInt:);
  methods[7].selector = @selector(restWithLong:withInt:);
  methods[8].selector = @selector(gcdWithInt:withInt:);
  methods[9].selector = @selector(isIrreducibleWithInt:);
  methods[10].selector = @selector(getIrreduciblePolynomialWithInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "add", "II", "multiply", "modMultiply", "III", "degree", "I", "J", "remainder", "rest", "JI", "gcd", "isIrreducible", "getIrreduciblePolynomial" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 = { "PolynomialRingGF2", "org.bouncycastle.pqc.math.linearalgebra", ptrTable, methods, NULL, 7, 0x11, 11, 0, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2;
}

@end

void OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *self) {
  NSObject_init(self);
}

OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *new_OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2, init)
}

OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2 *create_OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2, init)
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_addWithInt_withInt_(jint p, jint q) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  return p ^ q;
}

jlong OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_multiplyWithInt_withInt_(jint p, jint q) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jlong result = 0;
  if (q != 0) {
    jlong q1 = q & (jlong) 0x00000000ffffffffLL;
    while (p != 0) {
      jbyte b = (jbyte) (p & (jint) 0x01);
      if (b == 1) {
        result ^= q1;
      }
      JreURShiftAssignInt(&p, 1);
      JreLShiftAssignLong(&q1, 1);
    }
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_modMultiplyWithInt_withInt_withInt_(jint a, jint b, jint r) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jint result = 0;
  jint p = OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_remainderWithInt_withInt_(a, r);
  jint q = OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_remainderWithInt_withInt_(b, r);
  if (q != 0) {
    jint d = JreLShift32(1, OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(r));
    while (p != 0) {
      jbyte pMod2 = (jbyte) (p & (jint) 0x01);
      if (pMod2 == 1) {
        result ^= q;
      }
      JreURShiftAssignInt(&p, 1);
      JreLShiftAssignInt(&q, 1);
      if (q >= d) {
        q ^= r;
      }
    }
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(jint p) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jint result = -1;
  while (p != 0) {
    result++;
    JreURShiftAssignInt(&p, 1);
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithLong_(jlong p) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jint result = 0;
  while (p != 0) {
    result++;
    JreURShiftAssignLong(&p, 1);
  }
  return result - 1;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_remainderWithInt_withInt_(jint p, jint q) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jint result = p;
  if (q == 0) {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithNSString:@"Error: to be divided by 0"];
    return 0;
  }
  while (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(result) >= OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(q)) {
    result ^= JreLShift32(q, (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(result) - OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(q)));
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_restWithLong_withInt_(jlong p, jint q) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jlong p1 = p;
  if (q == 0) {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithNSString:@"Error: to be divided by 0"];
    return 0;
  }
  jlong q1 = q & (jlong) 0x00000000ffffffffLL;
  while ((JreURShift64(p1, 32)) != 0) {
    p1 ^= JreLShift64(q1, (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithLong_(p1) - OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithLong_(q1)));
  }
  jint result = (jint) (p1 & (jint) 0xffffffff);
  while (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(result) >= OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(q)) {
    result ^= JreLShift32(q, (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(result) - OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(q)));
  }
  return result;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_gcdWithInt_withInt_(jint p, jint q) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  jint a;
  jint b;
  jint c;
  a = p;
  b = q;
  while (b != 0) {
    c = OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_remainderWithInt_withInt_(a, b);
    a = b;
    b = c;
  }
  return a;
}

jboolean OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_isIrreducibleWithInt_(jint p) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  if (p == 0) {
    return false;
  }
  jint d = JreURShift32(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_degreeWithInt_(p), 1);
  jint u = 2;
  for (jint i = 0; i < d; i++) {
    u = OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_modMultiplyWithInt_withInt_withInt_(u, u, p);
    if (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_gcdWithInt_withInt_(u ^ 2, p) != 1) {
      return false;
    }
  }
  return true;
}

jint OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_getIrreduciblePolynomialWithInt_(jint deg) {
  OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_initialize();
  if (deg < 0) {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithNSString:@"The Degree is negative"];
    return 0;
  }
  if (deg > 31) {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, err))) printlnWithNSString:@"The Degree is more then 31"];
    return 0;
  }
  if (deg == 0) {
    return 1;
  }
  jint a = JreLShift32(1, deg);
  a++;
  jint b = JreLShift32(1, (deg + 1));
  for (jint i = a; i < b; i += 2) {
    if (OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2_isIrreducibleWithInt_(i)) {
      return i;
    }
  }
  return 0;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcMathLinearalgebraPolynomialRingGF2)
