//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/asn1/BERTaggedObject.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Integer.h"
#include "java/lang/annotation/Annotation.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1Encoding.h"
#include "org/bouncycastle/asn1/ASN1OutputStream.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/BERSequence.h"
#include "org/bouncycastle/asn1/BERTaggedObject.h"
#include "org/bouncycastle/asn1/BERTags.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/asn1/BERTaggedObject must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


__attribute__((unused)) static IOSObjectArray *OrgBouncycastleAsn1BERTaggedObject__Annotations$0(void);

@implementation OrgBouncycastleAsn1BERTaggedObject

- (instancetype)initWithInt:(jint)tagNo {
  OrgBouncycastleAsn1BERTaggedObject_initWithInt_(self, tagNo);
  return self;
}

- (instancetype)initWithInt:(jint)tagNo
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1BERTaggedObject_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(self, tagNo, obj);
  return self;
}

- (instancetype)initWithInt:(jint)tagClass
                    withInt:(jint)tagNo
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, tagClass, tagNo, obj);
  return self;
}

- (instancetype)initWithBoolean:(jboolean)explicit_
                        withInt:(jint)tagNo
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicit_, tagNo, obj);
  return self;
}

- (instancetype)initWithBoolean:(jboolean)explicit_
                        withInt:(jint)tagClass
                        withInt:(jint)tagNo
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicit_, tagClass, tagNo, obj);
  return self;
}

- (instancetype)initWithInt:(jint)explicitness
                    withInt:(jint)tagClass
                    withInt:(jint)tagNo
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicitness, tagClass, tagNo, obj);
  return self;
}

- (jboolean)encodeConstructed {
  return [self isExplicit] || [((OrgBouncycastleAsn1ASN1Primitive *) nil_chk([((id<OrgBouncycastleAsn1ASN1Encodable>) nil_chk(obj_)) toASN1Primitive])) encodeConstructed];
}

- (jint)encodedLengthWithBoolean:(jboolean)withTag {
  OrgBouncycastleAsn1ASN1Primitive *primitive = JreRetainedLocalValue([((id<OrgBouncycastleAsn1ASN1Encodable>) nil_chk(obj_)) toASN1Primitive]);
  jboolean explicit_ = [self isExplicit];
  jint length = [((OrgBouncycastleAsn1ASN1Primitive *) nil_chk(primitive)) encodedLengthWithBoolean:explicit_];
  if (explicit_) {
    length += 3;
  }
  length += withTag ? OrgBouncycastleAsn1ASN1OutputStream_getLengthOfIdentifierWithInt_(tagNo_) : 0;
  return length;
}

- (void)encodeWithOrgBouncycastleAsn1ASN1OutputStream:(OrgBouncycastleAsn1ASN1OutputStream *)outArg
                                          withBoolean:(jboolean)withTag {
  OrgBouncycastleAsn1ASN1Primitive *primitive = JreRetainedLocalValue([((id<OrgBouncycastleAsn1ASN1Encodable>) nil_chk(obj_)) toASN1Primitive]);
  jboolean explicit_ = [self isExplicit];
  if (withTag) {
    jint flags = tagClass_;
    if (explicit_ || [((OrgBouncycastleAsn1ASN1Primitive *) nil_chk(primitive)) encodeConstructed]) {
      flags |= OrgBouncycastleAsn1BERTags_CONSTRUCTED;
    }
    [((OrgBouncycastleAsn1ASN1OutputStream *) nil_chk(outArg)) writeIdentifierWithBoolean:true withInt:flags withInt:tagNo_];
  }
  if (explicit_) {
    [((OrgBouncycastleAsn1ASN1OutputStream *) nil_chk(outArg)) writeWithInt:(jint) 0x80];
    [((OrgBouncycastleAsn1ASN1Primitive *) nil_chk(primitive)) encodeWithOrgBouncycastleAsn1ASN1OutputStream:outArg withBoolean:true];
    [outArg writeWithInt:(jint) 0x00];
    [outArg writeWithInt:(jint) 0x00];
  }
  else {
    [((OrgBouncycastleAsn1ASN1Primitive *) nil_chk(primitive)) encodeWithOrgBouncycastleAsn1ASN1OutputStream:outArg withBoolean:false];
  }
}

- (NSString *)getASN1Encoding {
  return OrgBouncycastleAsn1ASN1Encoding_BER;
}

- (OrgBouncycastleAsn1ASN1Sequence *)rebuildConstructedWithOrgBouncycastleAsn1ASN1Primitive:(OrgBouncycastleAsn1ASN1Primitive *)primitive {
  return create_OrgBouncycastleAsn1BERSequence_initWithOrgBouncycastleAsn1ASN1Encodable_(primitive);
}

- (OrgBouncycastleAsn1ASN1TaggedObject *)replaceTagWithInt:(jint)tagClass
                                                   withInt:(jint)tagNo {
  return create_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(explicitness_, tagClass, tagNo, obj_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, 1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 5, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 6, -1, -1, -1, -1 },
    { NULL, "Z", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x0, 7, 8, 9, -1, -1, -1 },
    { NULL, "V", 0x0, 10, 11, 9, -1, -1, -1 },
    { NULL, "LNSString;", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1ASN1Sequence;", 0x0, 12, 13, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1ASN1TaggedObject;", 0x0, 14, 15, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:);
  methods[1].selector = @selector(initWithInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[2].selector = @selector(initWithInt:withInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[3].selector = @selector(initWithBoolean:withInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[4].selector = @selector(initWithBoolean:withInt:withInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[5].selector = @selector(initWithInt:withInt:withInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[6].selector = @selector(encodeConstructed);
  methods[7].selector = @selector(encodedLengthWithBoolean:);
  methods[8].selector = @selector(encodeWithOrgBouncycastleAsn1ASN1OutputStream:withBoolean:);
  methods[9].selector = @selector(getASN1Encoding);
  methods[10].selector = @selector(rebuildConstructedWithOrgBouncycastleAsn1ASN1Primitive:);
  methods[11].selector = @selector(replaceTagWithInt:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "I", (void *)&OrgBouncycastleAsn1BERTaggedObject__Annotations$0, "ILOrgBouncycastleAsn1ASN1Encodable;", "IILOrgBouncycastleAsn1ASN1Encodable;", "ZILOrgBouncycastleAsn1ASN1Encodable;", "ZIILOrgBouncycastleAsn1ASN1Encodable;", "IIILOrgBouncycastleAsn1ASN1Encodable;", "encodedLength", "Z", "LJavaIoIOException;", "encode", "LOrgBouncycastleAsn1ASN1OutputStream;Z", "rebuildConstructed", "LOrgBouncycastleAsn1ASN1Primitive;", "replaceTag", "II" };
  static const J2ObjcClassInfo _OrgBouncycastleAsn1BERTaggedObject = { "BERTaggedObject", "org.bouncycastle.asn1", ptrTable, methods, NULL, 7, 0x1, 12, 0, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleAsn1BERTaggedObject;
}

@end

void OrgBouncycastleAsn1BERTaggedObject_initWithInt_(OrgBouncycastleAsn1BERTaggedObject *self, jint tagNo) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, false, tagNo, create_OrgBouncycastleAsn1BERSequence_init());
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithInt_(jint tagNo) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_, tagNo)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithInt_(jint tagNo) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_, tagNo)
}

void OrgBouncycastleAsn1BERTaggedObject_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1BERTaggedObject *self, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, true, tagNo, obj);
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withOrgBouncycastleAsn1ASN1Encodable_, tagNo, obj)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withOrgBouncycastleAsn1ASN1Encodable_, tagNo, obj)
}

void OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1BERTaggedObject *self, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, true, tagClass, tagNo, obj);
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, tagClass, tagNo, obj)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, tagClass, tagNo, obj)
}

void OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1BERTaggedObject *self, jboolean explicit_, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicit_, tagNo, obj);
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jboolean explicit_, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicit_, tagNo, obj)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jboolean explicit_, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicit_, tagNo, obj)
}

void OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1BERTaggedObject *self, jboolean explicit_, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicit_, tagClass, tagNo, obj);
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jboolean explicit_, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicit_, tagClass, tagNo, obj)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jboolean explicit_, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithBoolean_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicit_, tagClass, tagNo, obj)
}

void OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1BERTaggedObject *self, jint explicitness, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  OrgBouncycastleAsn1ASN1TaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(self, explicitness, tagClass, tagNo, obj);
}

OrgBouncycastleAsn1BERTaggedObject *new_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jint explicitness, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicitness, tagClass, tagNo, obj)
}

OrgBouncycastleAsn1BERTaggedObject *create_OrgBouncycastleAsn1BERTaggedObject_initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_(jint explicitness, jint tagClass, jint tagNo, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1BERTaggedObject, initWithInt_withInt_withInt_withOrgBouncycastleAsn1ASN1Encodable_, explicitness, tagClass, tagNo, obj)
}

IOSObjectArray *OrgBouncycastleAsn1BERTaggedObject__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated(false, @"") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1BERTaggedObject)
