name: felectronic_certificates_android
description: >-
  Android implementation of the felectronic_certificates plugin
  using the Android KeyStore for certificate management and signing.
version: 1.0.0
repository: https://github.com/nicoacevedor/felectronic_dnie
issue_tracker: https://github.com/nicoacevedor/felectronic_dnie/issues
topics:
  - certificate
  - android
  - keystore

environment:
  sdk: ^3.11.0

flutter:
  plugin:
    implements: felectronic_certificates
    platforms:
      android:
        package: es.gob.electronic_certificates
        pluginClass: ElectronicCertificatesPlugin
        dartPluginClass: FelectronicCertificatesAndroid

dependencies:
  felectronic_certificates_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
