//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/jcajce/provider/mceliece/BCMcEliecePublicKey.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/StringBuilder.h"
#include "org/bouncycastle/asn1/ASN1ObjectIdentifier.h"
#include "org/bouncycastle/asn1/x509/AlgorithmIdentifier.h"
#include "org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.h"
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"
#include "org/bouncycastle/pqc/asn1/McEliecePublicKey.h"
#include "org/bouncycastle/pqc/asn1/PQCObjectIdentifiers.h"
#include "org/bouncycastle/pqc/crypto/mceliece/McEliecePublicKeyParameters.h"
#include "org/bouncycastle/pqc/jcajce/provider/mceliece/BCMcEliecePublicKey.h"
#include "org/bouncycastle/pqc/math/linearalgebra/GF2Matrix.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/jcajce/provider/mceliece/BCMcEliecePublicKey must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey () {
 @public
  OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *params_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey, params_, OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *)

inline jlong OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_get_serialVersionUID(void);
#define OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey, serialVersionUID, jlong)

@implementation OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey

- (instancetype)initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters:(OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *)params {
  OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_(self, params);
  return self;
}

- (NSString *)getAlgorithm {
  return @"McEliece";
}

- (jint)getN {
  return [((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getN];
}

- (jint)getK {
  return [((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getK];
}

- (jint)getT {
  return [((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getT];
}

- (OrgBouncycastlePqcMathLinearalgebraGF2Matrix *)getG {
  return [((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getG];
}

- (NSString *)description {
  JavaLangStringBuilder *result = create_JavaLangStringBuilder_initWithNSString_(@"McEliecePublicKey:\n");
  [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([result appendWithNSString:@" length of the code         : "])) appendWithInt:[((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getN]])) appendWithNSString:@"\n"];
  [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([result appendWithNSString:@" error correction capability: "])) appendWithInt:[params_ getT]])) appendWithNSString:@"\n"];
  [((JavaLangStringBuilder *) nil_chk([result appendWithNSString:@" generator matrix           : "])) appendWithId:[params_ getG]];
  return [result description];
}

- (jboolean)isEqual:(id)other {
  if ([other isKindOfClass:[OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey class]]) {
    OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *otherKey = (OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *) other;
    return [((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getN] == [((OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *) nil_chk(otherKey)) getN] && [params_ getT] == [otherKey getT] && [((OrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk([params_ getG])) isEqual:[otherKey getG]];
  }
  return false;
}

- (NSUInteger)hash {
  return 37 * ([((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getN] + 37 * [params_ getT]) + ((jint) [((OrgBouncycastlePqcMathLinearalgebraGF2Matrix *) nil_chk([params_ getG])) hash]);
}

- (IOSByteArray *)getEncoded {
  OrgBouncycastlePqcAsn1McEliecePublicKey *key = create_OrgBouncycastlePqcAsn1McEliecePublicKey_initWithInt_withInt_withOrgBouncycastlePqcMathLinearalgebraGF2Matrix_([((OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *) nil_chk(params_)) getN], [params_ getT], [params_ getG]);
  OrgBouncycastleAsn1X509AlgorithmIdentifier *algorithmIdentifier = create_OrgBouncycastleAsn1X509AlgorithmIdentifier_initWithOrgBouncycastleAsn1ASN1ObjectIdentifier_(JreLoadStatic(OrgBouncycastlePqcAsn1PQCObjectIdentifiers, mcEliece));
  @try {
    OrgBouncycastleAsn1X509SubjectPublicKeyInfo *subjectPublicKeyInfo = create_OrgBouncycastleAsn1X509SubjectPublicKeyInfo_initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withOrgBouncycastleAsn1ASN1Encodable_(algorithmIdentifier, key);
    return [subjectPublicKeyInfo getEncoded];
  }
  @catch (JavaIoIOException *e) {
    return nil;
  }
}

- (NSString *)getFormat {
  return @"X.509";
}

- (OrgBouncycastleCryptoParamsAsymmetricKeyParameter *)getKeyParams {
  return params_;
}

- (void)dealloc {
  RELEASE_(params_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcMathLinearalgebraGF2Matrix;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 4, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleCryptoParamsAsymmetricKeyParameter;", 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters:);
  methods[1].selector = @selector(getAlgorithm);
  methods[2].selector = @selector(getN);
  methods[3].selector = @selector(getK);
  methods[4].selector = @selector(getT);
  methods[5].selector = @selector(getG);
  methods[6].selector = @selector(description);
  methods[7].selector = @selector(isEqual:);
  methods[8].selector = @selector(hash);
  methods[9].selector = @selector(getEncoded);
  methods[10].selector = @selector(getFormat);
  methods[11].selector = @selector(getKeyParams);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "params_", "LOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters;", "toString", "equals", "LNSObject;", "hashCode" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey = { "BCMcEliecePublicKey", "org.bouncycastle.pqc.jcajce.provider.mceliece", ptrTable, methods, fields, 7, 0x1, 12, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey;
}

@end

void OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *self, OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *params) {
  NSObject_init(self);
  JreStrongAssign(&self->params_, params);
}

OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *new_OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_(OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *params) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey, initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_, params)
}

OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey *create_OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey_initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_(OrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters *params) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey, initWithOrgBouncycastlePqcCryptoMcelieceMcEliecePublicKeyParameters_, params)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcJcajceProviderMcelieceBCMcEliecePublicKey)
