//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/asn1/x509/Attribute.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleAsn1X509Attribute")
#ifdef RESTRICT_OrgBouncycastleAsn1X509Attribute
#define INCLUDE_ALL_OrgBouncycastleAsn1X509Attribute 0
#else
#define INCLUDE_ALL_OrgBouncycastleAsn1X509Attribute 1
#endif
#undef RESTRICT_OrgBouncycastleAsn1X509Attribute

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleAsn1X509Attribute_) && (INCLUDE_ALL_OrgBouncycastleAsn1X509Attribute || defined(INCLUDE_OrgBouncycastleAsn1X509Attribute))
#define OrgBouncycastleAsn1X509Attribute_

#define RESTRICT_OrgBouncycastleAsn1ASN1Object 1
#define INCLUDE_OrgBouncycastleAsn1ASN1Object 1
#include "org/bouncycastle/asn1/ASN1Object.h"

@class IOSObjectArray;
@class OrgBouncycastleAsn1ASN1ObjectIdentifier;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Set;

@interface OrgBouncycastleAsn1X509Attribute : OrgBouncycastleAsn1ASN1Object

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)attrType
                                          withOrgBouncycastleAsn1ASN1Set:(OrgBouncycastleAsn1ASN1Set *)attrValues;

- (IOSObjectArray *)getAttributeValues;

- (OrgBouncycastleAsn1ASN1ObjectIdentifier *)getAttrType;

- (OrgBouncycastleAsn1ASN1Set *)getAttrValues;

+ (OrgBouncycastleAsn1X509Attribute *)getInstanceWithId:(id)o;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1X509Attribute)

FOUNDATION_EXPORT OrgBouncycastleAsn1X509Attribute *OrgBouncycastleAsn1X509Attribute_getInstanceWithId_(id o);

FOUNDATION_EXPORT void OrgBouncycastleAsn1X509Attribute_initWithOrgBouncycastleAsn1ASN1ObjectIdentifier_withOrgBouncycastleAsn1ASN1Set_(OrgBouncycastleAsn1X509Attribute *self, OrgBouncycastleAsn1ASN1ObjectIdentifier *attrType, OrgBouncycastleAsn1ASN1Set *attrValues);

FOUNDATION_EXPORT OrgBouncycastleAsn1X509Attribute *new_OrgBouncycastleAsn1X509Attribute_initWithOrgBouncycastleAsn1ASN1ObjectIdentifier_withOrgBouncycastleAsn1ASN1Set_(OrgBouncycastleAsn1ASN1ObjectIdentifier *attrType, OrgBouncycastleAsn1ASN1Set *attrValues) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleAsn1X509Attribute *create_OrgBouncycastleAsn1X509Attribute_initWithOrgBouncycastleAsn1ASN1ObjectIdentifier_withOrgBouncycastleAsn1ASN1Set_(OrgBouncycastleAsn1ASN1ObjectIdentifier *attrType, OrgBouncycastleAsn1ASN1Set *attrValues);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1X509Attribute)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleAsn1X509Attribute")
