//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/asn1/x509/DigestInfo.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/util/Enumeration.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1Object.h"
#include "org/bouncycastle/asn1/ASN1OctetString.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/DEROctetString.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/x509/AlgorithmIdentifier.h"
#include "org/bouncycastle/asn1/x509/DigestInfo.h"
#include "org/bouncycastle/util/Arrays.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/asn1/x509/DigestInfo must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastleAsn1X509DigestInfo () {
 @public
  IOSByteArray *digest_;
  OrgBouncycastleAsn1X509AlgorithmIdentifier *algId_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509DigestInfo, digest_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509DigestInfo, algId_, OrgBouncycastleAsn1X509AlgorithmIdentifier *)

@implementation OrgBouncycastleAsn1X509DigestInfo

+ (OrgBouncycastleAsn1X509DigestInfo *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                              withBoolean:(jboolean)explicit_ {
  return OrgBouncycastleAsn1X509DigestInfo_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, explicit_);
}

+ (OrgBouncycastleAsn1X509DigestInfo *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1X509DigestInfo_getInstanceWithId_(obj);
}

- (instancetype)initWithOrgBouncycastleAsn1X509AlgorithmIdentifier:(OrgBouncycastleAsn1X509AlgorithmIdentifier *)algId
                                                     withByteArray:(IOSByteArray *)digest {
  OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_(self, algId, digest);
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)obj {
  OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1ASN1Sequence_(self, obj);
  return self;
}

- (OrgBouncycastleAsn1X509AlgorithmIdentifier *)getAlgorithmId {
  return algId_;
}

- (IOSByteArray *)getDigest {
  return OrgBouncycastleUtilArrays_cloneWithByteArray_(digest_);
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  OrgBouncycastleAsn1ASN1EncodableVector *v = create_OrgBouncycastleAsn1ASN1EncodableVector_initWithInt_(2);
  [v addWithOrgBouncycastleAsn1ASN1Encodable:algId_];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:create_OrgBouncycastleAsn1DEROctetString_initWithByteArray_(digest_)];
  return create_OrgBouncycastleAsn1DERSequence_initWithOrgBouncycastleAsn1ASN1EncodableVector_(v);
}

- (void)dealloc {
  RELEASE_(digest_);
  RELEASE_(algId_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgBouncycastleAsn1X509DigestInfo;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1X509DigestInfo;", 0x9, 0, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1X509AlgorithmIdentifier;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:withBoolean:);
  methods[1].selector = @selector(getInstanceWithId:);
  methods[2].selector = @selector(initWithOrgBouncycastleAsn1X509AlgorithmIdentifier:withByteArray:);
  methods[3].selector = @selector(initWithOrgBouncycastleAsn1ASN1Sequence:);
  methods[4].selector = @selector(getAlgorithmId);
  methods[5].selector = @selector(getDigest);
  methods[6].selector = @selector(toASN1Primitive);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "digest_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "algId_", "LOrgBouncycastleAsn1X509AlgorithmIdentifier;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "getInstance", "LOrgBouncycastleAsn1ASN1TaggedObject;Z", "LNSObject;", "LOrgBouncycastleAsn1X509AlgorithmIdentifier;[B", "LOrgBouncycastleAsn1ASN1Sequence;" };
  static const J2ObjcClassInfo _OrgBouncycastleAsn1X509DigestInfo = { "DigestInfo", "org.bouncycastle.asn1.x509", ptrTable, methods, fields, 7, 0x1, 7, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleAsn1X509DigestInfo;
}

@end

OrgBouncycastleAsn1X509DigestInfo *OrgBouncycastleAsn1X509DigestInfo_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_) {
  OrgBouncycastleAsn1X509DigestInfo_initialize();
  return OrgBouncycastleAsn1X509DigestInfo_getInstanceWithId_(OrgBouncycastleAsn1ASN1Sequence_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, explicit_));
}

OrgBouncycastleAsn1X509DigestInfo *OrgBouncycastleAsn1X509DigestInfo_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1X509DigestInfo_initialize();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1X509DigestInfo class]]) {
    return (OrgBouncycastleAsn1X509DigestInfo *) obj;
  }
  else if (obj != nil) {
    return create_OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1ASN1Sequence_(OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(obj));
  }
  return nil;
}

void OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_(OrgBouncycastleAsn1X509DigestInfo *self, OrgBouncycastleAsn1X509AlgorithmIdentifier *algId, IOSByteArray *digest) {
  OrgBouncycastleAsn1ASN1Object_init(self);
  JreStrongAssign(&self->digest_, OrgBouncycastleUtilArrays_cloneWithByteArray_(digest));
  JreStrongAssign(&self->algId_, algId);
}

OrgBouncycastleAsn1X509DigestInfo *new_OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_(OrgBouncycastleAsn1X509AlgorithmIdentifier *algId, IOSByteArray *digest) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1X509DigestInfo, initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_, algId, digest)
}

OrgBouncycastleAsn1X509DigestInfo *create_OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_(OrgBouncycastleAsn1X509AlgorithmIdentifier *algId, IOSByteArray *digest) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1X509DigestInfo, initWithOrgBouncycastleAsn1X509AlgorithmIdentifier_withByteArray_, algId, digest)
}

void OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1ASN1Sequence_(OrgBouncycastleAsn1X509DigestInfo *self, OrgBouncycastleAsn1ASN1Sequence *obj) {
  OrgBouncycastleAsn1ASN1Object_init(self);
  id<JavaUtilEnumeration> e = JreRetainedLocalValue([((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(obj)) getObjects]);
  JreStrongAssign(&self->algId_, OrgBouncycastleAsn1X509AlgorithmIdentifier_getInstanceWithId_([((id<JavaUtilEnumeration>) nil_chk(e)) nextElement]));
  JreStrongAssign(&self->digest_, [((OrgBouncycastleAsn1ASN1OctetString *) nil_chk(OrgBouncycastleAsn1ASN1OctetString_getInstanceWithId_([e nextElement]))) getOctets]);
}

OrgBouncycastleAsn1X509DigestInfo *new_OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1ASN1Sequence_(OrgBouncycastleAsn1ASN1Sequence *obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1X509DigestInfo, initWithOrgBouncycastleAsn1ASN1Sequence_, obj)
}

OrgBouncycastleAsn1X509DigestInfo *create_OrgBouncycastleAsn1X509DigestInfo_initWithOrgBouncycastleAsn1ASN1Sequence_(OrgBouncycastleAsn1ASN1Sequence *obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1X509DigestInfo, initWithOrgBouncycastleAsn1ASN1Sequence_, obj)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509DigestInfo)
