//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/asn1/x509/DistributionPointName.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/StringBuffer.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1Object.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Set.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/x509/DistributionPointName.h"
#include "org/bouncycastle/asn1/x509/GeneralNames.h"
#include "org/bouncycastle/util/Strings.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/asn1/x509/DistributionPointName must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastleAsn1X509DistributionPointName ()

- (void)appendObjectWithJavaLangStringBuffer:(JavaLangStringBuffer *)buf
                                withNSString:(NSString *)sep
                                withNSString:(NSString *)name
                                withNSString:(NSString *)value;

@end

__attribute__((unused)) static void OrgBouncycastleAsn1X509DistributionPointName_appendObjectWithJavaLangStringBuffer_withNSString_withNSString_withNSString_(OrgBouncycastleAsn1X509DistributionPointName *self, JavaLangStringBuffer *buf, NSString *sep, NSString *name, NSString *value);

@implementation OrgBouncycastleAsn1X509DistributionPointName

+ (jint)FULL_NAME {
  return OrgBouncycastleAsn1X509DistributionPointName_FULL_NAME;
}

+ (jint)NAME_RELATIVE_TO_CRL_ISSUER {
  return OrgBouncycastleAsn1X509DistributionPointName_NAME_RELATIVE_TO_CRL_ISSUER;
}

+ (OrgBouncycastleAsn1X509DistributionPointName *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                                         withBoolean:(jboolean)explicit_ {
  return OrgBouncycastleAsn1X509DistributionPointName_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, explicit_);
}

+ (OrgBouncycastleAsn1X509DistributionPointName *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1X509DistributionPointName_getInstanceWithId_(obj);
}

- (instancetype)initWithInt:(jint)type
withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)name {
  OrgBouncycastleAsn1X509DistributionPointName_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(self, type, name);
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1X509GeneralNames:(OrgBouncycastleAsn1X509GeneralNames *)name {
  OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1X509GeneralNames_(self, name);
  return self;
}

- (jint)getType {
  return type_;
}

- (id<OrgBouncycastleAsn1ASN1Encodable>)getName {
  return name_;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj {
  OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1ASN1TaggedObject_(self, obj);
  return self;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return create_OrgBouncycastleAsn1DERTaggedObject_initWithBoolean_withInt_withOrgBouncycastleAsn1ASN1Encodable_(false, type_, name_);
}

- (NSString *)description {
  NSString *sep = OrgBouncycastleUtilStrings_lineSeparator();
  JavaLangStringBuffer *buf = create_JavaLangStringBuffer_init();
  [buf appendWithNSString:@"DistributionPointName: ["];
  [buf appendWithNSString:sep];
  if (type_ == OrgBouncycastleAsn1X509DistributionPointName_FULL_NAME) {
    OrgBouncycastleAsn1X509DistributionPointName_appendObjectWithJavaLangStringBuffer_withNSString_withNSString_withNSString_(self, buf, sep, @"fullName", [((id<OrgBouncycastleAsn1ASN1Encodable>) nil_chk(name_)) description]);
  }
  else {
    OrgBouncycastleAsn1X509DistributionPointName_appendObjectWithJavaLangStringBuffer_withNSString_withNSString_withNSString_(self, buf, sep, @"nameRelativeToCRLIssuer", [((id<OrgBouncycastleAsn1ASN1Encodable>) nil_chk(name_)) description]);
  }
  [buf appendWithNSString:@"]"];
  [buf appendWithNSString:sep];
  return [buf description];
}

- (void)appendObjectWithJavaLangStringBuffer:(JavaLangStringBuffer *)buf
                                withNSString:(NSString *)sep
                                withNSString:(NSString *)name
                                withNSString:(NSString *)value {
  OrgBouncycastleAsn1X509DistributionPointName_appendObjectWithJavaLangStringBuffer_withNSString_withNSString_withNSString_(self, buf, sep, name, value);
}

- (void)dealloc {
  RELEASE_(name_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgBouncycastleAsn1X509DistributionPointName;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1X509DistributionPointName;", 0x9, 0, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1ASN1Encodable;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 5, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 6, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 7, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:withBoolean:);
  methods[1].selector = @selector(getInstanceWithId:);
  methods[2].selector = @selector(initWithInt:withOrgBouncycastleAsn1ASN1Encodable:);
  methods[3].selector = @selector(initWithOrgBouncycastleAsn1X509GeneralNames:);
  methods[4].selector = @selector(getType);
  methods[5].selector = @selector(getName);
  methods[6].selector = @selector(initWithOrgBouncycastleAsn1ASN1TaggedObject:);
  methods[7].selector = @selector(toASN1Primitive);
  methods[8].selector = @selector(description);
  methods[9].selector = @selector(appendObjectWithJavaLangStringBuffer:withNSString:withNSString:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "name_", "LOrgBouncycastleAsn1ASN1Encodable;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "type_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "FULL_NAME", "I", .constantValue.asInt = OrgBouncycastleAsn1X509DistributionPointName_FULL_NAME, 0x19, -1, -1, -1, -1 },
    { "NAME_RELATIVE_TO_CRL_ISSUER", "I", .constantValue.asInt = OrgBouncycastleAsn1X509DistributionPointName_NAME_RELATIVE_TO_CRL_ISSUER, 0x19, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "getInstance", "LOrgBouncycastleAsn1ASN1TaggedObject;Z", "LNSObject;", "ILOrgBouncycastleAsn1ASN1Encodable;", "LOrgBouncycastleAsn1X509GeneralNames;", "LOrgBouncycastleAsn1ASN1TaggedObject;", "toString", "appendObject", "LJavaLangStringBuffer;LNSString;LNSString;LNSString;" };
  static const J2ObjcClassInfo _OrgBouncycastleAsn1X509DistributionPointName = { "DistributionPointName", "org.bouncycastle.asn1.x509", ptrTable, methods, fields, 7, 0x1, 10, 4, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleAsn1X509DistributionPointName;
}

@end

OrgBouncycastleAsn1X509DistributionPointName *OrgBouncycastleAsn1X509DistributionPointName_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_) {
  OrgBouncycastleAsn1X509DistributionPointName_initialize();
  return OrgBouncycastleAsn1X509DistributionPointName_getInstanceWithId_(OrgBouncycastleAsn1ASN1TaggedObject_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, true));
}

OrgBouncycastleAsn1X509DistributionPointName *OrgBouncycastleAsn1X509DistributionPointName_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1X509DistributionPointName_initialize();
  if (obj == nil || [obj isKindOfClass:[OrgBouncycastleAsn1X509DistributionPointName class]]) {
    return (OrgBouncycastleAsn1X509DistributionPointName *) cast_chk(obj, [OrgBouncycastleAsn1X509DistributionPointName class]);
  }
  else if ([obj isKindOfClass:[OrgBouncycastleAsn1ASN1TaggedObject class]]) {
    return create_OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1ASN1TaggedObject_((OrgBouncycastleAsn1ASN1TaggedObject *) obj);
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$$", @"unknown object in factory: ", [[obj java_getClass] getName]));
}

void OrgBouncycastleAsn1X509DistributionPointName_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1X509DistributionPointName *self, jint type, id<OrgBouncycastleAsn1ASN1Encodable> name) {
  OrgBouncycastleAsn1ASN1Object_init(self);
  self->type_ = type;
  JreStrongAssign(&self->name_, name);
}

OrgBouncycastleAsn1X509DistributionPointName *new_OrgBouncycastleAsn1X509DistributionPointName_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(jint type, id<OrgBouncycastleAsn1ASN1Encodable> name) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithInt_withOrgBouncycastleAsn1ASN1Encodable_, type, name)
}

OrgBouncycastleAsn1X509DistributionPointName *create_OrgBouncycastleAsn1X509DistributionPointName_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(jint type, id<OrgBouncycastleAsn1ASN1Encodable> name) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithInt_withOrgBouncycastleAsn1ASN1Encodable_, type, name)
}

void OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509DistributionPointName *self, OrgBouncycastleAsn1X509GeneralNames *name) {
  OrgBouncycastleAsn1X509DistributionPointName_initWithInt_withOrgBouncycastleAsn1ASN1Encodable_(self, OrgBouncycastleAsn1X509DistributionPointName_FULL_NAME, name);
}

OrgBouncycastleAsn1X509DistributionPointName *new_OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509GeneralNames *name) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithOrgBouncycastleAsn1X509GeneralNames_, name)
}

OrgBouncycastleAsn1X509DistributionPointName *create_OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509GeneralNames *name) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithOrgBouncycastleAsn1X509GeneralNames_, name)
}

void OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1ASN1TaggedObject_(OrgBouncycastleAsn1X509DistributionPointName *self, OrgBouncycastleAsn1ASN1TaggedObject *obj) {
  OrgBouncycastleAsn1ASN1Object_init(self);
  self->type_ = [((OrgBouncycastleAsn1ASN1TaggedObject *) nil_chk(obj)) getTagNo];
  if (self->type_ == 0) {
    JreStrongAssign(&self->name_, OrgBouncycastleAsn1X509GeneralNames_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, false));
  }
  else {
    JreStrongAssign(&self->name_, OrgBouncycastleAsn1ASN1Set_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, false));
  }
}

OrgBouncycastleAsn1X509DistributionPointName *new_OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1ASN1TaggedObject_(OrgBouncycastleAsn1ASN1TaggedObject *obj) {
  J2OBJC_NEW_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithOrgBouncycastleAsn1ASN1TaggedObject_, obj)
}

OrgBouncycastleAsn1X509DistributionPointName *create_OrgBouncycastleAsn1X509DistributionPointName_initWithOrgBouncycastleAsn1ASN1TaggedObject_(OrgBouncycastleAsn1ASN1TaggedObject *obj) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleAsn1X509DistributionPointName, initWithOrgBouncycastleAsn1ASN1TaggedObject_, obj)
}

void OrgBouncycastleAsn1X509DistributionPointName_appendObjectWithJavaLangStringBuffer_withNSString_withNSString_withNSString_(OrgBouncycastleAsn1X509DistributionPointName *self, JavaLangStringBuffer *buf, NSString *sep, NSString *name, NSString *value) {
  NSString *indent = @"    ";
  [((JavaLangStringBuffer *) nil_chk(buf)) appendWithNSString:indent];
  [buf appendWithNSString:name];
  [buf appendWithNSString:@":"];
  [buf appendWithNSString:sep];
  [buf appendWithNSString:indent];
  [buf appendWithNSString:indent];
  [buf appendWithNSString:value];
  [buf appendWithNSString:sep];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509DistributionPointName)
