name: felectronic_certificates_ios
description: iOS implementation of the felectronic_certificates plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

flutter:
  plugin:
    implements: felectronic_certificates
    platforms:
      ios:
        pluginClass: FelectronicCertificatesPlugin
        dartPluginClass: FelectronicCertificatesIOS

dependencies:
  felectronic_certificates_platform_interface:
    path: ../felectronic_certificates_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
