name: felectronic_certificates_ios
description: >-
  iOS implementation of the felectronic_certificates plugin
  using Security.framework for Keychain certificate management.
version: 1.0.0
repository: https://github.com/nicoacevedor/felectronic_dnie
issue_tracker: https://github.com/nicoacevedor/felectronic_dnie/issues
topics:
  - certificate
  - ios
  - keychain

environment:
  sdk: ^3.11.0

flutter:
  plugin:
    implements: felectronic_certificates
    platforms:
      ios:
        pluginClass: FelectronicCertificatesPlugin
        dartPluginClass: FelectronicCertificatesIOS

dependencies:
  felectronic_certificates_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
