//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/sphincsplus/WotsPlus.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Byte.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "org/bouncycastle/pqc/crypto/sphincsplus/ADRS.h"
#include "org/bouncycastle/pqc/crypto/sphincsplus/SPHINCSPlusEngine.h"
#include "org/bouncycastle/pqc/crypto/sphincsplus/WotsPlus.h"
#include "org/bouncycastle/util/Arrays.h"
#include "org/bouncycastle/util/Pack.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/crypto/sphincsplus/WotsPlus must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcCryptoSphincsplusWotsPlus () {
 @public
  OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *engine_;
  jint w_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoSphincsplusWotsPlus, engine_, OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *)

@implementation OrgBouncycastlePqcCryptoSphincsplusWotsPlus

- (instancetype)initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine:(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *)engine {
  OrgBouncycastlePqcCryptoSphincsplusWotsPlus_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_(self, engine);
  return self;
}

- (IOSByteArray *)pkGenWithByteArray:(IOSByteArray *)skSeed
                       withByteArray:(IOSByteArray *)pkSeed
withOrgBouncycastlePqcCryptoSphincsplusADRS:(OrgBouncycastlePqcCryptoSphincsplusADRS *)paramAdrs {
  OrgBouncycastlePqcCryptoSphincsplusADRS *wotspkADRS = create_OrgBouncycastlePqcCryptoSphincsplusADRS_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusADRS_(paramAdrs);
  IOSObjectArray *tmp = [IOSObjectArray arrayWithLength:((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(engine_))->WOTS_LEN_ type:IOSClass_byteArray(1)];
  for (jint i = 0; i < engine_->WOTS_LEN_; i++) {
    OrgBouncycastlePqcCryptoSphincsplusADRS *adrs = create_OrgBouncycastlePqcCryptoSphincsplusADRS_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusADRS_(paramAdrs);
    [adrs setChainAddressWithInt:i];
    [adrs setHashAddressWithInt:0];
    IOSByteArray *sk = [engine_ PRFWithByteArray:pkSeed withByteArray:skSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs];
    IOSObjectArray_Set(tmp, i, [self chainWithByteArray:sk withInt:0 withInt:w_ - 1 withByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs]);
  }
  [wotspkADRS setTypeWithInt:OrgBouncycastlePqcCryptoSphincsplusADRS_WOTS_PK];
  [wotspkADRS setKeyPairAddressWithInt:[((OrgBouncycastlePqcCryptoSphincsplusADRS *) nil_chk(paramAdrs)) getKeyPairAddress]];
  return [engine_ T_lWithByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:wotspkADRS withByteArray:OrgBouncycastleUtilArrays_concatenateWithByteArray2_(tmp)];
}

- (IOSByteArray *)chainWithByteArray:(IOSByteArray *)X
                             withInt:(jint)i
                             withInt:(jint)s
                       withByteArray:(IOSByteArray *)pkSeed
withOrgBouncycastlePqcCryptoSphincsplusADRS:(OrgBouncycastlePqcCryptoSphincsplusADRS *)adrs {
  if (s == 0) {
    return OrgBouncycastleUtilArrays_cloneWithByteArray_(X);
  }
  if ((i + s) > (self->w_ - 1)) {
    return nil;
  }
  IOSByteArray *tmp = [self chainWithByteArray:X withInt:i withInt:s - 1 withByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs];
  [((OrgBouncycastlePqcCryptoSphincsplusADRS *) nil_chk(adrs)) setHashAddressWithInt:i + s - 1];
  tmp = [((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(engine_)) FWithByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs withByteArray:tmp];
  return tmp;
}

- (IOSByteArray *)signWithByteArray:(IOSByteArray *)M
                      withByteArray:(IOSByteArray *)skSeed
                      withByteArray:(IOSByteArray *)pkSeed
withOrgBouncycastlePqcCryptoSphincsplusADRS:(OrgBouncycastlePqcCryptoSphincsplusADRS *)paramAdrs {
  OrgBouncycastlePqcCryptoSphincsplusADRS *adrs = create_OrgBouncycastlePqcCryptoSphincsplusADRS_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusADRS_(paramAdrs);
  jint csum = 0;
  IOSIntArray *msg = [self base_wWithByteArray:M withInt:w_ withInt:((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(engine_))->WOTS_LEN1_];
  for (jint i = 0; i < engine_->WOTS_LEN1_; i++) {
    csum += w_ - 1 - IOSIntArray_Get(nil_chk(msg), i);
  }
  if ((JreIntMod(engine_->WOTS_LOGW_, 8)) != 0) {
    csum = JreLShift32(csum, (8 - (JreIntMod((engine_->WOTS_LEN2_ * engine_->WOTS_LOGW_), 8))));
  }
  jint len_2_bytes = JreIntDiv((engine_->WOTS_LEN2_ * engine_->WOTS_LOGW_ + 7), 8);
  IOSByteArray *bytes = OrgBouncycastleUtilPack_intToBigEndianWithInt_(csum);
  msg = OrgBouncycastleUtilArrays_concatenateWithIntArray_withIntArray_(msg, [self base_wWithByteArray:OrgBouncycastleUtilArrays_copyOfRangeWithByteArray_withInt_withInt_(bytes, len_2_bytes, ((IOSByteArray *) nil_chk(bytes))->size_) withInt:w_ withInt:engine_->WOTS_LEN2_]);
  IOSObjectArray *sig = [IOSObjectArray arrayWithLength:engine_->WOTS_LEN_ type:IOSClass_byteArray(1)];
  for (jint i = 0; i < engine_->WOTS_LEN_; i++) {
    [adrs setChainAddressWithInt:i];
    [adrs setHashAddressWithInt:0];
    IOSByteArray *sk = [engine_ PRFWithByteArray:pkSeed withByteArray:skSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs];
    IOSObjectArray_Set(sig, i, [self chainWithByteArray:sk withInt:0 withInt:IOSIntArray_Get(nil_chk(msg), i) withByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs]);
  }
  return OrgBouncycastleUtilArrays_concatenateWithByteArray2_(sig);
}

- (IOSIntArray *)base_wWithByteArray:(IOSByteArray *)X
                             withInt:(jint)w
                             withInt:(jint)out_len {
  jint in = 0;
  jint out = 0;
  jint total = 0;
  jint bits = 0;
  IOSIntArray *output = [IOSIntArray arrayWithLength:out_len];
  for (jint consumed = 0; consumed < out_len; consumed++) {
    if (bits == 0) {
      total = IOSByteArray_Get(nil_chk(X), in);
      in++;
      bits += 8;
    }
    bits -= ((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(engine_))->WOTS_LOGW_;
    *IOSIntArray_GetRef(output, out) = ((JreURShift32(total, bits)) & (w - 1));
    out++;
  }
  return output;
}

- (IOSByteArray *)pkFromSigWithByteArray:(IOSByteArray *)sig
                           withByteArray:(IOSByteArray *)M
                           withByteArray:(IOSByteArray *)pkSeed
withOrgBouncycastlePqcCryptoSphincsplusADRS:(OrgBouncycastlePqcCryptoSphincsplusADRS *)adrs {
  jint csum = 0;
  OrgBouncycastlePqcCryptoSphincsplusADRS *wotspkADRS = create_OrgBouncycastlePqcCryptoSphincsplusADRS_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusADRS_(adrs);
  IOSIntArray *msg = [self base_wWithByteArray:M withInt:w_ withInt:((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(engine_))->WOTS_LEN1_];
  for (jint i = 0; i < engine_->WOTS_LEN1_; i++) {
    csum += w_ - 1 - IOSIntArray_Get(nil_chk(msg), i);
  }
  csum = JreLShift32(csum, (8 - (JreIntMod((engine_->WOTS_LEN2_ * engine_->WOTS_LOGW_), 8))));
  jint len_2_bytes = JreIntDiv((engine_->WOTS_LEN2_ * engine_->WOTS_LOGW_ + 7), 8);
  msg = OrgBouncycastleUtilArrays_concatenateWithIntArray_withIntArray_(msg, [self base_wWithByteArray:OrgBouncycastleUtilArrays_copyOfRangeWithByteArray_withInt_withInt_(OrgBouncycastleUtilPack_intToBigEndianWithInt_(csum), 4 - len_2_bytes, 4) withInt:w_ withInt:engine_->WOTS_LEN2_]);
  IOSByteArray *sigI = [IOSByteArray arrayWithLength:engine_->N_];
  IOSObjectArray *tmp = [IOSObjectArray arrayWithLength:engine_->WOTS_LEN_ type:IOSClass_byteArray(1)];
  for (jint i = 0; i < engine_->WOTS_LEN_; i++) {
    [((OrgBouncycastlePqcCryptoSphincsplusADRS *) nil_chk(adrs)) setChainAddressWithInt:i];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(sig, i * engine_->N_, sigI, 0, engine_->N_);
    IOSObjectArray_Set(tmp, i, [self chainWithByteArray:sigI withInt:IOSIntArray_Get(nil_chk(msg), i) withInt:w_ - 1 - IOSIntArray_Get(msg, i) withByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:adrs]);
  }
  [wotspkADRS setTypeWithInt:OrgBouncycastlePqcCryptoSphincsplusADRS_WOTS_PK];
  [wotspkADRS setKeyPairAddressWithInt:[((OrgBouncycastlePqcCryptoSphincsplusADRS *) nil_chk(adrs)) getKeyPairAddress]];
  return [engine_ T_lWithByteArray:pkSeed withOrgBouncycastlePqcCryptoSphincsplusADRS:wotspkADRS withByteArray:OrgBouncycastleUtilArrays_concatenateWithByteArray2_(tmp)];
}

- (void)dealloc {
  RELEASE_(engine_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "[B", 0x0, 1, 2, -1, -1, -1, -1 },
    { NULL, "[B", 0x0, 3, 4, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "[I", 0x0, 7, 8, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, 9, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine:);
  methods[1].selector = @selector(pkGenWithByteArray:withByteArray:withOrgBouncycastlePqcCryptoSphincsplusADRS:);
  methods[2].selector = @selector(chainWithByteArray:withInt:withInt:withByteArray:withOrgBouncycastlePqcCryptoSphincsplusADRS:);
  methods[3].selector = @selector(signWithByteArray:withByteArray:withByteArray:withOrgBouncycastlePqcCryptoSphincsplusADRS:);
  methods[4].selector = @selector(base_wWithByteArray:withInt:withInt:);
  methods[5].selector = @selector(pkFromSigWithByteArray:withByteArray:withByteArray:withOrgBouncycastlePqcCryptoSphincsplusADRS:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "engine_", "LOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "w_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine;", "pkGen", "[B[BLOrgBouncycastlePqcCryptoSphincsplusADRS;", "chain", "[BII[BLOrgBouncycastlePqcCryptoSphincsplusADRS;", "sign", "[B[B[BLOrgBouncycastlePqcCryptoSphincsplusADRS;", "base_w", "[BII", "pkFromSig" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcCryptoSphincsplusWotsPlus = { "WotsPlus", "org.bouncycastle.pqc.crypto.sphincsplus", ptrTable, methods, fields, 7, 0x0, 6, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcCryptoSphincsplusWotsPlus;
}

@end

void OrgBouncycastlePqcCryptoSphincsplusWotsPlus_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_(OrgBouncycastlePqcCryptoSphincsplusWotsPlus *self, OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *engine) {
  NSObject_init(self);
  JreStrongAssign(&self->engine_, engine);
  self->w_ = ((OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *) nil_chk(self->engine_))->WOTS_W_;
}

OrgBouncycastlePqcCryptoSphincsplusWotsPlus *new_OrgBouncycastlePqcCryptoSphincsplusWotsPlus_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *engine) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcCryptoSphincsplusWotsPlus, initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_, engine)
}

OrgBouncycastlePqcCryptoSphincsplusWotsPlus *create_OrgBouncycastlePqcCryptoSphincsplusWotsPlus_initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_(OrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine *engine) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcCryptoSphincsplusWotsPlus, initPackagePrivateWithOrgBouncycastlePqcCryptoSphincsplusSPHINCSPlusEngine_, engine)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcCryptoSphincsplusWotsPlus)
