//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/jcajce/interfaces/BCX509Certificate.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleJcajceInterfacesBCX509Certificate")
#ifdef RESTRICT_OrgBouncycastleJcajceInterfacesBCX509Certificate
#define INCLUDE_ALL_OrgBouncycastleJcajceInterfacesBCX509Certificate 0
#else
#define INCLUDE_ALL_OrgBouncycastleJcajceInterfacesBCX509Certificate 1
#endif
#undef RESTRICT_OrgBouncycastleJcajceInterfacesBCX509Certificate

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleJcajceInterfacesBCX509Certificate_) && (INCLUDE_ALL_OrgBouncycastleJcajceInterfacesBCX509Certificate || defined(INCLUDE_OrgBouncycastleJcajceInterfacesBCX509Certificate))
#define OrgBouncycastleJcajceInterfacesBCX509Certificate_

@class OrgBouncycastleAsn1X500X500Name;
@class OrgBouncycastleAsn1X509TBSCertificate;

@protocol OrgBouncycastleJcajceInterfacesBCX509Certificate < JavaObject >

- (OrgBouncycastleAsn1X500X500Name *)getIssuerX500Name;

- (OrgBouncycastleAsn1X509TBSCertificate *)getTBSCertificateNative;

- (OrgBouncycastleAsn1X500X500Name *)getSubjectX500Name;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleJcajceInterfacesBCX509Certificate)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleJcajceInterfacesBCX509Certificate)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleJcajceInterfacesBCX509Certificate")
