name: felectronic_certificates
description: >-
  Flutter plugin for managing device-stored certificates (import, sign, list,
  delete) on Android and iOS using KeyStore and Keychain.
version: 1.0.0
repository: https://github.com/nicoacevedor/felectronic_dnie
issue_tracker: https://github.com/nicoacevedor/felectronic_dnie/issues
topics:
  - certificate
  - pkcs12
  - signing
  - keystore
  - keychain

environment:
  flutter: ">=3.22.0"
  sdk: ^3.11.0

flutter:
  plugin:
    platforms:
      android:
        default_package: felectronic_certificates_android
      ios:
        default_package: felectronic_certificates_ios

dependencies:
  felectronic_certificates_android: ^1.0.0
  felectronic_certificates_ios: ^1.0.0
  felectronic_certificates_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
