//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/es/gob/jmulticard/apdu/iso7816four/GetResponseApduCommand.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "es/gob/jmulticard/apdu/CommandApdu.h"
#include "es/gob/jmulticard/apdu/iso7816four/GetResponseApduCommand.h"
#include "java/lang/Byte.h"
#include "java/lang/Integer.h"

#if __has_feature(objc_arc)
#error "es/gob/jmulticard/apdu/iso7816four/GetResponseApduCommand must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


inline jbyte EsGobJmulticardApduIso7816fourGetResponseApduCommand_get_INS_GET_RESPONSE(void);
#define EsGobJmulticardApduIso7816fourGetResponseApduCommand_INS_GET_RESPONSE -64
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardApduIso7816fourGetResponseApduCommand, INS_GET_RESPONSE, jbyte)

@implementation EsGobJmulticardApduIso7816fourGetResponseApduCommand

- (instancetype)initWithByte:(jbyte)cla
                    withByte:(jbyte)le {
  EsGobJmulticardApduIso7816fourGetResponseApduCommand_initWithByte_withByte_(self, cla, le);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithByte:withByte:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INS_GET_RESPONSE", "B", .constantValue.asChar = EsGobJmulticardApduIso7816fourGetResponseApduCommand_INS_GET_RESPONSE, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "BB" };
  static const J2ObjcClassInfo _EsGobJmulticardApduIso7816fourGetResponseApduCommand = { "GetResponseApduCommand", "es.gob.jmulticard.apdu.iso7816four", ptrTable, methods, fields, 7, 0x11, 1, 1, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardApduIso7816fourGetResponseApduCommand;
}

@end

void EsGobJmulticardApduIso7816fourGetResponseApduCommand_initWithByte_withByte_(EsGobJmulticardApduIso7816fourGetResponseApduCommand *self, jbyte cla, jbyte le) {
  EsGobJmulticardApduCommandApdu_initWithByte_withByte_withByte_withByte_withByteArray_withJavaLangInteger_(self, cla, EsGobJmulticardApduIso7816fourGetResponseApduCommand_INS_GET_RESPONSE, (jbyte) (jint) 0x00, (jbyte) (jint) 0x00, nil, JavaLangInteger_valueOfWithNSString_(NSString_java_valueOfInt_(le)));
}

EsGobJmulticardApduIso7816fourGetResponseApduCommand *new_EsGobJmulticardApduIso7816fourGetResponseApduCommand_initWithByte_withByte_(jbyte cla, jbyte le) {
  J2OBJC_NEW_IMPL(EsGobJmulticardApduIso7816fourGetResponseApduCommand, initWithByte_withByte_, cla, le)
}

EsGobJmulticardApduIso7816fourGetResponseApduCommand *create_EsGobJmulticardApduIso7816fourGetResponseApduCommand_initWithByte_withByte_(jbyte cla, jbyte le) {
  J2OBJC_CREATE_IMPL(EsGobJmulticardApduIso7816fourGetResponseApduCommand, initWithByte_withByte_, cla, le)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardApduIso7816fourGetResponseApduCommand)
