//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/rainbow/RainbowKeyParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters")
#ifdef RESTRICT_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters 1
#endif
#undef RESTRICT_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters || defined(INCLUDE_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters))
#define OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_

#define RESTRICT_OrgBouncycastleCryptoParamsAsymmetricKeyParameter 1
#define INCLUDE_OrgBouncycastleCryptoParamsAsymmetricKeyParameter 1
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"

@class JavaLangBoolean;
@class JavaLangInteger;

@interface OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters : OrgBouncycastleCryptoParamsAsymmetricKeyParameter

#pragma mark Public

- (instancetype _Nonnull)initWithBoolean:(jboolean)isPrivate
                                 withInt:(jint)docLength;

- (jint)getDocLength;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithBoolean:(jboolean)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters)

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_initWithBoolean_withInt_(OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters *self, jboolean isPrivate, jint docLength);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters *new_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_initWithBoolean_withInt_(jboolean isPrivate, jint docLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters *create_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters_initWithBoolean_withInt_(jboolean isPrivate, jint docLength);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoRainbowRainbowKeyParameters")
