//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/es/gob/jmulticard/card/dnie/Dnie.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobJmulticardCardDnieDnie")
#ifdef RESTRICT_EsGobJmulticardCardDnieDnie
#define INCLUDE_ALL_EsGobJmulticardCardDnieDnie 0
#else
#define INCLUDE_ALL_EsGobJmulticardCardDnieDnie 1
#endif
#undef RESTRICT_EsGobJmulticardCardDnieDnie

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EsGobJmulticardCardDnieDnie_) && (INCLUDE_ALL_EsGobJmulticardCardDnieDnie || defined(INCLUDE_EsGobJmulticardCardDnieDnie))
#define EsGobJmulticardCardDnieDnie_

#define RESTRICT_EsGobJmulticardCardIso7816eightAbstractIso7816EightCard 1
#define INCLUDE_EsGobJmulticardCardIso7816eightAbstractIso7816EightCard 1
#include "es/gob/jmulticard/card/iso7816eight/AbstractIso7816EightCard.h"

#define RESTRICT_EsGobJmulticardCardDnieDni 1
#define INCLUDE_EsGobJmulticardCardDnieDni 1
#include "es/gob/jmulticard/card/dnie/Dni.h"

#define RESTRICT_EsGobJmulticardCardCwa14890Cwa14890Card 1
#define INCLUDE_EsGobJmulticardCardCwa14890Cwa14890Card 1
#include "es/gob/jmulticard/card/cwa14890/Cwa14890Card.h"

@class EsGobJmulticardAsn1DerPkcs15Cdf;
@class EsGobJmulticardCardLocation;
@class EsGobJmulticardCryptoHelper;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangByte;
@class JavaLangInteger;
@class JavaSecurityCertX509Certificate;
@class JavaxSecurityAuthCallbackPasswordCallback;
@protocol EsGobJmulticardCardCwa14890Cwa14890PrivateConstants;
@protocol EsGobJmulticardCardCwa14890Cwa14890PublicConstants;
@protocol EsGobJmulticardCardPrivateKeyReference;
@protocol EsGobJmulticardConnectionApduConnection;
@protocol JavaSecurityInterfacesRSAPrivateKey;
@protocol JavaSecurityInterfacesRSAPublicKey;
@protocol JavaxSecurityAuthCallbackCallbackHandler;

@interface EsGobJmulticardCardDnieDnie : EsGobJmulticardCardIso7816eightAbstractIso7816EightCard < EsGobJmulticardCardDnieDni, EsGobJmulticardCardCwa14890Cwa14890Card > {
 @public
  JavaSecurityCertX509Certificate *certCiph_;
  JavaSecurityCertX509Certificate *certIcc_;
  id<EsGobJmulticardConnectionApduConnection> rawConnection_;
  EsGobJmulticardCryptoHelper *cryptoHelper_;
}
@property (readonly, copy, class) NSString *CERT_ALIAS_AUTH NS_SWIFT_NAME(CERT_ALIAS_AUTH);
@property (readonly, copy, class) NSString *CERT_ALIAS_SIGN NS_SWIFT_NAME(CERT_ALIAS_SIGN);
@property (readonly, copy, class) NSString *CERT_ALIAS_INTERMEDIATE_CA NS_SWIFT_NAME(CERT_ALIAS_INTERMEDIATE_CA);
@property (readonly, class, strong) EsGobJmulticardCardLocation *CDF_LOCATION NS_SWIFT_NAME(CDF_LOCATION);
@property (readonly, class, strong) EsGobJmulticardCardLocation *PRKDF_LOCATION NS_SWIFT_NAME(PRKDF_LOCATION);

#pragma mark Public

- (IOSByteArray *)changePINWithNSString:(NSString *)oldPin
                           withNSString:(NSString *)newPin;

- (IOSByteArray *)cipherDataWithByteArray:(IOSByteArray *)data
withEsGobJmulticardCardPrivateKeyReference:(id<EsGobJmulticardCardPrivateKeyReference>)privateKeyReference;

+ (void)connectWithEsGobJmulticardConnectionApduConnection:(id<EsGobJmulticardConnectionApduConnection>)conn;

- (jboolean)externalAuthenticationWithByteArray:(IOSByteArray *)extAuthenticationData;

- (IOSObjectArray *)getAliases;

- (NSString *)getCardName;

- (EsGobJmulticardAsn1DerPkcs15Cdf *)getCdf;

- (JavaSecurityCertX509Certificate *)getCertificateWithNSString:(NSString *)alias;

- (IOSByteArray *)getChrCCvIfdWithEsGobJmulticardCardCwa14890Cwa14890PublicConstants:(id<EsGobJmulticardCardCwa14890Cwa14890PublicConstants>)consts;

- (id<JavaSecurityInterfacesRSAPublicKey>)getIccCertPublicKey;

- (NSString *)getIdesp;

- (jint)getIfdKeyLengthWithEsGobJmulticardCardCwa14890Cwa14890PublicConstants:(id<EsGobJmulticardCardCwa14890Cwa14890PublicConstants>)consts;

- (id<JavaSecurityInterfacesRSAPrivateKey>)getIfdPrivateKeyWithEsGobJmulticardCardCwa14890Cwa14890PrivateConstants:(id<EsGobJmulticardCardCwa14890Cwa14890PrivateConstants>)consts;

- (IOSByteArray *)getInternalAuthenticateMessageWithByteArray:(IOSByteArray *)randomIfd
                                                withByteArray:(IOSByteArray *)chrCCvIfd;

- (jint)getPinRetriesLeft;

- (id<EsGobJmulticardCardPrivateKeyReference>)getPrivateKeyWithNSString:(NSString *)alias;

- (IOSByteArray *)getRefIccPrivateKeyWithEsGobJmulticardCardCwa14890Cwa14890PublicConstants:(id<EsGobJmulticardCardCwa14890Cwa14890PublicConstants>)consts;

- (IOSByteArray *)getSerialNumber;

- (void)openSecureChannelIfNotAlreadyOpened;

- (void)openSecureChannelIfNotAlreadyOpenedWithBoolean:(jboolean)doChv;

- (void)setCallbackHandlerWithJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

- (void)setKeysToAuthenticationWithByteArray:(IOSByteArray *)refPublicKey
                               withByteArray:(IOSByteArray *)refPrivateKey;

- (void)setPasswordCallbackWithJavaxSecurityAuthCallbackPasswordCallback:(JavaxSecurityAuthCallbackPasswordCallback *)pwc;

- (IOSByteArray *)signWithByteArray:(IOSByteArray *)data
                       withNSString:(NSString *)signAlgorithm
withEsGobJmulticardCardPrivateKeyReference:(id<EsGobJmulticardCardPrivateKeyReference>)privateKeyReference;

- (NSString *)description;

- (void)verifyIcc;

- (void)verifyIfdCertificateChainWithEsGobJmulticardCardCwa14890Cwa14890PublicConstants:(id<EsGobJmulticardCardCwa14890Cwa14890PublicConstants>)consts;

- (void)verifyPinWithJavaxSecurityAuthCallbackPasswordCallback:(JavaxSecurityAuthCallbackPasswordCallback *)psc;

#pragma mark Protected

- (instancetype _Nonnull)initWithEsGobJmulticardConnectionApduConnection:(id<EsGobJmulticardConnectionApduConnection>)conn
                           withJavaxSecurityAuthCallbackPasswordCallback:(JavaxSecurityAuthCallbackPasswordCallback *)pwc
                                         withEsGobJmulticardCryptoHelper:(EsGobJmulticardCryptoHelper *)cryptoHlpr
                            withJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)ch;

- (EsGobJmulticardCryptoHelper *)getCryptoHelper;

- (id<EsGobJmulticardCardCwa14890Cwa14890PrivateConstants>)getCwa14890PrivateConstants;

- (id<EsGobJmulticardCardCwa14890Cwa14890PublicConstants>)getCwa14890PublicConstants;

- (JavaxSecurityAuthCallbackPasswordCallback *)getInternalPasswordCallback;

- (JavaxSecurityAuthCallbackPasswordCallback *)getInternalPasswordCallbackWithBoolean:(jboolean)reset;

- (JavaxSecurityAuthCallbackPasswordCallback *)getPasswordCallback;

- (NSString *)getPinMessageWithInt:(jint)retriesLeft;

- (jboolean)isSecurityChannelOpen;

- (void)loadCertificates;

- (void)loadCertificatesPaths;

- (void)loadKeyReferences;

- (jboolean)needAuthorizationToSign;

- (jboolean)needsPinForLoadingCerts;

- (void)selectMasterFile;

- (IOSByteArray *)signInternalWithByteArray:(IOSByteArray *)data
                               withNSString:(NSString *)signAlgorithm
 withEsGobJmulticardCardPrivateKeyReference:(id<EsGobJmulticardCardPrivateKeyReference>)privateKeyReference;

- (IOSByteArray *)signOperationWithByteArray:(IOSByteArray *)data
                                withNSString:(NSString *)signAlgorithm
  withEsGobJmulticardCardPrivateKeyReference:(id<EsGobJmulticardCardPrivateKeyReference>)privateKeyReference;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithByte:(jbyte)arg0
withEsGobJmulticardConnectionApduConnection:(id<EsGobJmulticardConnectionApduConnection>)arg1 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(EsGobJmulticardCardDnieDnie)

J2OBJC_FIELD_SETTER(EsGobJmulticardCardDnieDnie, certCiph_, JavaSecurityCertX509Certificate *)
J2OBJC_FIELD_SETTER(EsGobJmulticardCardDnieDnie, certIcc_, JavaSecurityCertX509Certificate *)
J2OBJC_FIELD_SETTER(EsGobJmulticardCardDnieDnie, rawConnection_, id<EsGobJmulticardConnectionApduConnection>)
J2OBJC_FIELD_SETTER(EsGobJmulticardCardDnieDnie, cryptoHelper_, EsGobJmulticardCryptoHelper *)

inline NSString *EsGobJmulticardCardDnieDnie_get_CERT_ALIAS_AUTH(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobJmulticardCardDnieDnie_CERT_ALIAS_AUTH;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie, CERT_ALIAS_AUTH, NSString *)

inline NSString *EsGobJmulticardCardDnieDnie_get_CERT_ALIAS_SIGN(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobJmulticardCardDnieDnie_CERT_ALIAS_SIGN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie, CERT_ALIAS_SIGN, NSString *)

inline NSString *EsGobJmulticardCardDnieDnie_get_CERT_ALIAS_INTERMEDIATE_CA(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobJmulticardCardDnieDnie_CERT_ALIAS_INTERMEDIATE_CA;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie, CERT_ALIAS_INTERMEDIATE_CA, NSString *)

inline EsGobJmulticardCardLocation *EsGobJmulticardCardDnieDnie_get_CDF_LOCATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT EsGobJmulticardCardLocation *EsGobJmulticardCardDnieDnie_CDF_LOCATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie, CDF_LOCATION, EsGobJmulticardCardLocation *)

inline EsGobJmulticardCardLocation *EsGobJmulticardCardDnieDnie_get_PRKDF_LOCATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT EsGobJmulticardCardLocation *EsGobJmulticardCardDnieDnie_PRKDF_LOCATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie, PRKDF_LOCATION, EsGobJmulticardCardLocation *)

FOUNDATION_EXPORT void EsGobJmulticardCardDnieDnie_initWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackPasswordCallback_withEsGobJmulticardCryptoHelper_withJavaxSecurityAuthCallbackCallbackHandler_(EsGobJmulticardCardDnieDnie *self, id<EsGobJmulticardConnectionApduConnection> conn, JavaxSecurityAuthCallbackPasswordCallback *pwc, EsGobJmulticardCryptoHelper *cryptoHlpr, id<JavaxSecurityAuthCallbackCallbackHandler> ch);

FOUNDATION_EXPORT EsGobJmulticardCardDnieDnie *new_EsGobJmulticardCardDnieDnie_initWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackPasswordCallback_withEsGobJmulticardCryptoHelper_withJavaxSecurityAuthCallbackCallbackHandler_(id<EsGobJmulticardConnectionApduConnection> conn, JavaxSecurityAuthCallbackPasswordCallback *pwc, EsGobJmulticardCryptoHelper *cryptoHlpr, id<JavaxSecurityAuthCallbackCallbackHandler> ch) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobJmulticardCardDnieDnie *create_EsGobJmulticardCardDnieDnie_initWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackPasswordCallback_withEsGobJmulticardCryptoHelper_withJavaxSecurityAuthCallbackCallbackHandler_(id<EsGobJmulticardConnectionApduConnection> conn, JavaxSecurityAuthCallbackPasswordCallback *pwc, EsGobJmulticardCryptoHelper *cryptoHlpr, id<JavaxSecurityAuthCallbackCallbackHandler> ch);

FOUNDATION_EXPORT void EsGobJmulticardCardDnieDnie_connectWithEsGobJmulticardConnectionApduConnection_(id<EsGobJmulticardConnectionApduConnection> conn);

J2OBJC_TYPE_LITERAL_HEADER(EsGobJmulticardCardDnieDnie)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EsGobJmulticardCardDnieDnie")
