//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/custom/sec/SecP128R1Field.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/math/BigInteger.h"
#include "java/security/SecureRandom.h"
#include "org/bouncycastle/math/ec/custom/sec/SecP128R1Field.h"
#include "org/bouncycastle/math/raw/Mod.h"
#include "org/bouncycastle/math/raw/Nat.h"
#include "org/bouncycastle/math/raw/Nat128.h"
#include "org/bouncycastle/math/raw/Nat256.h"
#include "org/bouncycastle/util/Pack.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/math/ec/custom/sec/SecP128R1Field must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastleMathEcCustomSecSecP128R1Field ()

+ (void)addPInvToWithIntArray:(IOSIntArray *)z;

+ (void)subPInvFromWithIntArray:(IOSIntArray *)z;

@end

inline jlong OrgBouncycastleMathEcCustomSecSecP128R1Field_get_M(void);
#define OrgBouncycastleMathEcCustomSecSecP128R1Field_M 4294967295LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastleMathEcCustomSecSecP128R1Field, M, jlong)

inline IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_get_PExt(void);
static IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleMathEcCustomSecSecP128R1Field, PExt, IOSIntArray *)

inline IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_get_PExtInv(void);
static IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleMathEcCustomSecSecP128R1Field, PExtInv, IOSIntArray *)

inline jint OrgBouncycastleMathEcCustomSecSecP128R1Field_get_P3s1(void);
#define OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 2147483646
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastleMathEcCustomSecSecP128R1Field, P3s1, jint)

inline jint OrgBouncycastleMathEcCustomSecSecP128R1Field_get_PExt7s1(void);
#define OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt7s1 2147483646
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastleMathEcCustomSecSecP128R1Field, PExt7s1, jint)

__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(IOSIntArray *z);

__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecP128R1Field_subPInvFromWithIntArray_(IOSIntArray *z);

J2OBJC_INITIALIZED_DEFN(OrgBouncycastleMathEcCustomSecSecP128R1Field)

IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_P;

@implementation OrgBouncycastleMathEcCustomSecSecP128R1Field

+ (IOSIntArray *)P {
  return OrgBouncycastleMathEcCustomSecSecP128R1Field_P;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)addWithIntArray:(IOSIntArray *)x
           withIntArray:(IOSIntArray *)y
           withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_addWithIntArray_withIntArray_withIntArray_(x, y, z);
}

+ (void)addExtWithIntArray:(IOSIntArray *)xx
              withIntArray:(IOSIntArray *)yy
              withIntArray:(IOSIntArray *)zz {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_addExtWithIntArray_withIntArray_withIntArray_(xx, yy, zz);
}

+ (void)addOneWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_addOneWithIntArray_withIntArray_(x, z);
}

+ (IOSIntArray *)fromBigIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  return OrgBouncycastleMathEcCustomSecSecP128R1Field_fromBigIntegerWithJavaMathBigInteger_(x);
}

+ (void)halfWithIntArray:(IOSIntArray *)x
            withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_halfWithIntArray_withIntArray_(x, z);
}

+ (void)invWithIntArray:(IOSIntArray *)x
           withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_invWithIntArray_withIntArray_(x, z);
}

+ (jint)isZeroWithIntArray:(IOSIntArray *)x {
  return OrgBouncycastleMathEcCustomSecSecP128R1Field_isZeroWithIntArray_(x);
}

+ (void)multiplyWithIntArray:(IOSIntArray *)x
                withIntArray:(IOSIntArray *)y
                withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_multiplyWithIntArray_withIntArray_withIntArray_(x, y, z);
}

+ (void)multiplyAddToExtWithIntArray:(IOSIntArray *)x
                        withIntArray:(IOSIntArray *)y
                        withIntArray:(IOSIntArray *)zz {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_multiplyAddToExtWithIntArray_withIntArray_withIntArray_(x, y, zz);
}

+ (void)negateWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_negateWithIntArray_withIntArray_(x, z);
}

+ (void)randomWithJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)r
                              withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_randomWithJavaSecuritySecureRandom_withIntArray_(r, z);
}

+ (void)randomMultWithJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)r
                                  withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_randomMultWithJavaSecuritySecureRandom_withIntArray_(r, z);
}

+ (void)reduceWithIntArray:(IOSIntArray *)xx
              withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(xx, z);
}

+ (void)reduce32WithInt:(jint)x
           withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduce32WithInt_withIntArray_(x, z);
}

+ (void)squareWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_squareWithIntArray_withIntArray_(x, z);
}

+ (void)squareNWithIntArray:(IOSIntArray *)x
                    withInt:(jint)n
               withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_squareNWithIntArray_withInt_withIntArray_(x, n, z);
}

+ (void)subtractWithIntArray:(IOSIntArray *)x
                withIntArray:(IOSIntArray *)y
                withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_subtractWithIntArray_withIntArray_withIntArray_(x, y, z);
}

+ (void)subtractExtWithIntArray:(IOSIntArray *)xx
                   withIntArray:(IOSIntArray *)yy
                   withIntArray:(IOSIntArray *)zz {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_subtractExtWithIntArray_withIntArray_withIntArray_(xx, yy, zz);
}

+ (void)twiceWithIntArray:(IOSIntArray *)x
             withIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_twiceWithIntArray_withIntArray_(x, z);
}

+ (void)addPInvToWithIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(z);
}

+ (void)subPInvFromWithIntArray:(IOSIntArray *)z {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_subPInvFromWithIntArray_(z);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 2, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 3, 4, -1, -1, -1, -1 },
    { NULL, "[I", 0x9, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 7, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 8, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x9, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 11, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 12, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 13, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 14, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 16, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 17, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 20, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 21, 22, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 25, 4, -1, -1, -1, -1 },
    { NULL, "V", 0xa, 26, 10, -1, -1, -1, -1 },
    { NULL, "V", 0xa, 27, 10, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(addWithIntArray:withIntArray:withIntArray:);
  methods[2].selector = @selector(addExtWithIntArray:withIntArray:withIntArray:);
  methods[3].selector = @selector(addOneWithIntArray:withIntArray:);
  methods[4].selector = @selector(fromBigIntegerWithJavaMathBigInteger:);
  methods[5].selector = @selector(halfWithIntArray:withIntArray:);
  methods[6].selector = @selector(invWithIntArray:withIntArray:);
  methods[7].selector = @selector(isZeroWithIntArray:);
  methods[8].selector = @selector(multiplyWithIntArray:withIntArray:withIntArray:);
  methods[9].selector = @selector(multiplyAddToExtWithIntArray:withIntArray:withIntArray:);
  methods[10].selector = @selector(negateWithIntArray:withIntArray:);
  methods[11].selector = @selector(randomWithJavaSecuritySecureRandom:withIntArray:);
  methods[12].selector = @selector(randomMultWithJavaSecuritySecureRandom:withIntArray:);
  methods[13].selector = @selector(reduceWithIntArray:withIntArray:);
  methods[14].selector = @selector(reduce32WithInt:withIntArray:);
  methods[15].selector = @selector(squareWithIntArray:withIntArray:);
  methods[16].selector = @selector(squareNWithIntArray:withInt:withIntArray:);
  methods[17].selector = @selector(subtractWithIntArray:withIntArray:withIntArray:);
  methods[18].selector = @selector(subtractExtWithIntArray:withIntArray:withIntArray:);
  methods[19].selector = @selector(twiceWithIntArray:withIntArray:);
  methods[20].selector = @selector(addPInvToWithIntArray:);
  methods[21].selector = @selector(subPInvFromWithIntArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "M", "J", .constantValue.asLong = OrgBouncycastleMathEcCustomSecSecP128R1Field_M, 0x1a, -1, -1, -1, -1 },
    { "P", "[I", .constantValue.asLong = 0, 0x18, -1, 28, -1, -1 },
    { "PExt", "[I", .constantValue.asLong = 0, 0x1a, -1, 29, -1, -1 },
    { "PExtInv", "[I", .constantValue.asLong = 0, 0x1a, -1, 30, -1, -1 },
    { "P3s1", "I", .constantValue.asInt = OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1, 0x1a, -1, -1, -1, -1 },
    { "PExt7s1", "I", .constantValue.asInt = OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt7s1, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "add", "[I[I[I", "addExt", "addOne", "[I[I", "fromBigInteger", "LJavaMathBigInteger;", "half", "inv", "isZero", "[I", "multiply", "multiplyAddToExt", "negate", "random", "LJavaSecuritySecureRandom;[I", "randomMult", "reduce", "reduce32", "I[I", "square", "squareN", "[II[I", "subtract", "subtractExt", "twice", "addPInvTo", "subPInvFrom", &OrgBouncycastleMathEcCustomSecSecP128R1Field_P, &OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt, &OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcCustomSecSecP128R1Field = { "SecP128R1Field", "org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 22, 6, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcCustomSecSecP128R1Field;
}

+ (void)initialize {
  if (self == [OrgBouncycastleMathEcCustomSecSecP128R1Field class]) {
    JreStrongAssignAndConsume(&OrgBouncycastleMathEcCustomSecSecP128R1Field_P, [IOSIntArray newArrayWithInts:(jint[]){ (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFD } count:4]);
    JreStrongAssignAndConsume(&OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt, [IOSIntArray newArrayWithInts:(jint[]){ (jint) 0x00000001, (jint) 0x00000000, (jint) 0x00000000, (jint) 0x00000004, (jint) 0xFFFFFFFE, (jint) 0xFFFFFFFF, (jint) 0x00000003, (jint) 0xFFFFFFFC } count:8]);
    JreStrongAssignAndConsume(&OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv, [IOSIntArray newArrayWithInts:(jint[]){ (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFB, (jint) 0x00000001, (jint) 0x00000000, (jint) 0xFFFFFFFC, (jint) 0x00000003 } count:8]);
    J2OBJC_SET_INITIALIZED(OrgBouncycastleMathEcCustomSecSecP128R1Field)
  }
}

@end

void OrgBouncycastleMathEcCustomSecSecP128R1Field_init(OrgBouncycastleMathEcCustomSecSecP128R1Field *self) {
  NSObject_init(self);
}

OrgBouncycastleMathEcCustomSecSecP128R1Field *new_OrgBouncycastleMathEcCustomSecSecP128R1Field_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecP128R1Field, init)
}

OrgBouncycastleMathEcCustomSecSecP128R1Field *create_OrgBouncycastleMathEcCustomSecSecP128R1Field_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecP128R1Field, init)
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_addWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat128_addWithIntArray_withIntArray_withIntArray_(x, y, z);
  if (c != 0 || ((JreURShift32(IOSIntArray_Get(nil_chk(z), 3), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 && OrgBouncycastleMathRawNat128_gteWithIntArray_withIntArray_(z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P))) {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_addExtWithIntArray_withIntArray_withIntArray_(IOSIntArray *xx, IOSIntArray *yy, IOSIntArray *zz) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat256_addWithIntArray_withIntArray_withIntArray_(xx, yy, zz);
  if (c != 0 || ((JreURShift32(IOSIntArray_Get(nil_chk(zz), 7), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt7s1 && OrgBouncycastleMathRawNat256_gteWithIntArray_withIntArray_(zz, OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt))) {
    OrgBouncycastleMathRawNat_addToWithInt_withIntArray_withIntArray_(((IOSIntArray *) nil_chk(OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv))->size_, OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv, zz);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_addOneWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat_incWithInt_withIntArray_withIntArray_(4, x, z);
  if (c != 0 || ((JreURShift32(IOSIntArray_Get(nil_chk(z), 3), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 && OrgBouncycastleMathRawNat128_gteWithIntArray_withIntArray_(z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P))) {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(z);
  }
}

IOSIntArray *OrgBouncycastleMathEcCustomSecSecP128R1Field_fromBigIntegerWithJavaMathBigInteger_(JavaMathBigInteger *x) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  IOSIntArray *z = OrgBouncycastleMathRawNat128_fromBigIntegerWithJavaMathBigInteger_(x);
  if ((JreURShift32(IOSIntArray_Get(nil_chk(z), 3), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 && OrgBouncycastleMathRawNat128_gteWithIntArray_withIntArray_(z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P)) {
    OrgBouncycastleMathRawNat128_subFromWithIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP128R1Field_P, z);
  }
  return z;
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_halfWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  if ((IOSIntArray_Get(nil_chk(x), 0) & 1) == 0) {
    OrgBouncycastleMathRawNat_shiftDownBitWithInt_withIntArray_withInt_withIntArray_(4, x, 0, z);
  }
  else {
    jint c = OrgBouncycastleMathRawNat128_addWithIntArray_withIntArray_withIntArray_(x, OrgBouncycastleMathEcCustomSecSecP128R1Field_P, z);
    OrgBouncycastleMathRawNat_shiftDownBitWithInt_withIntArray_withInt_(4, z, c);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_invWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  OrgBouncycastleMathRawMod_checkedModOddInverseWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP128R1Field_P, x, z);
}

jint OrgBouncycastleMathEcCustomSecSecP128R1Field_isZeroWithIntArray_(IOSIntArray *x) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint d = 0;
  for (jint i = 0; i < 4; ++i) {
    d |= IOSIntArray_Get(nil_chk(x), i);
  }
  d = (JreURShift32(d, 1)) | (d & 1);
  return JreRShift32((d - 1), 31);
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_multiplyWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  IOSIntArray *tt = OrgBouncycastleMathRawNat128_createExt();
  OrgBouncycastleMathRawNat128_mulWithIntArray_withIntArray_withIntArray_(x, y, tt);
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(tt, z);
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_multiplyAddToExtWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *zz) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat128_mulAddToWithIntArray_withIntArray_withIntArray_(x, y, zz);
  if (c != 0 || ((JreURShift32(IOSIntArray_Get(nil_chk(zz), 7), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt7s1 && OrgBouncycastleMathRawNat256_gteWithIntArray_withIntArray_(zz, OrgBouncycastleMathEcCustomSecSecP128R1Field_PExt))) {
    OrgBouncycastleMathRawNat_addToWithInt_withIntArray_withIntArray_(((IOSIntArray *) nil_chk(OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv))->size_, OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv, zz);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_negateWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  if (0 != OrgBouncycastleMathEcCustomSecSecP128R1Field_isZeroWithIntArray_(x)) {
    OrgBouncycastleMathRawNat128_subWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP128R1Field_P, OrgBouncycastleMathEcCustomSecSecP128R1Field_P, z);
  }
  else {
    OrgBouncycastleMathRawNat128_subWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP128R1Field_P, x, z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_randomWithJavaSecuritySecureRandom_withIntArray_(JavaSecuritySecureRandom *r, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  IOSByteArray *bb = [IOSByteArray arrayWithLength:4 * 4];
  do {
    [((JavaSecuritySecureRandom *) nil_chk(r)) nextBytesWithByteArray:bb];
    OrgBouncycastleUtilPack_littleEndianToIntWithByteArray_withInt_withIntArray_withInt_withInt_(bb, 0, z, 0, 4);
  }
  while (0 == OrgBouncycastleMathRawNat_lessThanWithInt_withIntArray_withIntArray_(4, z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P));
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_randomMultWithJavaSecuritySecureRandom_withIntArray_(JavaSecuritySecureRandom *r, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  do {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_randomWithJavaSecuritySecureRandom_withIntArray_(r, z);
  }
  while (0 != OrgBouncycastleMathEcCustomSecSecP128R1Field_isZeroWithIntArray_(z));
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(IOSIntArray *xx, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jlong x0 = IOSIntArray_Get(nil_chk(xx), 0) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x1 = IOSIntArray_Get(xx, 1) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x2 = IOSIntArray_Get(xx, 2) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x3 = IOSIntArray_Get(xx, 3) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x4 = IOSIntArray_Get(xx, 4) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x5 = IOSIntArray_Get(xx, 5) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x6 = IOSIntArray_Get(xx, 6) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  jlong x7 = IOSIntArray_Get(xx, 7) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
  x3 += x7;
  x6 += (JreLShift64(x7, 1));
  x2 += x6;
  x5 += (JreLShift64(x6, 1));
  x1 += x5;
  x4 += (JreLShift64(x5, 1));
  x0 += x4;
  x3 += (JreLShift64(x4, 1));
  *IOSIntArray_GetRef(nil_chk(z), 0) = (jint) x0;
  x1 += (JreURShift64(x0, 32));
  *IOSIntArray_GetRef(z, 1) = (jint) x1;
  x2 += (JreURShift64(x1, 32));
  *IOSIntArray_GetRef(z, 2) = (jint) x2;
  x3 += (JreURShift64(x2, 32));
  *IOSIntArray_GetRef(z, 3) = (jint) x3;
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduce32WithInt_withIntArray_((jint) (JreURShift64(x3, 32)), z);
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_reduce32WithInt_withIntArray_(jint x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  while (x != 0) {
    jlong c;
    jlong x4 = x & OrgBouncycastleMathEcCustomSecSecP128R1Field_M;
    c = (IOSIntArray_Get(nil_chk(z), 0) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) + x4;
    *IOSIntArray_GetRef(z, 0) = (jint) c;
    JreRShiftAssignLong(&c, 32);
    if (c != 0) {
      c += (IOSIntArray_Get(z, 1) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
      *IOSIntArray_GetRef(z, 1) = (jint) c;
      JreRShiftAssignLong(&c, 32);
      c += (IOSIntArray_Get(z, 2) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
      *IOSIntArray_GetRef(z, 2) = (jint) c;
      JreRShiftAssignLong(&c, 32);
    }
    c += (IOSIntArray_Get(z, 3) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) + (JreLShift64(x4, 1));
    *IOSIntArray_GetRef(z, 3) = (jint) c;
    JreRShiftAssignLong(&c, 32);
    x = (jint) c;
  }
  if ((JreURShift32(IOSIntArray_Get(nil_chk(z), 3), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 && OrgBouncycastleMathRawNat128_gteWithIntArray_withIntArray_(z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P)) {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_squareWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  IOSIntArray *tt = OrgBouncycastleMathRawNat128_createExt();
  OrgBouncycastleMathRawNat128_squareWithIntArray_withIntArray_(x, tt);
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(tt, z);
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_squareNWithIntArray_withInt_withIntArray_(IOSIntArray *x, jint n, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  IOSIntArray *tt = OrgBouncycastleMathRawNat128_createExt();
  OrgBouncycastleMathRawNat128_squareWithIntArray_withIntArray_(x, tt);
  OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(tt, z);
  while (--n > 0) {
    OrgBouncycastleMathRawNat128_squareWithIntArray_withIntArray_(z, tt);
    OrgBouncycastleMathEcCustomSecSecP128R1Field_reduceWithIntArray_withIntArray_(tt, z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_subtractWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat128_subWithIntArray_withIntArray_withIntArray_(x, y, z);
  if (c != 0) {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_subPInvFromWithIntArray_(z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_subtractExtWithIntArray_withIntArray_withIntArray_(IOSIntArray *xx, IOSIntArray *yy, IOSIntArray *zz) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat_subWithInt_withIntArray_withIntArray_withIntArray_(10, xx, yy, zz);
  if (c != 0) {
    OrgBouncycastleMathRawNat_subFromWithInt_withIntArray_withIntArray_(((IOSIntArray *) nil_chk(OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv))->size_, OrgBouncycastleMathEcCustomSecSecP128R1Field_PExtInv, zz);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_twiceWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jint c = OrgBouncycastleMathRawNat_shiftUpBitWithInt_withIntArray_withInt_withIntArray_(4, x, 0, z);
  if (c != 0 || ((JreURShift32(IOSIntArray_Get(nil_chk(z), 3), 1)) >= OrgBouncycastleMathEcCustomSecSecP128R1Field_P3s1 && OrgBouncycastleMathRawNat128_gteWithIntArray_withIntArray_(z, OrgBouncycastleMathEcCustomSecSecP128R1Field_P))) {
    OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(z);
  }
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_addPInvToWithIntArray_(IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jlong c = (IOSIntArray_Get(nil_chk(z), 0) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) + 1;
  *IOSIntArray_GetRef(z, 0) = (jint) c;
  JreRShiftAssignLong(&c, 32);
  if (c != 0) {
    c += (IOSIntArray_Get(z, 1) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
    *IOSIntArray_GetRef(z, 1) = (jint) c;
    JreRShiftAssignLong(&c, 32);
    c += (IOSIntArray_Get(z, 2) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
    *IOSIntArray_GetRef(z, 2) = (jint) c;
    JreRShiftAssignLong(&c, 32);
  }
  c += (IOSIntArray_Get(z, 3) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) + 2;
  *IOSIntArray_GetRef(z, 3) = (jint) c;
}

void OrgBouncycastleMathEcCustomSecSecP128R1Field_subPInvFromWithIntArray_(IOSIntArray *z) {
  OrgBouncycastleMathEcCustomSecSecP128R1Field_initialize();
  jlong c = (IOSIntArray_Get(nil_chk(z), 0) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) - 1;
  *IOSIntArray_GetRef(z, 0) = (jint) c;
  JreRShiftAssignLong(&c, 32);
  if (c != 0) {
    c += (IOSIntArray_Get(z, 1) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
    *IOSIntArray_GetRef(z, 1) = (jint) c;
    JreRShiftAssignLong(&c, 32);
    c += (IOSIntArray_Get(z, 2) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M);
    *IOSIntArray_GetRef(z, 2) = (jint) c;
    JreRShiftAssignLong(&c, 32);
  }
  c += (IOSIntArray_Get(z, 3) & OrgBouncycastleMathEcCustomSecSecP128R1Field_M) - 2;
  *IOSIntArray_GetRef(z, 3) = (jint) c;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcCustomSecSecP128R1Field)
