//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/custom/sec/SecT233FieldElement.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/math/ec/ECFieldElement.h"
#include "org/bouncycastle/math/ec/custom/sec/SecT233Field.h"
#include "org/bouncycastle/math/ec/custom/sec/SecT233FieldElement.h"
#include "org/bouncycastle/math/raw/Nat256.h"
#include "org/bouncycastle/util/Arrays.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/math/ec/custom/sec/SecT233FieldElement must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation OrgBouncycastleMathEcCustomSecSecT233FieldElement

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(self, x);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastleMathEcCustomSecSecT233FieldElement_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithLongArray:(IOSLongArray *)x {
  OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(self, x);
  return self;
}

- (jboolean)isOne {
  return OrgBouncycastleMathRawNat256_isOne64WithLongArray_(x_);
}

- (jboolean)isZero {
  return OrgBouncycastleMathRawNat256_isZero64WithLongArray_(x_);
}

- (jboolean)testBitZero {
  return (IOSLongArray_Get(nil_chk(x_), 0) & 1LL) != 0LL;
}

- (JavaMathBigInteger *)toBigInteger {
  return OrgBouncycastleMathRawNat256_toBigInteger64WithLongArray_(x_);
}

- (NSString *)getFieldName {
  return @"SecT233Field";
}

- (jint)getFieldSize {
  return 233;
}

- (OrgBouncycastleMathEcECFieldElement *)addWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_addWithLongArray_withLongArray_withLongArray_(x_, ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(b, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)addOne {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_addOneWithLongArray_withLongArray_(x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)subtractWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  return [self addWithOrgBouncycastleMathEcECFieldElement:b];
}

- (OrgBouncycastleMathEcECFieldElement *)multiplyWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_multiplyWithLongArray_withLongArray_withLongArray_(x_, ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(b, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)multiplyMinusProductWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b
                                                             withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                             withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y {
  return [self multiplyPlusProductWithOrgBouncycastleMathEcECFieldElement:b withOrgBouncycastleMathEcECFieldElement:x withOrgBouncycastleMathEcECFieldElement:y];
}

- (OrgBouncycastleMathEcECFieldElement *)multiplyPlusProductWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b
                                                            withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                            withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y {
  IOSLongArray *ax = self->x_;
  IOSLongArray *bx = ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(b, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_;
  IOSLongArray *xx = ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(x, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_;
  IOSLongArray *yx = ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(y, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_;
  IOSLongArray *tt = OrgBouncycastleMathRawNat256_createExt64();
  OrgBouncycastleMathEcCustomSecSecT233Field_multiplyAddToExtWithLongArray_withLongArray_withLongArray_(ax, bx, tt);
  OrgBouncycastleMathEcCustomSecSecT233Field_multiplyAddToExtWithLongArray_withLongArray_withLongArray_(xx, yx, tt);
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_reduceWithLongArray_withLongArray_(tt, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)divideWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  return [self multiplyWithOrgBouncycastleMathEcECFieldElement:[((OrgBouncycastleMathEcECFieldElement *) nil_chk(b)) invert]];
}

- (OrgBouncycastleMathEcECFieldElement *)negate {
  return self;
}

- (OrgBouncycastleMathEcECFieldElement *)square {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_squareWithLongArray_withLongArray_(x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)squareMinusProductWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                           withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y {
  return [self squarePlusProductWithOrgBouncycastleMathEcECFieldElement:x withOrgBouncycastleMathEcECFieldElement:y];
}

- (OrgBouncycastleMathEcECFieldElement *)squarePlusProductWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                          withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y {
  IOSLongArray *ax = self->x_;
  IOSLongArray *xx = ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(x, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_;
  IOSLongArray *yx = ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(y, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_;
  IOSLongArray *tt = OrgBouncycastleMathRawNat256_createExt64();
  OrgBouncycastleMathEcCustomSecSecT233Field_squareAddToExtWithLongArray_withLongArray_(ax, tt);
  OrgBouncycastleMathEcCustomSecSecT233Field_multiplyAddToExtWithLongArray_withLongArray_withLongArray_(xx, yx, tt);
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_reduceWithLongArray_withLongArray_(tt, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)squarePowWithInt:(jint)pow {
  if (pow < 1) {
    return self;
  }
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_squareNWithLongArray_withInt_withLongArray_(x_, pow, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)halfTrace {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_halfTraceWithLongArray_withLongArray_(x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (jboolean)hasFastTrace {
  return true;
}

- (jint)trace {
  return OrgBouncycastleMathEcCustomSecSecT233Field_traceWithLongArray_(x_);
}

- (OrgBouncycastleMathEcECFieldElement *)invert {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_invertWithLongArray_withLongArray_(x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (OrgBouncycastleMathEcECFieldElement *)sqrt {
  IOSLongArray *z = OrgBouncycastleMathRawNat256_create64();
  OrgBouncycastleMathEcCustomSecSecT233Field_sqrtWithLongArray_withLongArray_(x_, z);
  return create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(z);
}

- (jint)getRepresentation {
  return OrgBouncycastleMathEcECFieldElement_F2m_TPB;
}

- (jint)getM {
  return 233;
}

- (jint)getK1 {
  return 74;
}

- (jint)getK2 {
  return 0;
}

- (jint)getK3 {
  return 0;
}

- (jboolean)isEqual:(id)other {
  if (JreObjectEqualsEquals(other, self)) {
    return true;
  }
  if (!([other isKindOfClass:[OrgBouncycastleMathEcCustomSecSecT233FieldElement class]])) {
    return false;
  }
  OrgBouncycastleMathEcCustomSecSecT233FieldElement *o = (OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk(other, [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]);
  return OrgBouncycastleMathRawNat256_eq64WithLongArray_withLongArray_(x_, ((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(o))->x_);
}

- (NSUInteger)hash {
  return 2330074 ^ OrgBouncycastleUtilArrays_hashCodeWithLongArray_withInt_withInt_(x_, 0, 4);
}

- (void)dealloc {
  RELEASE_(x_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 4, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 5, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 8, 7, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 9, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 12, 11, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 17, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithJavaMathBigInteger:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithLongArray:);
  methods[3].selector = @selector(isOne);
  methods[4].selector = @selector(isZero);
  methods[5].selector = @selector(testBitZero);
  methods[6].selector = @selector(toBigInteger);
  methods[7].selector = @selector(getFieldName);
  methods[8].selector = @selector(getFieldSize);
  methods[9].selector = @selector(addWithOrgBouncycastleMathEcECFieldElement:);
  methods[10].selector = @selector(addOne);
  methods[11].selector = @selector(subtractWithOrgBouncycastleMathEcECFieldElement:);
  methods[12].selector = @selector(multiplyWithOrgBouncycastleMathEcECFieldElement:);
  methods[13].selector = @selector(multiplyMinusProductWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:);
  methods[14].selector = @selector(multiplyPlusProductWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:);
  methods[15].selector = @selector(divideWithOrgBouncycastleMathEcECFieldElement:);
  methods[16].selector = @selector(negate);
  methods[17].selector = @selector(square);
  methods[18].selector = @selector(squareMinusProductWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:);
  methods[19].selector = @selector(squarePlusProductWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:);
  methods[20].selector = @selector(squarePowWithInt:);
  methods[21].selector = @selector(halfTrace);
  methods[22].selector = @selector(hasFastTrace);
  methods[23].selector = @selector(trace);
  methods[24].selector = @selector(invert);
  methods[25].selector = @selector(sqrt);
  methods[26].selector = @selector(getRepresentation);
  methods[27].selector = @selector(getM);
  methods[28].selector = @selector(getK1);
  methods[29].selector = @selector(getK2);
  methods[30].selector = @selector(getK3);
  methods[31].selector = @selector(isEqual:);
  methods[32].selector = @selector(hash);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "x_", "[J", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaMathBigInteger;", "[J", "add", "LOrgBouncycastleMathEcECFieldElement;", "subtract", "multiply", "multiplyMinusProduct", "LOrgBouncycastleMathEcECFieldElement;LOrgBouncycastleMathEcECFieldElement;LOrgBouncycastleMathEcECFieldElement;", "multiplyPlusProduct", "divide", "squareMinusProduct", "LOrgBouncycastleMathEcECFieldElement;LOrgBouncycastleMathEcECFieldElement;", "squarePlusProduct", "squarePow", "I", "equals", "LNSObject;", "hashCode" };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcCustomSecSecT233FieldElement = { "SecT233FieldElement", "org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 33, 1, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcCustomSecSecT233FieldElement;
}

@end

void OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(OrgBouncycastleMathEcCustomSecSecT233FieldElement *self, JavaMathBigInteger *x) {
  OrgBouncycastleMathEcECFieldElement_AbstractF2m_init(self);
  if (x == nil || [x signum] < 0 || [x bitLength] > 233) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"x value invalid for SecT233FieldElement");
  }
  JreStrongAssign(&self->x_, OrgBouncycastleMathEcCustomSecSecT233Field_fromBigIntegerWithJavaMathBigInteger_(x));
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(JavaMathBigInteger *x) {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, initWithJavaMathBigInteger_, x)
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(JavaMathBigInteger *x) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, initWithJavaMathBigInteger_, x)
}

void OrgBouncycastleMathEcCustomSecSecT233FieldElement_init(OrgBouncycastleMathEcCustomSecSecT233FieldElement *self) {
  OrgBouncycastleMathEcECFieldElement_AbstractF2m_init(self);
  JreStrongAssign(&self->x_, OrgBouncycastleMathRawNat256_create64());
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, init)
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, init)
}

void OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(OrgBouncycastleMathEcCustomSecSecT233FieldElement *self, IOSLongArray *x) {
  OrgBouncycastleMathEcECFieldElement_AbstractF2m_init(self);
  JreStrongAssign(&self->x_, x);
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(IOSLongArray *x) {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, initWithLongArray_, x)
}

OrgBouncycastleMathEcCustomSecSecT233FieldElement *create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(IOSLongArray *x) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecT233FieldElement, initWithLongArray_, x)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcCustomSecSecT233FieldElement)
