//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/jcajce/spec/LMSHSSParameterSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec")
#ifdef RESTRICT_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec
#define INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec 1
#endif
#undef RESTRICT_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_) && (INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec || defined(INCLUDE_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec))
#define OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_

#define RESTRICT_JavaSecuritySpecAlgorithmParameterSpec 1
#define INCLUDE_JavaSecuritySpecAlgorithmParameterSpec 1
#include "java/security/spec/AlgorithmParameterSpec.h"

@class IOSObjectArray;

@interface OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray:(IOSObjectArray *)specs;

- (IOSObjectArray *)getLMSSpecs;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec)

FOUNDATION_EXPORT void OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *self, IOSObjectArray *specs);

FOUNDATION_EXPORT OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *new_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(IOSObjectArray *specs) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *create_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(IOSObjectArray *specs);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec")
