//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/jcajce/spec/LMSParameterSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSParameterSpec")
#ifdef RESTRICT_OrgBouncycastlePqcJcajceSpecLMSParameterSpec
#define INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSParameterSpec 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSParameterSpec 1
#endif
#undef RESTRICT_OrgBouncycastlePqcJcajceSpecLMSParameterSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcJcajceSpecLMSParameterSpec_) && (INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSParameterSpec || defined(INCLUDE_OrgBouncycastlePqcJcajceSpecLMSParameterSpec))
#define OrgBouncycastlePqcJcajceSpecLMSParameterSpec_

#define RESTRICT_JavaSecuritySpecAlgorithmParameterSpec 1
#define INCLUDE_JavaSecuritySpecAlgorithmParameterSpec 1
#include "java/security/spec/AlgorithmParameterSpec.h"

@class OrgBouncycastlePqcCryptoLmsLMOtsParameters;
@class OrgBouncycastlePqcCryptoLmsLMSigParameters;

@interface OrgBouncycastlePqcJcajceSpecLMSParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastlePqcCryptoLmsLMSigParameters:(OrgBouncycastlePqcCryptoLmsLMSigParameters *)lmSigParams
                             withOrgBouncycastlePqcCryptoLmsLMOtsParameters:(OrgBouncycastlePqcCryptoLmsLMOtsParameters *)lmOtsParameters;

- (OrgBouncycastlePqcCryptoLmsLMOtsParameters *)getOtsParams;

- (OrgBouncycastlePqcCryptoLmsLMSigParameters *)getSigParams;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcJcajceSpecLMSParameterSpec)

FOUNDATION_EXPORT void OrgBouncycastlePqcJcajceSpecLMSParameterSpec_initWithOrgBouncycastlePqcCryptoLmsLMSigParameters_withOrgBouncycastlePqcCryptoLmsLMOtsParameters_(OrgBouncycastlePqcJcajceSpecLMSParameterSpec *self, OrgBouncycastlePqcCryptoLmsLMSigParameters *lmSigParams, OrgBouncycastlePqcCryptoLmsLMOtsParameters *lmOtsParameters);

FOUNDATION_EXPORT OrgBouncycastlePqcJcajceSpecLMSParameterSpec *new_OrgBouncycastlePqcJcajceSpecLMSParameterSpec_initWithOrgBouncycastlePqcCryptoLmsLMSigParameters_withOrgBouncycastlePqcCryptoLmsLMOtsParameters_(OrgBouncycastlePqcCryptoLmsLMSigParameters *lmSigParams, OrgBouncycastlePqcCryptoLmsLMOtsParameters *lmOtsParameters) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcJcajceSpecLMSParameterSpec *create_OrgBouncycastlePqcJcajceSpecLMSParameterSpec_initWithOrgBouncycastlePqcCryptoLmsLMSigParameters_withOrgBouncycastlePqcCryptoLmsLMOtsParameters_(OrgBouncycastlePqcCryptoLmsLMSigParameters *lmSigParams, OrgBouncycastlePqcCryptoLmsLMOtsParameters *lmOtsParameters);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcJcajceSpecLMSParameterSpec)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcJcajceSpecLMSParameterSpec")
