//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/qtesla/QTESLAPrivateKeyParameters.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"
#include "org/bouncycastle/pqc/crypto/qtesla/QTESLAPrivateKeyParameters.h"
#include "org/bouncycastle/pqc/crypto/qtesla/QTESLASecurityCategory.h"
#include "org/bouncycastle/util/Arrays.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/pqc/crypto/qtesla/QTESLAPrivateKeyParameters must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters () {
 @public
  jint securityCategory_;
  IOSByteArray *privateKey_QTESLAPrivateKeyParameters_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters, privateKey_QTESLAPrivateKeyParameters_, IOSByteArray *)

@implementation OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters

- (instancetype)initWithInt:(jint)securityCategory
              withByteArray:(IOSByteArray *)privateKey {
  OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters_initWithInt_withByteArray_(self, securityCategory, privateKey);
  return self;
}

- (jint)getSecurityCategory {
  return self->securityCategory_;
}

- (IOSByteArray *)getSecret {
  return OrgBouncycastleUtilArrays_cloneWithByteArray_(privateKey_QTESLAPrivateKeyParameters_);
}

- (void)dealloc {
  RELEASE_(privateKey_QTESLAPrivateKeyParameters_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withByteArray:);
  methods[1].selector = @selector(getSecurityCategory);
  methods[2].selector = @selector(getSecret);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "securityCategory_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "privateKey_QTESLAPrivateKeyParameters_", "[B", .constantValue.asLong = 0, 0x2, 1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I[B", "privateKey" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters = { "QTESLAPrivateKeyParameters", "org.bouncycastle.pqc.crypto.qtesla", ptrTable, methods, fields, 7, 0x11, 3, 2, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters;
}

@end

void OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters_initWithInt_withByteArray_(OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters *self, jint securityCategory, IOSByteArray *privateKey) {
  OrgBouncycastleCryptoParamsAsymmetricKeyParameter_initWithBoolean_(self, true);
  if (((IOSByteArray *) nil_chk(privateKey))->size_ != OrgBouncycastlePqcCryptoQteslaQTESLASecurityCategory_getPrivateSizeWithInt_(securityCategory)) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"invalid key size for security category");
  }
  self->securityCategory_ = securityCategory;
  JreStrongAssign(&self->privateKey_QTESLAPrivateKeyParameters_, OrgBouncycastleUtilArrays_cloneWithByteArray_(privateKey));
}

OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters *new_OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters_initWithInt_withByteArray_(jint securityCategory, IOSByteArray *privateKey) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters, initWithInt_withByteArray_, securityCategory, privateKey)
}

OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters *create_OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters_initWithInt_withByteArray_(jint securityCategory, IOSByteArray *privateKey) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters, initWithInt_withByteArray_, securityCategory, privateKey)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcCryptoQteslaQTESLAPrivateKeyParameters)
