//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/endo/GLVTypeBParameters.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/math/ec/endo/GLVTypeBParameters.h"
#include "org/bouncycastle/math/ec/endo/ScalarSplitParameters.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/math/ec/endo/GLVTypeBParameters must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation OrgBouncycastleMathEcEndoGLVTypeBParameters

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)beta
                    withJavaMathBigInteger:(JavaMathBigInteger *)lambda
withOrgBouncycastleMathEcEndoScalarSplitParameters:(OrgBouncycastleMathEcEndoScalarSplitParameters *)splitParams {
  OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_(self, beta, lambda, splitParams);
  return self;
}

- (JavaMathBigInteger *)getBeta {
  return beta_;
}

- (JavaMathBigInteger *)getLambda {
  return lambda_;
}

- (OrgBouncycastleMathEcEndoScalarSplitParameters *)getSplitParams {
  return splitParams_;
}

- (void)dealloc {
  RELEASE_(beta_);
  RELEASE_(lambda_);
  RELEASE_(splitParams_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcEndoScalarSplitParameters;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithJavaMathBigInteger:withJavaMathBigInteger:withOrgBouncycastleMathEcEndoScalarSplitParameters:);
  methods[1].selector = @selector(getBeta);
  methods[2].selector = @selector(getLambda);
  methods[3].selector = @selector(getSplitParams);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "beta_", "LJavaMathBigInteger;", .constantValue.asLong = 0, 0x14, -1, -1, -1, -1 },
    { "lambda_", "LJavaMathBigInteger;", .constantValue.asLong = 0, 0x14, -1, -1, -1, -1 },
    { "splitParams_", "LOrgBouncycastleMathEcEndoScalarSplitParameters;", .constantValue.asLong = 0, 0x14, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaMathBigInteger;LJavaMathBigInteger;LOrgBouncycastleMathEcEndoScalarSplitParameters;" };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcEndoGLVTypeBParameters = { "GLVTypeBParameters", "org.bouncycastle.math.ec.endo", ptrTable, methods, fields, 7, 0x1, 4, 3, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcEndoGLVTypeBParameters;
}

@end

void OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_(OrgBouncycastleMathEcEndoGLVTypeBParameters *self, JavaMathBigInteger *beta, JavaMathBigInteger *lambda, OrgBouncycastleMathEcEndoScalarSplitParameters *splitParams) {
  NSObject_init(self);
  JreStrongAssign(&self->beta_, beta);
  JreStrongAssign(&self->lambda_, lambda);
  JreStrongAssign(&self->splitParams_, splitParams);
}

OrgBouncycastleMathEcEndoGLVTypeBParameters *new_OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_(JavaMathBigInteger *beta, JavaMathBigInteger *lambda, OrgBouncycastleMathEcEndoScalarSplitParameters *splitParams) {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcEndoGLVTypeBParameters, initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_, beta, lambda, splitParams)
}

OrgBouncycastleMathEcEndoGLVTypeBParameters *create_OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_(JavaMathBigInteger *beta, JavaMathBigInteger *lambda, OrgBouncycastleMathEcEndoScalarSplitParameters *splitParams) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcEndoGLVTypeBParameters, initWithJavaMathBigInteger_withJavaMathBigInteger_withOrgBouncycastleMathEcEndoScalarSplitParameters_, beta, lambda, splitParams)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcEndoGLVTypeBParameters)
