//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/math/ntru/polynomial/LongPolynomial2.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2")
#ifdef RESTRICT_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 1
#endif
#undef RESTRICT_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2_) && (INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 || defined(INCLUDE_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2))
#define OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2_

@class JavaLangBoolean;
@class JavaLangInteger;
@class OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial;

@interface OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 : NSObject

#pragma mark Public

- (instancetype _Nonnull)initWithOrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial:(OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial *)p;

- (id)java_clone;

- (jboolean)isEqual:(id)obj;

- (OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *)multWithOrgBouncycastlePqcMathNtruPolynomialLongPolynomial2:(OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *)poly2;

- (void)mult2AndWithInt:(jint)mask;

- (void)subAndWithOrgBouncycastlePqcMathNtruPolynomialLongPolynomial2:(OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *)b
                                                              withInt:(jint)mask;

- (OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial *)toIntegerPolynomial;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2)

FOUNDATION_EXPORT void OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2_initWithOrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial_(OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *self, OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial *p);

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *new_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2_initWithOrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial_(OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial *p) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2 *create_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2_initWithOrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial_(OrgBouncycastlePqcMathNtruPolynomialIntegerPolynomial *p);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialLongPolynomial2")
