//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/cms/CMSAttributeTableGenerator.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "org/bouncycastle/cms/CMSAttributeTableGenerator.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/cms/CMSAttributeTableGenerator must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_CONTENT_TYPE = @"contentType";
NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST = @"digest";
NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE = @"encryptedDigest";
NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST_ALGORITHM_IDENTIFIER = @"digestAlgID";
NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_MAC_ALGORITHM_IDENTIFIER = @"macAlgID";
NSString *OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE_ALGORITHM_IDENTIFIER = @"signatureAlgID";

@implementation OrgBouncycastleCmsCMSAttributeTableGenerator

+ (NSString *)CONTENT_TYPE {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_CONTENT_TYPE;
}

+ (NSString *)DIGEST {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST;
}

+ (NSString *)SIGNATURE {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE;
}

+ (NSString *)DIGEST_ALGORITHM_IDENTIFIER {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST_ALGORITHM_IDENTIFIER;
}

+ (NSString *)MAC_ALGORITHM_IDENTIFIER {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_MAC_ALGORITHM_IDENTIFIER;
}

+ (NSString *)SIGNATURE_ALGORITHM_IDENTIFIER {
  return OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE_ALGORITHM_IDENTIFIER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgBouncycastleAsn1CmsAttributeTable;", 0x401, 0, 1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getAttributesWithJavaUtilMap:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "CONTENT_TYPE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 3, -1, -1 },
    { "DIGEST", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 4, -1, -1 },
    { "SIGNATURE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 5, -1, -1 },
    { "DIGEST_ALGORITHM_IDENTIFIER", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 6, -1, -1 },
    { "MAC_ALGORITHM_IDENTIFIER", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 7, -1, -1 },
    { "SIGNATURE_ALGORITHM_IDENTIFIER", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 8, -1, -1 },
  };
  static const void *ptrTable[] = { "getAttributes", "LJavaUtilMap;", "LOrgBouncycastleCmsCMSAttributeTableGenerationException;", &OrgBouncycastleCmsCMSAttributeTableGenerator_CONTENT_TYPE, &OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST, &OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE, &OrgBouncycastleCmsCMSAttributeTableGenerator_DIGEST_ALGORITHM_IDENTIFIER, &OrgBouncycastleCmsCMSAttributeTableGenerator_MAC_ALGORITHM_IDENTIFIER, &OrgBouncycastleCmsCMSAttributeTableGenerator_SIGNATURE_ALGORITHM_IDENTIFIER };
  static const J2ObjcClassInfo _OrgBouncycastleCmsCMSAttributeTableGenerator = { "CMSAttributeTableGenerator", "org.bouncycastle.cms", ptrTable, methods, fields, 7, 0x609, 1, 6, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleCmsCMSAttributeTableGenerator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgBouncycastleCmsCMSAttributeTableGenerator)
