//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/jce/interfaces/ECKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleJceInterfacesECKey")
#ifdef RESTRICT_OrgBouncycastleJceInterfacesECKey
#define INCLUDE_ALL_OrgBouncycastleJceInterfacesECKey 0
#else
#define INCLUDE_ALL_OrgBouncycastleJceInterfacesECKey 1
#endif
#undef RESTRICT_OrgBouncycastleJceInterfacesECKey

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleJceInterfacesECKey_) && (INCLUDE_ALL_OrgBouncycastleJceInterfacesECKey || defined(INCLUDE_OrgBouncycastleJceInterfacesECKey))
#define OrgBouncycastleJceInterfacesECKey_

@class OrgBouncycastleJceSpecECParameterSpec;

@protocol OrgBouncycastleJceInterfacesECKey < JavaObject >

- (OrgBouncycastleJceSpecECParameterSpec *)getParameters;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleJceInterfacesECKey)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleJceInterfacesECKey)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleJceInterfacesECKey")
