//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/es/gob/afirma/core/AOUnsupportedSignFormatException.java
//



#include "J2ObjC_source.h"
#include "es/gob/afirma/core/AOException.h"
#include "es/gob/afirma/core/AOUnsupportedSignFormatException.h"
#include "java/lang/Exception.h"
#include "java/lang/Long.h"

#if __has_feature(objc_arc)
#error "es/gob/afirma/core/AOUnsupportedSignFormatException must not be compiled with ARC (-fobjc-arc)"
#endif

inline jlong EsGobAfirmaCoreAOUnsupportedSignFormatException_get_serialVersionUID(void);
#define EsGobAfirmaCoreAOUnsupportedSignFormatException_serialVersionUID -1LL
J2OBJC_STATIC_FIELD_CONSTANT(EsGobAfirmaCoreAOUnsupportedSignFormatException, serialVersionUID, jlong)

@implementation EsGobAfirmaCoreAOUnsupportedSignFormatException

- (instancetype)initWithNSString:(NSString *)msg {
  EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_(self, msg);
  return self;
}

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangException:(JavaLangException *)e {
  EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_withJavaLangException_(self, msg, e);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithNSString:withJavaLangException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EsGobAfirmaCoreAOUnsupportedSignFormatException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LNSString;LJavaLangException;" };
  static const J2ObjcClassInfo _EsGobAfirmaCoreAOUnsupportedSignFormatException = { "AOUnsupportedSignFormatException", "es.gob.afirma.core", ptrTable, methods, fields, 7, 0x11, 2, 1, -1, -1, -1, -1, -1 };
  return &_EsGobAfirmaCoreAOUnsupportedSignFormatException;
}

@end

void EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_(EsGobAfirmaCoreAOUnsupportedSignFormatException *self, NSString *msg) {
  EsGobAfirmaCoreAOException_initWithNSString_(self, msg);
}

EsGobAfirmaCoreAOUnsupportedSignFormatException *new_EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_(NSString *msg) {
  J2OBJC_NEW_IMPL(EsGobAfirmaCoreAOUnsupportedSignFormatException, initWithNSString_, msg)
}

EsGobAfirmaCoreAOUnsupportedSignFormatException *create_EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_(NSString *msg) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaCoreAOUnsupportedSignFormatException, initWithNSString_, msg)
}

void EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_withJavaLangException_(EsGobAfirmaCoreAOUnsupportedSignFormatException *self, NSString *msg, JavaLangException *e) {
  EsGobAfirmaCoreAOException_initWithNSString_withJavaLangThrowable_(self, msg, e);
}

EsGobAfirmaCoreAOUnsupportedSignFormatException *new_EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_withJavaLangException_(NSString *msg, JavaLangException *e) {
  J2OBJC_NEW_IMPL(EsGobAfirmaCoreAOUnsupportedSignFormatException, initWithNSString_withJavaLangException_, msg, e)
}

EsGobAfirmaCoreAOUnsupportedSignFormatException *create_EsGobAfirmaCoreAOUnsupportedSignFormatException_initWithNSString_withJavaLangException_(NSString *msg, JavaLangException *e) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaCoreAOUnsupportedSignFormatException, initWithNSString_withJavaLangException_, msg, e)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobAfirmaCoreAOUnsupportedSignFormatException)
