//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/es/gob/afirma/core/RuntimeConfigNeededException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException")
#ifdef RESTRICT_EsGobAfirmaCoreRuntimeConfigNeededException
#define INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException 0
#else
#define INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException 1
#endif
#undef RESTRICT_EsGobAfirmaCoreRuntimeConfigNeededException

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EsGobAfirmaCoreRuntimeConfigNeededException_) && (INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException || defined(INCLUDE_EsGobAfirmaCoreRuntimeConfigNeededException))
#define EsGobAfirmaCoreRuntimeConfigNeededException_

#define RESTRICT_EsGobAfirmaCoreAOException 1
#define INCLUDE_EsGobAfirmaCoreAOException 1
#include "es/gob/afirma/core/AOException.h"

@class EsGobAfirmaCoreRuntimeConfigNeededException_RequestType;
@class JavaLangThrowable;

@interface EsGobAfirmaCoreRuntimeConfigNeededException : EsGobAfirmaCoreAOException

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)msg
withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType:(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)requestType
                              withNSString:(NSString *)requestorText
                              withNSString:(NSString *)param;

- (instancetype __nonnull)initWithNSString:(NSString *)msg
withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType:(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)requestType
                              withNSString:(NSString *)requestorText
                              withNSString:(NSString *)param
                     withJavaLangThrowable:(JavaLangThrowable *)e;

- (NSString *)getParam;

- (NSString *)getRequestorText;

- (EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)getRequestType;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaCoreRuntimeConfigNeededException)

FOUNDATION_EXPORT void EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_(EsGobAfirmaCoreRuntimeConfigNeededException *self, NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param);

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException *new_EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_(NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException *create_EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_(NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param);

FOUNDATION_EXPORT void EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_withJavaLangThrowable_(EsGobAfirmaCoreRuntimeConfigNeededException *self, NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param, JavaLangThrowable *e);

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException *new_EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_withJavaLangThrowable_(NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param, JavaLangThrowable *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException *create_EsGobAfirmaCoreRuntimeConfigNeededException_initWithNSString_withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType_withNSString_withNSString_withJavaLangThrowable_(NSString *msg, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *requestType, NSString *requestorText, NSString *param, JavaLangThrowable *e);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaCoreRuntimeConfigNeededException)

#endif

#if !defined (EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_) && (INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException || defined(INCLUDE_EsGobAfirmaCoreRuntimeConfigNeededException_RequestType))
#define EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(jint, EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_Enum) {
  EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_Enum_CONFIRM = 0,
  EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_Enum_PASSWORD = 1,
};

@interface EsGobAfirmaCoreRuntimeConfigNeededException_RequestType : JavaLangEnum

@property (readonly, class, nonnull) EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *CONFIRM NS_SWIFT_NAME(CONFIRM);
@property (readonly, class, nonnull) EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *PASSWORD NS_SWIFT_NAME(PASSWORD);
#pragma mark Public

+ (EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_values_[];

inline EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_get_CONFIRM(void);
J2OBJC_ENUM_CONSTANT(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType, CONFIRM)

inline EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_get_PASSWORD(void);
J2OBJC_ENUM_CONSTANT(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType, PASSWORD)

FOUNDATION_EXPORT IOSObjectArray *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_values(void);

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *EsGobAfirmaCoreRuntimeConfigNeededException_RequestType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EsGobAfirmaCoreRuntimeConfigNeededException")
