//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/ECAlgorithms.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Byte.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Integer.h"
#include "java/lang/Math.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/math/ec/ECAlgorithms.h"
#include "org/bouncycastle/math/ec/ECConstants.h"
#include "org/bouncycastle/math/ec/ECCurve.h"
#include "org/bouncycastle/math/ec/ECFieldElement.h"
#include "org/bouncycastle/math/ec/ECLookupTable.h"
#include "org/bouncycastle/math/ec/ECPoint.h"
#include "org/bouncycastle/math/ec/ECPointMap.h"
#include "org/bouncycastle/math/ec/FixedPointCombMultiplier.h"
#include "org/bouncycastle/math/ec/FixedPointPreCompInfo.h"
#include "org/bouncycastle/math/ec/FixedPointUtil.h"
#include "org/bouncycastle/math/ec/WNafPreCompInfo.h"
#include "org/bouncycastle/math/ec/WNafUtil.h"
#include "org/bouncycastle/math/ec/endo/ECEndomorphism.h"
#include "org/bouncycastle/math/ec/endo/EndoUtil.h"
#include "org/bouncycastle/math/ec/endo/GLVEndomorphism.h"
#include "org/bouncycastle/math/field/FiniteField.h"
#include "org/bouncycastle/math/field/PolynomialExtensionField.h"
#include "org/bouncycastle/math/raw/Nat.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/math/ec/ECAlgorithms must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface OrgBouncycastleMathEcECAlgorithms ()

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompP
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompNegP
                                                                              withByteArray:(IOSByteArray *)wnafP
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompQ
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompNegQ
                                                                              withByteArray:(IOSByteArray *)wnafQ;

+ (OrgBouncycastleMathEcECPoint *)implSumOfMultipliesWithBooleanArray:(IOSBooleanArray *)negs
                        withOrgBouncycastleMathEcWNafPreCompInfoArray:(IOSObjectArray *)infos
                                                       withByteArray2:(IOSObjectArray *)wnafs;

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p
                                                                      withJavaMathBigInteger:(JavaMathBigInteger *)k
                                                            withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)q
                                                                      withJavaMathBigInteger:(JavaMathBigInteger *)l;

@end

__attribute__((unused)) static OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_withOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_(IOSObjectArray *preCompP, IOSObjectArray *preCompNegP, IOSByteArray *wnafP, IOSObjectArray *preCompQ, IOSObjectArray *preCompNegQ, IOSByteArray *wnafQ);

__attribute__((unused)) static OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithBooleanArray_withOrgBouncycastleMathEcWNafPreCompInfoArray_withByteArray2_(IOSBooleanArray *negs, IOSObjectArray *infos, IOSObjectArray *wnafs);

__attribute__((unused)) static OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *p, JavaMathBigInteger *k, OrgBouncycastleMathEcECPoint *q, JavaMathBigInteger *l);

@implementation OrgBouncycastleMathEcECAlgorithms

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastleMathEcECAlgorithms_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jboolean)isF2mCurveWithOrgBouncycastleMathEcECCurve:(OrgBouncycastleMathEcECCurve *)c {
  return OrgBouncycastleMathEcECAlgorithms_isF2mCurveWithOrgBouncycastleMathEcECCurve_(c);
}

+ (jboolean)isF2mFieldWithOrgBouncycastleMathFieldFiniteField:(id<OrgBouncycastleMathFieldFiniteField>)field {
  return OrgBouncycastleMathEcECAlgorithms_isF2mFieldWithOrgBouncycastleMathFieldFiniteField_(field);
}

+ (jboolean)isFpCurveWithOrgBouncycastleMathEcECCurve:(OrgBouncycastleMathEcECCurve *)c {
  return OrgBouncycastleMathEcECAlgorithms_isFpCurveWithOrgBouncycastleMathEcECCurve_(c);
}

+ (jboolean)isFpFieldWithOrgBouncycastleMathFieldFiniteField:(id<OrgBouncycastleMathFieldFiniteField>)field {
  return OrgBouncycastleMathEcECAlgorithms_isFpFieldWithOrgBouncycastleMathFieldFiniteField_(field);
}

+ (OrgBouncycastleMathEcECPoint *)sumOfMultipliesWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)ps
                                                           withJavaMathBigIntegerArray:(IOSObjectArray *)ks {
  return OrgBouncycastleMathEcECAlgorithms_sumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(ps, ks);
}

+ (OrgBouncycastleMathEcECPoint *)sumOfTwoMultipliesWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)P
                                                              withJavaMathBigInteger:(JavaMathBigInteger *)a
                                                    withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)Q
                                                              withJavaMathBigInteger:(JavaMathBigInteger *)b {
  return OrgBouncycastleMathEcECAlgorithms_sumOfTwoMultipliesWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, a, Q, b);
}

+ (OrgBouncycastleMathEcECPoint *)shamirsTrickWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)P
                                                        withJavaMathBigInteger:(JavaMathBigInteger *)k
                                              withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)Q
                                                        withJavaMathBigInteger:(JavaMathBigInteger *)l {
  return OrgBouncycastleMathEcECAlgorithms_shamirsTrickWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, k, Q, l);
}

+ (OrgBouncycastleMathEcECPoint *)importPointWithOrgBouncycastleMathEcECCurve:(OrgBouncycastleMathEcECCurve *)c
                                             withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p {
  return OrgBouncycastleMathEcECAlgorithms_importPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(c, p);
}

+ (void)montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray:(IOSObjectArray *)zs
                                                            withInt:(jint)off
                                                            withInt:(jint)len {
  OrgBouncycastleMathEcECAlgorithms_montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray_withInt_withInt_(zs, off, len);
}

+ (void)montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray:(IOSObjectArray *)zs
                                                            withInt:(jint)off
                                                            withInt:(jint)len
                            withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)scale_ {
  OrgBouncycastleMathEcECAlgorithms_montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray_withInt_withInt_withOrgBouncycastleMathEcECFieldElement_(zs, off, len, scale_);
}

+ (OrgBouncycastleMathEcECPoint *)referenceMultiplyWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p
                                                             withJavaMathBigInteger:(JavaMathBigInteger *)k {
  return OrgBouncycastleMathEcECAlgorithms_referenceMultiplyWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(p, k);
}

+ (OrgBouncycastleMathEcECPoint *)validatePointWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p {
  return OrgBouncycastleMathEcECAlgorithms_validatePointWithOrgBouncycastleMathEcECPoint_(p);
}

+ (OrgBouncycastleMathEcECPoint *)cleanPointWithOrgBouncycastleMathEcECCurve:(OrgBouncycastleMathEcECCurve *)c
                                            withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p {
  return OrgBouncycastleMathEcECAlgorithms_cleanPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(c, p);
}

+ (OrgBouncycastleMathEcECPoint *)implCheckResultWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p {
  return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(p);
}

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickJsfWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)P
                                                               withJavaMathBigInteger:(JavaMathBigInteger *)k
                                                     withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)Q
                                                               withJavaMathBigInteger:(JavaMathBigInteger *)l {
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickJsfWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, k, Q, l);
}

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickWNafWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)P
                                                                withJavaMathBigInteger:(JavaMathBigInteger *)k
                                                      withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)Q
                                                                withJavaMathBigInteger:(JavaMathBigInteger *)l {
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, k, Q, l);
}

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickWNafWithOrgBouncycastleMathEcEndoECEndomorphism:(id<OrgBouncycastleMathEcEndoECEndomorphism>)endomorphism
                                                                 withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)P
                                                                           withJavaMathBigInteger:(JavaMathBigInteger *)k
                                                                           withJavaMathBigInteger:(JavaMathBigInteger *)l {
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withJavaMathBigInteger_(endomorphism, P, k, l);
}

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompP
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompNegP
                                                                              withByteArray:(IOSByteArray *)wnafP
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompQ
                                                      withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompNegQ
                                                                              withByteArray:(IOSByteArray *)wnafQ {
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_withOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_(preCompP, preCompNegP, wnafP, preCompQ, preCompNegQ, wnafQ);
}

+ (OrgBouncycastleMathEcECPoint *)implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)ps
                                                               withJavaMathBigIntegerArray:(IOSObjectArray *)ks {
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(ps, ks);
}

+ (OrgBouncycastleMathEcECPoint *)implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)ps
                                                                  withJavaMathBigIntegerArray:(IOSObjectArray *)ks
                                                 withOrgBouncycastleMathEcEndoGLVEndomorphism:(id<OrgBouncycastleMathEcEndoGLVEndomorphism>)glvEndomorphism {
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_withOrgBouncycastleMathEcEndoGLVEndomorphism_(ps, ks, glvEndomorphism);
}

+ (OrgBouncycastleMathEcECPoint *)implSumOfMultipliesWithOrgBouncycastleMathEcEndoECEndomorphism:(id<OrgBouncycastleMathEcEndoECEndomorphism>)endomorphism
                                                           withOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)ps
                                                                     withJavaMathBigIntegerArray:(IOSObjectArray *)ks {
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(endomorphism, ps, ks);
}

+ (OrgBouncycastleMathEcECPoint *)implSumOfMultipliesWithBooleanArray:(IOSBooleanArray *)negs
                        withOrgBouncycastleMathEcWNafPreCompInfoArray:(IOSObjectArray *)infos
                                                       withByteArray2:(IOSObjectArray *)wnafs {
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithBooleanArray_withOrgBouncycastleMathEcWNafPreCompInfoArray_withByteArray2_(negs, infos, wnafs);
}

+ (OrgBouncycastleMathEcECPoint *)implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p
                                                                      withJavaMathBigInteger:(JavaMathBigInteger *)k
                                                            withOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)q
                                                                      withJavaMathBigInteger:(JavaMathBigInteger *)l {
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(p, k, q, l);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 4, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 5, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 6, 7, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 8, 9, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 10, 9, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 13, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 13, 15, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 16, 17, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 18, 19, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x9, 20, 12, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 21, 19, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 22, 9, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 23, 9, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 23, 24, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0xa, 23, 25, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 26, 7, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 27, 28, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x8, 26, 29, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0xa, 26, 30, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0xa, 31, 9, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(isF2mCurveWithOrgBouncycastleMathEcECCurve:);
  methods[2].selector = @selector(isF2mFieldWithOrgBouncycastleMathFieldFiniteField:);
  methods[3].selector = @selector(isFpCurveWithOrgBouncycastleMathEcECCurve:);
  methods[4].selector = @selector(isFpFieldWithOrgBouncycastleMathFieldFiniteField:);
  methods[5].selector = @selector(sumOfMultipliesWithOrgBouncycastleMathEcECPointArray:withJavaMathBigIntegerArray:);
  methods[6].selector = @selector(sumOfTwoMultipliesWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  methods[7].selector = @selector(shamirsTrickWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  methods[8].selector = @selector(importPointWithOrgBouncycastleMathEcECCurve:withOrgBouncycastleMathEcECPoint:);
  methods[9].selector = @selector(montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray:withInt:withInt:);
  methods[10].selector = @selector(montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray:withInt:withInt:withOrgBouncycastleMathEcECFieldElement:);
  methods[11].selector = @selector(referenceMultiplyWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  methods[12].selector = @selector(validatePointWithOrgBouncycastleMathEcECPoint:);
  methods[13].selector = @selector(cleanPointWithOrgBouncycastleMathEcECCurve:withOrgBouncycastleMathEcECPoint:);
  methods[14].selector = @selector(implCheckResultWithOrgBouncycastleMathEcECPoint:);
  methods[15].selector = @selector(implShamirsTrickJsfWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  methods[16].selector = @selector(implShamirsTrickWNafWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  methods[17].selector = @selector(implShamirsTrickWNafWithOrgBouncycastleMathEcEndoECEndomorphism:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withJavaMathBigInteger:);
  methods[18].selector = @selector(implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray:withOrgBouncycastleMathEcECPointArray:withByteArray:withOrgBouncycastleMathEcECPointArray:withOrgBouncycastleMathEcECPointArray:withByteArray:);
  methods[19].selector = @selector(implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray:withJavaMathBigIntegerArray:);
  methods[20].selector = @selector(implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray:withJavaMathBigIntegerArray:withOrgBouncycastleMathEcEndoGLVEndomorphism:);
  methods[21].selector = @selector(implSumOfMultipliesWithOrgBouncycastleMathEcEndoECEndomorphism:withOrgBouncycastleMathEcECPointArray:withJavaMathBigIntegerArray:);
  methods[22].selector = @selector(implSumOfMultipliesWithBooleanArray:withOrgBouncycastleMathEcWNafPreCompInfoArray:withByteArray2:);
  methods[23].selector = @selector(implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:withOrgBouncycastleMathEcECPoint:withJavaMathBigInteger:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "isF2mCurve", "LOrgBouncycastleMathEcECCurve;", "isF2mField", "LOrgBouncycastleMathFieldFiniteField;", "isFpCurve", "isFpField", "sumOfMultiplies", "[LOrgBouncycastleMathEcECPoint;[LJavaMathBigInteger;", "sumOfTwoMultiplies", "LOrgBouncycastleMathEcECPoint;LJavaMathBigInteger;LOrgBouncycastleMathEcECPoint;LJavaMathBigInteger;", "shamirsTrick", "importPoint", "LOrgBouncycastleMathEcECCurve;LOrgBouncycastleMathEcECPoint;", "montgomeryTrick", "[LOrgBouncycastleMathEcECFieldElement;II", "[LOrgBouncycastleMathEcECFieldElement;IILOrgBouncycastleMathEcECFieldElement;", "referenceMultiply", "LOrgBouncycastleMathEcECPoint;LJavaMathBigInteger;", "validatePoint", "LOrgBouncycastleMathEcECPoint;", "cleanPoint", "implCheckResult", "implShamirsTrickJsf", "implShamirsTrickWNaf", "LOrgBouncycastleMathEcEndoECEndomorphism;LOrgBouncycastleMathEcECPoint;LJavaMathBigInteger;LJavaMathBigInteger;", "[LOrgBouncycastleMathEcECPoint;[LOrgBouncycastleMathEcECPoint;[B[LOrgBouncycastleMathEcECPoint;[LOrgBouncycastleMathEcECPoint;[B", "implSumOfMultiplies", "implSumOfMultipliesGLV", "[LOrgBouncycastleMathEcECPoint;[LJavaMathBigInteger;LOrgBouncycastleMathEcEndoGLVEndomorphism;", "LOrgBouncycastleMathEcEndoECEndomorphism;[LOrgBouncycastleMathEcECPoint;[LJavaMathBigInteger;", "[Z[LOrgBouncycastleMathEcWNafPreCompInfo;[[B", "implShamirsTrickFixedPoint" };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcECAlgorithms = { "ECAlgorithms", "org.bouncycastle.math.ec", ptrTable, methods, NULL, 7, 0x1, 24, 0, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcECAlgorithms;
}

@end

void OrgBouncycastleMathEcECAlgorithms_init(OrgBouncycastleMathEcECAlgorithms *self) {
  NSObject_init(self);
}

OrgBouncycastleMathEcECAlgorithms *new_OrgBouncycastleMathEcECAlgorithms_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcECAlgorithms, init)
}

OrgBouncycastleMathEcECAlgorithms *create_OrgBouncycastleMathEcECAlgorithms_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcECAlgorithms, init)
}

jboolean OrgBouncycastleMathEcECAlgorithms_isF2mCurveWithOrgBouncycastleMathEcECCurve_(OrgBouncycastleMathEcECCurve *c) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  return OrgBouncycastleMathEcECAlgorithms_isF2mFieldWithOrgBouncycastleMathFieldFiniteField_([((OrgBouncycastleMathEcECCurve *) nil_chk(c)) getField]);
}

jboolean OrgBouncycastleMathEcECAlgorithms_isF2mFieldWithOrgBouncycastleMathFieldFiniteField_(id<OrgBouncycastleMathFieldFiniteField> field) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  return [((id<OrgBouncycastleMathFieldFiniteField>) nil_chk(field)) getDimension] > 1 && [((JavaMathBigInteger *) nil_chk([field getCharacteristic])) isEqual:JreLoadStatic(OrgBouncycastleMathEcECConstants, TWO)] && [OrgBouncycastleMathFieldPolynomialExtensionField_class_() isInstance:field];
}

jboolean OrgBouncycastleMathEcECAlgorithms_isFpCurveWithOrgBouncycastleMathEcECCurve_(OrgBouncycastleMathEcECCurve *c) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  return OrgBouncycastleMathEcECAlgorithms_isFpFieldWithOrgBouncycastleMathFieldFiniteField_([((OrgBouncycastleMathEcECCurve *) nil_chk(c)) getField]);
}

jboolean OrgBouncycastleMathEcECAlgorithms_isFpFieldWithOrgBouncycastleMathFieldFiniteField_(id<OrgBouncycastleMathFieldFiniteField> field) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  return [((id<OrgBouncycastleMathFieldFiniteField>) nil_chk(field)) getDimension] == 1;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_sumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(IOSObjectArray *ps, IOSObjectArray *ks) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  if (ps == nil || ks == nil || ps->size_ != ks->size_ || ps->size_ < 1) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"point and scalar arrays should be non-null, and of equal, non-zero, length");
  }
  jint count = ps->size_;
  switch (count) {
    case 1:
    return [((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(ps, 0))) multiplyWithJavaMathBigInteger:IOSObjectArray_Get(ks, 0)];
    case 2:
    return OrgBouncycastleMathEcECAlgorithms_sumOfTwoMultipliesWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(IOSObjectArray_Get(ps, 0), IOSObjectArray_Get(ks, 0), IOSObjectArray_Get(ps, 1), IOSObjectArray_Get(ks, 1));
    default:
    break;
  }
  OrgBouncycastleMathEcECPoint *p = IOSObjectArray_Get(ps, 0);
  OrgBouncycastleMathEcECCurve *c = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getCurve]);
  IOSObjectArray *imported = [IOSObjectArray arrayWithLength:count type:OrgBouncycastleMathEcECPoint_class_()];
  IOSObjectArray_Set(imported, 0, p);
  for (jint i = 1; i < count; ++i) {
    IOSObjectArray_Set(imported, i, OrgBouncycastleMathEcECAlgorithms_importPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(c, IOSObjectArray_Get(ps, i)));
  }
  id<OrgBouncycastleMathEcEndoECEndomorphism> endomorphism = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(c)) getEndomorphism]);
  if ([OrgBouncycastleMathEcEndoGLVEndomorphism_class_() isInstance:endomorphism]) {
    return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_withOrgBouncycastleMathEcEndoGLVEndomorphism_(imported, ks, (id<OrgBouncycastleMathEcEndoGLVEndomorphism>) cast_check(endomorphism, OrgBouncycastleMathEcEndoGLVEndomorphism_class_())));
  }
  return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(imported, ks));
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_sumOfTwoMultipliesWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *P, JavaMathBigInteger *a, OrgBouncycastleMathEcECPoint *Q, JavaMathBigInteger *b) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *cp = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(P)) getCurve]);
  Q = OrgBouncycastleMathEcECAlgorithms_importPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(cp, Q);
  if ([cp isKindOfClass:[OrgBouncycastleMathEcECCurve_AbstractF2m class]]) {
    OrgBouncycastleMathEcECCurve_AbstractF2m *f2mCurve = (OrgBouncycastleMathEcECCurve_AbstractF2m *) cp;
    if ([((OrgBouncycastleMathEcECCurve_AbstractF2m *) nil_chk(f2mCurve)) isKoblitz]) {
      return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_([((OrgBouncycastleMathEcECPoint *) nil_chk([P multiplyWithJavaMathBigInteger:a])) addWithOrgBouncycastleMathEcECPoint:[((OrgBouncycastleMathEcECPoint *) nil_chk(Q)) multiplyWithJavaMathBigInteger:b]]);
    }
  }
  id<OrgBouncycastleMathEcEndoECEndomorphism> endomorphism = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(cp)) getEndomorphism]);
  if ([OrgBouncycastleMathEcEndoGLVEndomorphism_class_() isInstance:endomorphism]) {
    return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_withOrgBouncycastleMathEcEndoGLVEndomorphism_([IOSObjectArray arrayWithObjects:(id[]){ P, Q } count:2 type:OrgBouncycastleMathEcECPoint_class_()], [IOSObjectArray arrayWithObjects:(id[]){ a, b } count:2 type:JavaMathBigInteger_class_()], (id<OrgBouncycastleMathEcEndoGLVEndomorphism>) cast_check(endomorphism, OrgBouncycastleMathEcEndoGLVEndomorphism_class_())));
  }
  return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, a, Q, b));
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_shamirsTrickWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *P, JavaMathBigInteger *k, OrgBouncycastleMathEcECPoint *Q, JavaMathBigInteger *l) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *cp = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(P)) getCurve]);
  Q = OrgBouncycastleMathEcECAlgorithms_importPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(cp, Q);
  return OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECAlgorithms_implShamirsTrickJsfWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, k, Q, l));
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_importPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECCurve *c, OrgBouncycastleMathEcECPoint *p) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *cp = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getCurve]);
  if (![((OrgBouncycastleMathEcECCurve *) nil_chk(c)) equalsWithOrgBouncycastleMathEcECCurve:cp]) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"Point must be on the same curve");
  }
  return [c importPointWithOrgBouncycastleMathEcECPoint:p];
}

void OrgBouncycastleMathEcECAlgorithms_montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray_withInt_withInt_(IOSObjectArray *zs, jint off, jint len) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECAlgorithms_montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray_withInt_withInt_withOrgBouncycastleMathEcECFieldElement_(zs, off, len, nil);
}

void OrgBouncycastleMathEcECAlgorithms_montgomeryTrickWithOrgBouncycastleMathEcECFieldElementArray_withInt_withInt_withOrgBouncycastleMathEcECFieldElement_(IOSObjectArray *zs, jint off, jint len, OrgBouncycastleMathEcECFieldElement *scale_) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  IOSObjectArray *c = [IOSObjectArray arrayWithLength:len type:OrgBouncycastleMathEcECFieldElement_class_()];
  IOSObjectArray_Set(c, 0, IOSObjectArray_Get(nil_chk(zs), off));
  jint i = 0;
  while (++i < len) {
    IOSObjectArray_Set(c, i, [((OrgBouncycastleMathEcECFieldElement *) nil_chk(IOSObjectArray_Get(c, i - 1))) multiplyWithOrgBouncycastleMathEcECFieldElement:IOSObjectArray_Get(zs, off + i)]);
  }
  --i;
  if (scale_ != nil) {
    IOSObjectArray_Set(c, i, [((OrgBouncycastleMathEcECFieldElement *) nil_chk(IOSObjectArray_Get(c, i))) multiplyWithOrgBouncycastleMathEcECFieldElement:scale_]);
  }
  OrgBouncycastleMathEcECFieldElement *u = JreRetainedLocalValue([((OrgBouncycastleMathEcECFieldElement *) nil_chk(IOSObjectArray_Get(c, i))) invert]);
  while (i > 0) {
    jint j = off + i--;
    OrgBouncycastleMathEcECFieldElement *tmp = IOSObjectArray_Get(zs, j);
    IOSObjectArray_Set(zs, j, [((OrgBouncycastleMathEcECFieldElement *) nil_chk(IOSObjectArray_Get(c, i))) multiplyWithOrgBouncycastleMathEcECFieldElement:u]);
    u = [((OrgBouncycastleMathEcECFieldElement *) nil_chk(u)) multiplyWithOrgBouncycastleMathEcECFieldElement:tmp];
  }
  IOSObjectArray_Set(zs, off, u);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_referenceMultiplyWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *p, JavaMathBigInteger *k) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  JavaMathBigInteger *x = JreRetainedLocalValue([((JavaMathBigInteger *) nil_chk(k)) abs]);
  OrgBouncycastleMathEcECPoint *q = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getCurve])) getInfinity]);
  jint t = [((JavaMathBigInteger *) nil_chk(x)) bitLength];
  if (t > 0) {
    if ([x testBitWithInt:0]) {
      q = p;
    }
    for (jint i = 1; i < t; i++) {
      p = [((OrgBouncycastleMathEcECPoint *) nil_chk(p)) twice];
      if ([x testBitWithInt:i]) {
        q = [((OrgBouncycastleMathEcECPoint *) nil_chk(q)) addWithOrgBouncycastleMathEcECPoint:p];
      }
    }
  }
  return [k signum] < 0 ? [((OrgBouncycastleMathEcECPoint *) nil_chk(q)) negate] : q;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_validatePointWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECPoint *p) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  if (![((OrgBouncycastleMathEcECPoint *) nil_chk(p)) isValid]) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(@"Invalid point");
  }
  return p;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_cleanPointWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECCurve *c, OrgBouncycastleMathEcECPoint *p) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *cp = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getCurve]);
  if (![((OrgBouncycastleMathEcECCurve *) nil_chk(c)) equalsWithOrgBouncycastleMathEcECCurve:cp]) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"Point must be on the same curve");
  }
  return [c decodePointWithByteArray:[p getEncodedWithBoolean:false]];
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implCheckResultWithOrgBouncycastleMathEcECPoint_(OrgBouncycastleMathEcECPoint *p) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  if (![((OrgBouncycastleMathEcECPoint *) nil_chk(p)) isValidPartial]) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(@"Invalid result");
  }
  return p;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickJsfWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *P, JavaMathBigInteger *k, OrgBouncycastleMathEcECPoint *Q, JavaMathBigInteger *l) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *curve = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(P)) getCurve]);
  OrgBouncycastleMathEcECPoint *infinity = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(curve)) getInfinity]);
  OrgBouncycastleMathEcECPoint *PaddQ = JreRetainedLocalValue([P addWithOrgBouncycastleMathEcECPoint:Q]);
  OrgBouncycastleMathEcECPoint *PsubQ = JreRetainedLocalValue([P subtractWithOrgBouncycastleMathEcECPoint:Q]);
  IOSObjectArray *points = [IOSObjectArray arrayWithObjects:(id[]){ Q, PsubQ, P, PaddQ } count:4 type:OrgBouncycastleMathEcECPoint_class_()];
  [curve normalizeAllWithOrgBouncycastleMathEcECPointArray:points];
  IOSObjectArray *table = [IOSObjectArray arrayWithObjects:(id[]){ [((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(points, 3))) negate], [((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(points, 2))) negate], [((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(points, 1))) negate], [((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(points, 0))) negate], infinity, IOSObjectArray_Get(points, 0), IOSObjectArray_Get(points, 1), IOSObjectArray_Get(points, 2), IOSObjectArray_Get(points, 3) } count:9 type:OrgBouncycastleMathEcECPoint_class_()];
  IOSByteArray *jsf = OrgBouncycastleMathEcWNafUtil_generateJSFWithJavaMathBigInteger_withJavaMathBigInteger_(k, l);
  OrgBouncycastleMathEcECPoint *R = JreRetainedLocalValue(infinity);
  jint i = ((IOSByteArray *) nil_chk(jsf))->size_;
  while (--i >= 0) {
    jint jsfi = IOSByteArray_Get(jsf, i);
    jint kDigit = (JreRShift32((JreLShift32(jsfi, 24)), 28));
    jint lDigit = (JreRShift32((JreLShift32(jsfi, 28)), 28));
    jint index = 4 + (kDigit * 3) + lDigit;
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) twicePlusWithOrgBouncycastleMathEcECPoint:IOSObjectArray_Get(table, index)];
  }
  return R;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *P, JavaMathBigInteger *k, OrgBouncycastleMathEcECPoint *Q, JavaMathBigInteger *l) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jboolean negK = [((JavaMathBigInteger *) nil_chk(k)) signum] < 0;
  jboolean negL = [((JavaMathBigInteger *) nil_chk(l)) signum] < 0;
  JavaMathBigInteger *kAbs = JreRetainedLocalValue([k abs]);
  JavaMathBigInteger *lAbs = JreRetainedLocalValue([l abs]);
  jint minWidthP = OrgBouncycastleMathEcWNafUtil_getWindowSizeWithInt_withInt_([((JavaMathBigInteger *) nil_chk(kAbs)) bitLength], 8);
  jint minWidthQ = OrgBouncycastleMathEcWNafUtil_getWindowSizeWithInt_withInt_([((JavaMathBigInteger *) nil_chk(lAbs)) bitLength], 8);
  OrgBouncycastleMathEcWNafPreCompInfo *infoP = OrgBouncycastleMathEcWNafUtil_precomputeWithOrgBouncycastleMathEcECPoint_withInt_withBoolean_(P, minWidthP, true);
  OrgBouncycastleMathEcWNafPreCompInfo *infoQ = OrgBouncycastleMathEcWNafUtil_precomputeWithOrgBouncycastleMathEcECPoint_withInt_withBoolean_(Q, minWidthQ, true);
  {
    OrgBouncycastleMathEcECCurve *c = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(P)) getCurve]);
    jint combSize = OrgBouncycastleMathEcFixedPointUtil_getCombSizeWithOrgBouncycastleMathEcECCurve_(c);
    if (!negK && !negL && [k bitLength] <= combSize && [l bitLength] <= combSize && [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoP)) isPromoted] && [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoQ)) isPromoted]) {
      return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(P, k, Q, l);
    }
  }
  jint widthP = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoP)) getWidth]);
  jint widthQ = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoQ)) getWidth]);
  IOSObjectArray *preCompP = negK ? [infoP getPreCompNeg] : [infoP getPreComp];
  IOSObjectArray *preCompQ = negL ? [infoQ getPreCompNeg] : [infoQ getPreComp];
  IOSObjectArray *preCompNegP = negK ? [infoP getPreComp] : [infoP getPreCompNeg];
  IOSObjectArray *preCompNegQ = negL ? [infoQ getPreComp] : [infoQ getPreCompNeg];
  IOSByteArray *wnafP = OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthP, kAbs);
  IOSByteArray *wnafQ = OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthQ, lAbs);
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_withOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_(preCompP, preCompNegP, wnafP, preCompQ, preCompNegQ, wnafQ);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withJavaMathBigInteger_(id<OrgBouncycastleMathEcEndoECEndomorphism> endomorphism, OrgBouncycastleMathEcECPoint *P, JavaMathBigInteger *k, JavaMathBigInteger *l) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jboolean negK = [((JavaMathBigInteger *) nil_chk(k)) signum] < 0;
  jboolean negL = [((JavaMathBigInteger *) nil_chk(l)) signum] < 0;
  k = [k abs];
  l = [l abs];
  jint minWidth = OrgBouncycastleMathEcWNafUtil_getWindowSizeWithInt_withInt_(JavaLangMath_maxWithInt_withInt_([((JavaMathBigInteger *) nil_chk(k)) bitLength], [((JavaMathBigInteger *) nil_chk(l)) bitLength]), 8);
  OrgBouncycastleMathEcWNafPreCompInfo *infoP = OrgBouncycastleMathEcWNafUtil_precomputeWithOrgBouncycastleMathEcECPoint_withInt_withBoolean_(P, minWidth, true);
  OrgBouncycastleMathEcECPoint *Q = OrgBouncycastleMathEcEndoEndoUtil_mapPointWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPoint_(endomorphism, P);
  OrgBouncycastleMathEcWNafPreCompInfo *infoQ = OrgBouncycastleMathEcWNafUtil_precomputeWithPointMapWithOrgBouncycastleMathEcECPoint_withOrgBouncycastleMathEcECPointMap_withOrgBouncycastleMathEcWNafPreCompInfo_withBoolean_(Q, [((id<OrgBouncycastleMathEcEndoECEndomorphism>) nil_chk(endomorphism)) getPointMap], infoP, true);
  jint widthP = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoP)) getWidth]);
  jint widthQ = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoQ)) getWidth]);
  IOSObjectArray *preCompP = negK ? [infoP getPreCompNeg] : [infoP getPreComp];
  IOSObjectArray *preCompQ = negL ? [infoQ getPreCompNeg] : [infoQ getPreComp];
  IOSObjectArray *preCompNegP = negK ? [infoP getPreComp] : [infoP getPreCompNeg];
  IOSObjectArray *preCompNegQ = negL ? [infoQ getPreComp] : [infoQ getPreCompNeg];
  IOSByteArray *wnafP = OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthP, k);
  IOSByteArray *wnafQ = OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthQ, l);
  return OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_withOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_(preCompP, preCompNegP, wnafP, preCompQ, preCompNegQ, wnafQ);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickWNafWithOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_withOrgBouncycastleMathEcECPointArray_withOrgBouncycastleMathEcECPointArray_withByteArray_(IOSObjectArray *preCompP, IOSObjectArray *preCompNegP, IOSByteArray *wnafP, IOSObjectArray *preCompQ, IOSObjectArray *preCompNegQ, IOSByteArray *wnafQ) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jint len = JavaLangMath_maxWithInt_withInt_(((IOSByteArray *) nil_chk(wnafP))->size_, ((IOSByteArray *) nil_chk(wnafQ))->size_);
  OrgBouncycastleMathEcECCurve *curve = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(nil_chk(preCompP), 0))) getCurve]);
  OrgBouncycastleMathEcECPoint *infinity = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(curve)) getInfinity]);
  OrgBouncycastleMathEcECPoint *R = JreRetainedLocalValue(infinity);
  jint zeroes = 0;
  for (jint i = len - 1; i >= 0; --i) {
    jint wiP = i < wnafP->size_ ? IOSByteArray_Get(wnafP, i) : 0;
    jint wiQ = i < wnafQ->size_ ? IOSByteArray_Get(wnafQ, i) : 0;
    if ((wiP | wiQ) == 0) {
      ++zeroes;
      continue;
    }
    OrgBouncycastleMathEcECPoint *r = JreRetainedLocalValue(infinity);
    if (wiP != 0) {
      jint nP = JavaLangMath_absWithInt_(wiP);
      IOSObjectArray *tableP = wiP < 0 ? preCompNegP : preCompP;
      r = [((OrgBouncycastleMathEcECPoint *) nil_chk(r)) addWithOrgBouncycastleMathEcECPoint:IOSObjectArray_Get(tableP, JreURShift32(nP, 1))];
    }
    if (wiQ != 0) {
      jint nQ = JavaLangMath_absWithInt_(wiQ);
      IOSObjectArray *tableQ = wiQ < 0 ? preCompNegQ : preCompQ;
      r = [((OrgBouncycastleMathEcECPoint *) nil_chk(r)) addWithOrgBouncycastleMathEcECPoint:IOSObjectArray_Get(tableQ, JreURShift32(nQ, 1))];
    }
    if (zeroes > 0) {
      R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) timesPow2WithInt:zeroes];
      zeroes = 0;
    }
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) twicePlusWithOrgBouncycastleMathEcECPoint:r];
  }
  if (zeroes > 0) {
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) timesPow2WithInt:zeroes];
  }
  return R;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(IOSObjectArray *ps, IOSObjectArray *ks) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jint count = ((IOSObjectArray *) nil_chk(ps))->size_;
  IOSBooleanArray *negs = [IOSBooleanArray arrayWithLength:count];
  IOSObjectArray *infos = [IOSObjectArray arrayWithLength:count type:OrgBouncycastleMathEcWNafPreCompInfo_class_()];
  IOSObjectArray *wnafs = [IOSObjectArray arrayWithLength:count type:IOSClass_byteArray(1)];
  for (jint i = 0; i < count; ++i) {
    JavaMathBigInteger *ki = IOSObjectArray_Get(nil_chk(ks), i);
    *IOSBooleanArray_GetRef(negs, i) = ([((JavaMathBigInteger *) nil_chk(ki)) signum] < 0);
    ki = [ki abs];
    jint minWidth = OrgBouncycastleMathEcWNafUtil_getWindowSizeWithInt_withInt_([((JavaMathBigInteger *) nil_chk(ki)) bitLength], 8);
    OrgBouncycastleMathEcWNafPreCompInfo *info = OrgBouncycastleMathEcWNafUtil_precomputeWithOrgBouncycastleMathEcECPoint_withInt_withBoolean_(IOSObjectArray_Get(ps, i), minWidth, true);
    jint width = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(info)) getWidth]);
    IOSObjectArray_Set(infos, i, info);
    IOSObjectArray_Set(wnafs, i, OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(width, ki));
  }
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithBooleanArray_withOrgBouncycastleMathEcWNafPreCompInfoArray_withByteArray2_(negs, infos, wnafs);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesGLVWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_withOrgBouncycastleMathEcEndoGLVEndomorphism_(IOSObjectArray *ps, IOSObjectArray *ks, id<OrgBouncycastleMathEcEndoGLVEndomorphism> glvEndomorphism) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  JavaMathBigInteger *n = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk([((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(nil_chk(ps), 0))) getCurve])) getOrder]);
  jint len = ps->size_;
  IOSObjectArray *abs = [IOSObjectArray arrayWithLength:JreLShift32(len, 1) type:JavaMathBigInteger_class_()];
  for (jint i = 0, j = 0; i < len; ++i) {
    IOSObjectArray *ab = [((id<OrgBouncycastleMathEcEndoGLVEndomorphism>) nil_chk(glvEndomorphism)) decomposeScalarWithJavaMathBigInteger:[((JavaMathBigInteger *) nil_chk(IOSObjectArray_Get(nil_chk(ks), i))) modWithJavaMathBigInteger:n]];
    IOSObjectArray_Set(abs, j++, IOSObjectArray_Get(nil_chk(ab), 0));
    IOSObjectArray_Set(abs, j++, IOSObjectArray_Get(ab, 1));
  }
  if ([((id<OrgBouncycastleMathEcEndoGLVEndomorphism>) nil_chk(glvEndomorphism)) hasEfficientPointMap]) {
    return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(glvEndomorphism, ps, abs);
  }
  IOSObjectArray *pqs = [IOSObjectArray arrayWithLength:JreLShift32(len, 1) type:OrgBouncycastleMathEcECPoint_class_()];
  for (jint i = 0, j = 0; i < len; ++i) {
    OrgBouncycastleMathEcECPoint *p = IOSObjectArray_Get(ps, i);
    OrgBouncycastleMathEcECPoint *q = OrgBouncycastleMathEcEndoEndoUtil_mapPointWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPoint_(glvEndomorphism, p);
    IOSObjectArray_Set(pqs, j++, p);
    IOSObjectArray_Set(pqs, j++, q);
  }
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(pqs, abs);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPointArray_withJavaMathBigIntegerArray_(id<OrgBouncycastleMathEcEndoECEndomorphism> endomorphism, IOSObjectArray *ps, IOSObjectArray *ks) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jint halfCount = ((IOSObjectArray *) nil_chk(ps))->size_;
  jint fullCount = JreLShift32(halfCount, 1);
  IOSBooleanArray *negs = [IOSBooleanArray arrayWithLength:fullCount];
  IOSObjectArray *infos = [IOSObjectArray arrayWithLength:fullCount type:OrgBouncycastleMathEcWNafPreCompInfo_class_()];
  IOSObjectArray *wnafs = [IOSObjectArray arrayWithLength:fullCount type:IOSClass_byteArray(1)];
  id<OrgBouncycastleMathEcECPointMap> pointMap = JreRetainedLocalValue([((id<OrgBouncycastleMathEcEndoECEndomorphism>) nil_chk(endomorphism)) getPointMap]);
  for (jint i = 0; i < halfCount; ++i) {
    jint j0 = JreLShift32(i, 1);
    jint j1 = j0 + 1;
    JavaMathBigInteger *kj0 = IOSObjectArray_Get(nil_chk(ks), j0);
    *IOSBooleanArray_GetRef(negs, j0) = ([((JavaMathBigInteger *) nil_chk(kj0)) signum] < 0);
    kj0 = [kj0 abs];
    JavaMathBigInteger *kj1 = IOSObjectArray_Get(ks, j1);
    *IOSBooleanArray_GetRef(negs, j1) = ([((JavaMathBigInteger *) nil_chk(kj1)) signum] < 0);
    kj1 = [kj1 abs];
    jint minWidth = OrgBouncycastleMathEcWNafUtil_getWindowSizeWithInt_withInt_(JavaLangMath_maxWithInt_withInt_([((JavaMathBigInteger *) nil_chk(kj0)) bitLength], [((JavaMathBigInteger *) nil_chk(kj1)) bitLength]), 8);
    OrgBouncycastleMathEcECPoint *P = IOSObjectArray_Get(ps, i);
    OrgBouncycastleMathEcWNafPreCompInfo *infoP = OrgBouncycastleMathEcWNafUtil_precomputeWithOrgBouncycastleMathEcECPoint_withInt_withBoolean_(P, minWidth, true);
    OrgBouncycastleMathEcECPoint *Q = OrgBouncycastleMathEcEndoEndoUtil_mapPointWithOrgBouncycastleMathEcEndoECEndomorphism_withOrgBouncycastleMathEcECPoint_(endomorphism, P);
    OrgBouncycastleMathEcWNafPreCompInfo *infoQ = OrgBouncycastleMathEcWNafUtil_precomputeWithPointMapWithOrgBouncycastleMathEcECPoint_withOrgBouncycastleMathEcECPointMap_withOrgBouncycastleMathEcWNafPreCompInfo_withBoolean_(Q, pointMap, infoP, true);
    jint widthP = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoP)) getWidth]);
    jint widthQ = JavaLangMath_minWithInt_withInt_(8, [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(infoQ)) getWidth]);
    IOSObjectArray_Set(infos, j0, infoP);
    IOSObjectArray_Set(infos, j1, infoQ);
    IOSObjectArray_Set(wnafs, j0, OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthP, kj0));
    IOSObjectArray_Set(wnafs, j1, OrgBouncycastleMathEcWNafUtil_generateWindowNafWithInt_withJavaMathBigInteger_(widthQ, kj1));
  }
  return OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithBooleanArray_withOrgBouncycastleMathEcWNafPreCompInfoArray_withByteArray2_(negs, infos, wnafs);
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implSumOfMultipliesWithBooleanArray_withOrgBouncycastleMathEcWNafPreCompInfoArray_withByteArray2_(IOSBooleanArray *negs, IOSObjectArray *infos, IOSObjectArray *wnafs) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  jint len = 0;
  jint count = ((IOSObjectArray *) nil_chk(wnafs))->size_;
  for (jint i = 0; i < count; ++i) {
    len = JavaLangMath_maxWithInt_withInt_(len, ((IOSByteArray *) nil_chk(IOSObjectArray_Get(wnafs, i)))->size_);
  }
  OrgBouncycastleMathEcECCurve *curve = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(IOSObjectArray_Get(nil_chk([((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(IOSObjectArray_Get(nil_chk(infos), 0))) getPreComp]), 0))) getCurve]);
  OrgBouncycastleMathEcECPoint *infinity = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(curve)) getInfinity]);
  OrgBouncycastleMathEcECPoint *R = JreRetainedLocalValue(infinity);
  jint zeroes = 0;
  for (jint i = len - 1; i >= 0; --i) {
    OrgBouncycastleMathEcECPoint *r = JreRetainedLocalValue(infinity);
    for (jint j = 0; j < count; ++j) {
      IOSByteArray *wnaf = IOSObjectArray_Get(wnafs, j);
      jint wi = i < ((IOSByteArray *) nil_chk(wnaf))->size_ ? IOSByteArray_Get(wnaf, i) : 0;
      if (wi != 0) {
        jint n = JavaLangMath_absWithInt_(wi);
        OrgBouncycastleMathEcWNafPreCompInfo *info = IOSObjectArray_Get(infos, j);
        IOSObjectArray *table = (wi < 0 == IOSBooleanArray_Get(nil_chk(negs), j)) ? [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(info)) getPreComp] : [((OrgBouncycastleMathEcWNafPreCompInfo *) nil_chk(info)) getPreCompNeg];
        r = [((OrgBouncycastleMathEcECPoint *) nil_chk(r)) addWithOrgBouncycastleMathEcECPoint:IOSObjectArray_Get(table, JreURShift32(n, 1))];
      }
    }
    if (JreObjectEqualsEquals(r, infinity)) {
      ++zeroes;
      continue;
    }
    if (zeroes > 0) {
      R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) timesPow2WithInt:zeroes];
      zeroes = 0;
    }
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) twicePlusWithOrgBouncycastleMathEcECPoint:r];
  }
  if (zeroes > 0) {
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) timesPow2WithInt:zeroes];
  }
  return R;
}

OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcECAlgorithms_implShamirsTrickFixedPointWithOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_withOrgBouncycastleMathEcECPoint_withJavaMathBigInteger_(OrgBouncycastleMathEcECPoint *p, JavaMathBigInteger *k, OrgBouncycastleMathEcECPoint *q, JavaMathBigInteger *l) {
  OrgBouncycastleMathEcECAlgorithms_initialize();
  OrgBouncycastleMathEcECCurve *c = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getCurve]);
  jint combSize = OrgBouncycastleMathEcFixedPointUtil_getCombSizeWithOrgBouncycastleMathEcECCurve_(c);
  if ([((JavaMathBigInteger *) nil_chk(k)) bitLength] > combSize || [((JavaMathBigInteger *) nil_chk(l)) bitLength] > combSize) {
    @throw create_JavaLangIllegalStateException_initWithNSString_(@"fixed-point comb doesn't support scalars larger than the curve order");
  }
  OrgBouncycastleMathEcFixedPointPreCompInfo *infoP = OrgBouncycastleMathEcFixedPointUtil_precomputeWithOrgBouncycastleMathEcECPoint_(p);
  OrgBouncycastleMathEcFixedPointPreCompInfo *infoQ = OrgBouncycastleMathEcFixedPointUtil_precomputeWithOrgBouncycastleMathEcECPoint_(q);
  id<OrgBouncycastleMathEcECLookupTable> lookupTableP = JreRetainedLocalValue([((OrgBouncycastleMathEcFixedPointPreCompInfo *) nil_chk(infoP)) getLookupTable]);
  id<OrgBouncycastleMathEcECLookupTable> lookupTableQ = JreRetainedLocalValue([((OrgBouncycastleMathEcFixedPointPreCompInfo *) nil_chk(infoQ)) getLookupTable]);
  jint widthP = [infoP getWidth];
  jint widthQ = [infoQ getWidth];
  if (widthP != widthQ) {
    OrgBouncycastleMathEcFixedPointCombMultiplier *m = create_OrgBouncycastleMathEcFixedPointCombMultiplier_init();
    OrgBouncycastleMathEcECPoint *r1 = JreRetainedLocalValue([m multiplyWithOrgBouncycastleMathEcECPoint:p withJavaMathBigInteger:k]);
    OrgBouncycastleMathEcECPoint *r2 = JreRetainedLocalValue([m multiplyWithOrgBouncycastleMathEcECPoint:q withJavaMathBigInteger:l]);
    return [((OrgBouncycastleMathEcECPoint *) nil_chk(r1)) addWithOrgBouncycastleMathEcECPoint:r2];
  }
  jint width = widthP;
  jint d = JreIntDiv((combSize + width - 1), width);
  OrgBouncycastleMathEcECPoint *R = JreRetainedLocalValue([((OrgBouncycastleMathEcECCurve *) nil_chk(c)) getInfinity]);
  jint fullComb = d * width;
  IOSIntArray *K = OrgBouncycastleMathRawNat_fromBigIntegerWithInt_withJavaMathBigInteger_(fullComb, k);
  IOSIntArray *L = OrgBouncycastleMathRawNat_fromBigIntegerWithInt_withJavaMathBigInteger_(fullComb, l);
  jint top = fullComb - 1;
  for (jint i = 0; i < d; ++i) {
    jint secretIndexK = 0;
    jint secretIndexL = 0;
    for (jint j = top - i; j >= 0; j -= d) {
      jint secretBitK = JreURShift32(IOSIntArray_Get(nil_chk(K), JreURShift32(j, 5)), (j & (jint) 0x1F));
      secretIndexK ^= JreURShift32(secretBitK, 1);
      JreLShiftAssignInt(&secretIndexK, 1);
      secretIndexK ^= secretBitK;
      jint secretBitL = JreURShift32(IOSIntArray_Get(nil_chk(L), JreURShift32(j, 5)), (j & (jint) 0x1F));
      secretIndexL ^= JreURShift32(secretBitL, 1);
      JreLShiftAssignInt(&secretIndexL, 1);
      secretIndexL ^= secretBitL;
    }
    OrgBouncycastleMathEcECPoint *addP = JreRetainedLocalValue([((id<OrgBouncycastleMathEcECLookupTable>) nil_chk(lookupTableP)) lookupVarWithInt:secretIndexK]);
    OrgBouncycastleMathEcECPoint *addQ = JreRetainedLocalValue([((id<OrgBouncycastleMathEcECLookupTable>) nil_chk(lookupTableQ)) lookupVarWithInt:secretIndexL]);
    OrgBouncycastleMathEcECPoint *T = JreRetainedLocalValue([((OrgBouncycastleMathEcECPoint *) nil_chk(addP)) addWithOrgBouncycastleMathEcECPoint:addQ]);
    R = [((OrgBouncycastleMathEcECPoint *) nil_chk(R)) twicePlusWithOrgBouncycastleMathEcECPoint:T];
  }
  return [((OrgBouncycastleMathEcECPoint *) nil_chk([((OrgBouncycastleMathEcECPoint *) nil_chk(R)) addWithOrgBouncycastleMathEcECPoint:[infoP getOffset]])) addWithOrgBouncycastleMathEcECPoint:[infoQ getOffset]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcECAlgorithms)
