//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/ECLookupTable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleMathEcECLookupTable")
#ifdef RESTRICT_OrgBouncycastleMathEcECLookupTable
#define INCLUDE_ALL_OrgBouncycastleMathEcECLookupTable 0
#else
#define INCLUDE_ALL_OrgBouncycastleMathEcECLookupTable 1
#endif
#undef RESTRICT_OrgBouncycastleMathEcECLookupTable

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleMathEcECLookupTable_) && (INCLUDE_ALL_OrgBouncycastleMathEcECLookupTable || defined(INCLUDE_OrgBouncycastleMathEcECLookupTable))
#define OrgBouncycastleMathEcECLookupTable_

@class JavaLangInteger;
@class OrgBouncycastleMathEcECPoint;

@protocol OrgBouncycastleMathEcECLookupTable < JavaObject >

- (jint)getSize;

- (OrgBouncycastleMathEcECPoint *)lookupWithInt:(jint)index;

- (OrgBouncycastleMathEcECPoint *)lookupVarWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcECLookupTable)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleMathEcECLookupTable)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleMathEcECLookupTable")
