//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/WNafPreCompInfo.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "org/bouncycastle/math/ec/ECPoint.h"
#include "org/bouncycastle/math/ec/WNafPreCompInfo.h"

#if __has_feature(objc_arc)
#error "org/bouncycastle/math/ec/WNafPreCompInfo must not be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation OrgBouncycastleMathEcWNafPreCompInfo

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgBouncycastleMathEcWNafPreCompInfo_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)decrementPromotionCountdown {
  jint t = JreLoadVolatileInt(&promotionCountdown_);
  if (t > 0) {
    JreAssignVolatileInt(&promotionCountdown_, --t);
  }
  return t;
}

- (jint)getPromotionCountdown {
  return JreLoadVolatileInt(&promotionCountdown_);
}

- (void)setPromotionCountdownWithInt:(jint)promotionCountdown {
  JreAssignVolatileInt(&self->promotionCountdown_, promotionCountdown);
}

- (jboolean)isPromoted {
  return JreLoadVolatileInt(&promotionCountdown_) <= 0;
}

- (jint)getConfWidth {
  return confWidth_;
}

- (void)setConfWidthWithInt:(jint)confWidth {
  self->confWidth_ = confWidth;
}

- (IOSObjectArray *)getPreComp {
  return preComp_;
}

- (void)setPreCompWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preComp {
  JreStrongAssign(&self->preComp_, preComp);
}

- (IOSObjectArray *)getPreCompNeg {
  return preCompNeg_;
}

- (void)setPreCompNegWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)preCompNeg {
  JreStrongAssign(&self->preCompNeg_, preCompNeg);
}

- (OrgBouncycastleMathEcECPoint *)getTwice {
  return twice_;
}

- (void)setTwiceWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)twice {
  JreStrongAssign(&self->twice_, twice);
}

- (jint)getWidth {
  return width_;
}

- (void)setWidthWithInt:(jint)width {
  self->width_ = width;
}

- (void)dealloc {
  RELEASE_(preComp_);
  RELEASE_(preCompNeg_);
  RELEASE_(twice_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "[LOrgBouncycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "[LOrgBouncycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 4, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(decrementPromotionCountdown);
  methods[2].selector = @selector(getPromotionCountdown);
  methods[3].selector = @selector(setPromotionCountdownWithInt:);
  methods[4].selector = @selector(isPromoted);
  methods[5].selector = @selector(getConfWidth);
  methods[6].selector = @selector(setConfWidthWithInt:);
  methods[7].selector = @selector(getPreComp);
  methods[8].selector = @selector(setPreCompWithOrgBouncycastleMathEcECPointArray:);
  methods[9].selector = @selector(getPreCompNeg);
  methods[10].selector = @selector(setPreCompNegWithOrgBouncycastleMathEcECPointArray:);
  methods[11].selector = @selector(getTwice);
  methods[12].selector = @selector(setTwiceWithOrgBouncycastleMathEcECPoint:);
  methods[13].selector = @selector(getWidth);
  methods[14].selector = @selector(setWidthWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "promotionCountdown_", "I", .constantValue.asLong = 0, 0x40, -1, -1, -1, -1 },
    { "confWidth_", "I", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "preComp_", "[LOrgBouncycastleMathEcECPoint;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "preCompNeg_", "[LOrgBouncycastleMathEcECPoint;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "twice_", "LOrgBouncycastleMathEcECPoint;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "width_", "I", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setPromotionCountdown", "I", "setConfWidth", "setPreComp", "[LOrgBouncycastleMathEcECPoint;", "setPreCompNeg", "setTwice", "LOrgBouncycastleMathEcECPoint;", "setWidth" };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcWNafPreCompInfo = { "WNafPreCompInfo", "org.bouncycastle.math.ec", ptrTable, methods, fields, 7, 0x1, 15, 6, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcWNafPreCompInfo;
}

@end

void OrgBouncycastleMathEcWNafPreCompInfo_init(OrgBouncycastleMathEcWNafPreCompInfo *self) {
  NSObject_init(self);
  JreAssignVolatileInt(&self->promotionCountdown_, 4);
  self->confWidth_ = -1;
  JreStrongAssign(&self->preComp_, nil);
  JreStrongAssign(&self->preCompNeg_, nil);
  JreStrongAssign(&self->twice_, nil);
  self->width_ = -1;
}

OrgBouncycastleMathEcWNafPreCompInfo *new_OrgBouncycastleMathEcWNafPreCompInfo_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcWNafPreCompInfo, init)
}

OrgBouncycastleMathEcWNafPreCompInfo *create_OrgBouncycastleMathEcWNafPreCompInfo_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcWNafPreCompInfo, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcWNafPreCompInfo)
