//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/math/ec/WTauNafMultiplier.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleMathEcWTauNafMultiplier")
#ifdef RESTRICT_OrgBouncycastleMathEcWTauNafMultiplier
#define INCLUDE_ALL_OrgBouncycastleMathEcWTauNafMultiplier 0
#else
#define INCLUDE_ALL_OrgBouncycastleMathEcWTauNafMultiplier 1
#endif
#undef RESTRICT_OrgBouncycastleMathEcWTauNafMultiplier

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastleMathEcWTauNafMultiplier_) && (INCLUDE_ALL_OrgBouncycastleMathEcWTauNafMultiplier || defined(INCLUDE_OrgBouncycastleMathEcWTauNafMultiplier))
#define OrgBouncycastleMathEcWTauNafMultiplier_

#define RESTRICT_OrgBouncycastleMathEcAbstractECMultiplier 1
#define INCLUDE_OrgBouncycastleMathEcAbstractECMultiplier 1
#include "org/bouncycastle/math/ec/AbstractECMultiplier.h"

@class JavaMathBigInteger;
@class OrgBouncycastleMathEcECPoint;

@interface OrgBouncycastleMathEcWTauNafMultiplier : OrgBouncycastleMathEcAbstractECMultiplier
@property (readonly, copy, class) NSString *PRECOMP_NAME NS_SWIFT_NAME(PRECOMP_NAME);

#pragma mark Public

- (instancetype _Nonnull)init;

#pragma mark Protected

- (OrgBouncycastleMathEcECPoint *)multiplyPositiveWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)point
                                                            withJavaMathBigInteger:(JavaMathBigInteger *)k;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcWTauNafMultiplier)

inline NSString *OrgBouncycastleMathEcWTauNafMultiplier_get_PRECOMP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgBouncycastleMathEcWTauNafMultiplier_PRECOMP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleMathEcWTauNafMultiplier, PRECOMP_NAME, NSString *)

FOUNDATION_EXPORT void OrgBouncycastleMathEcWTauNafMultiplier_init(OrgBouncycastleMathEcWTauNafMultiplier *self);

FOUNDATION_EXPORT OrgBouncycastleMathEcWTauNafMultiplier *new_OrgBouncycastleMathEcWTauNafMultiplier_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleMathEcWTauNafMultiplier *create_OrgBouncycastleMathEcWTauNafMultiplier_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleMathEcWTauNafMultiplier)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleMathEcWTauNafMultiplier")
