//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./jmulticard/jmulticard-j2obc/java/org/bouncycastle/pqc/crypto/frodo/FrodoKeyParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters")
#ifdef RESTRICT_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters 1
#endif
#undef RESTRICT_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters || defined(INCLUDE_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters))
#define OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters_

#define RESTRICT_OrgBouncycastleCryptoParamsAsymmetricKeyParameter 1
#define INCLUDE_OrgBouncycastleCryptoParamsAsymmetricKeyParameter 1
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"

@class JavaLangBoolean;
@class OrgBouncycastlePqcCryptoFrodoFrodoParameters;

@interface OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters : OrgBouncycastleCryptoParamsAsymmetricKeyParameter

#pragma mark Public

- (instancetype _Nonnull)initWithBoolean:(jboolean)isPrivate
withOrgBouncycastlePqcCryptoFrodoFrodoParameters:(OrgBouncycastlePqcCryptoFrodoFrodoParameters *)params;

- (OrgBouncycastlePqcCryptoFrodoFrodoParameters *)getParameters;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)initWithBoolean:(jboolean)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters)

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters_initWithBoolean_withOrgBouncycastlePqcCryptoFrodoFrodoParameters_(OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters *self, jboolean isPrivate, OrgBouncycastlePqcCryptoFrodoFrodoParameters *params);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters *new_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters_initWithBoolean_withOrgBouncycastlePqcCryptoFrodoFrodoParameters_(jboolean isPrivate, OrgBouncycastlePqcCryptoFrodoFrodoParameters *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters *create_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters_initWithBoolean_withOrgBouncycastlePqcCryptoFrodoFrodoParameters_(jboolean isPrivate, OrgBouncycastlePqcCryptoFrodoFrodoParameters *params);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoFrodoFrodoKeyParameters")
